### ISSUE TITLE
passive cooking without mats

### ISSUE THREAD

**Issue by miehkmezz** [MelvorIdle/melvoridle.github.io#1522] opened 2021-10-26 21:26 UTC
**Describe the bug**
 able to cook meat pies without any meat in the inventory

**To Reproduce**
1. Go to cooking, have flour and meat. and start cooking. (I had 2k flour and 150 meat)
2. start active cooking whale, and afk cooking meat pie
3. go afk, and for me, it kept and is still cooking pies when I am not online. even thou I ran out of meat over 1k pies a go.
4. this works only if you have the game fully closed. if its in the background it gives the fail to cook.

**Expected behavior**
I expected the cooking to stop when materials end.

**Screenshots**

**Browser**
latest version of firerox.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
no scripts

**Comment by coolrox95** [comment] 2021-10-30 06:49
Duplicate of #1424

**Closed by coolrox95** 2021-10-30 06:49 UTC
Labels: Duplicate
