### ISSUE TITLE
Mole+ Octopus Synergy when fishing is bugged

### ISSUE THREAD

**Issue by igniteice** [MelvorIdle/melvoridle.github.io#1314] opened 2021-09-02 20:25 UTC
**Describe the bug**
When fishing with the Mole + Octopus synergy, moles and octopus are randomly consumed. The synergy says that when you a receive a gem from mining/fishing, there is a 15% chance to get another random gem. This implies that the Mole tablet should be consumed when a special item is caught -- might like when using Leprechaun+Monkey on Thieving, Monkey tablets are only consumed when an item is received.

However, with the Mole, it is used almost every fishing event, but sometimes it isn't. The amount of fish caught doesn't seem to affect it. Furthermore, even when you do catch a special, sometimes the mole tablets aren't used at all. Even further, the octopus tablets are randomly consumed as well. Sometimes it will use 1 of them, sometimes 2 of them, even when specials aren't being caught.

**To Reproduce**
1. Go to 'Fishing'
2. Equip Mole + Octopus tablets
3. Fish.

**Expected behavior**
I expect one octopus tablet to be consumed every fishing action, and when catching a gem (which is ~95% of the time when receiving a special), it should use 1 Mole and 2 Octopus tablets.

**Screenshots**

**Browser**
Steam.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No.

**Comment by kellewic** [comment] 2021-09-13 15:37
Seeing similar but my observations are the following:

1. Have tablets equipped
2. Start fishing
3. 2x Octopus consumed on every action
4. Once a gem is found, 1x Mole and 2x Octopus were consumed (intended behavior)
5. On every subsequence action, 1x Mole and 2x Octopus consumed

Unequipping Mole causes Octopus to be consumed 1 per action as normal. Equipping Mole again, causes #5 to happen regardless of if a gem is found.

This combination works as you would expect for mining.

**Comment by coolrox95** [comment] 2021-11-11 05:01
Fixed as of Beta v1.0.

**Closed by coolrox95** 2021-11-11 05:01 UTC
Labels: bug, In Progress
