### ISSUE TITLE
[Spelling/Grammar]: Shop -> Slayer -> Generous Resupply

### ISSUE THREAD

**Issue by zzsamzzsam** [MelvorIdle/melvoridle.github.io#1964] opened 2021-12-24 01:52 UTC
### What text is wrong?

+$1,000 Magic Bones

theres a $

### What is the correct spelling or grammar?

+1,000 Magic Bones

**Comment by MelvorIdle** [comment] 2021-12-24 06:49
Duplicate of #1959

**Closed by MelvorIdle** 2021-12-24 06:49 UTC
Labels: spelling/grammar
