### ISSUE TITLE
[Bug]: HP and Defence levels reset after completing Tutorial Island

### ISSUE THREAD

**Issue by dalxyon** [MelvorIdle/melvoridle.github.io#1643] opened 2021-11-11 20:13 UTC
### Describe the bug

My HP and Defence levels were well into the 60s, almost 70 before the update. After the update to v1.00 and following through the Tutorial Island, my Defence level was reset to 3 and HP was reset to 10. I thought nothing of it because I figured it would go back to where it should be after the tutorial is complete but after completing the entire tutorial my Defence level remains at level 3 and my HP is 10. I am currently training it to get back to where I was, but if this can be reset while keeping the Tutorial Island progress completed, that would be greatly appreciated.

Note that this is on my "Adventure Mode" character. My "Hardcore Mode" character didn't even get the prompt to start the tutorial so that character was not affected.

### Screenshots

![image](https://user-images.githubusercontent.com/94140918/141362467-fb7b87de-431d-48fb-b03b-52e15cea2816.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2021-11-11 20:18
Duplicate of #1626

**Closed by coolrox95** 2021-11-11 20:18 UTC
Labels: Duplicate

**Comment by dalxyon** [comment] 2021-11-11 20:21
I don't believe this is a duplicate. My progress reset is very different than the ticket you tagged.

**Comment by dalxyon** [comment] 2021-11-11 21:02
> Duplicate of #1626

I don't believe this is a duplicate. My progress reset is very different than the ticket you tagged.
