### ISSUE TITLE
[Bug]: Bonfire not working

### ISSUE THREAD

**Issue by aolson078** [MelvorIdle/melvoridle.github.io#2265] opened 2022-03-01 12:51 UTC
### Describe the bug

When I click the firemaking skill, my bonfire timer is always halfway, and decreasing, but when it finishes I cant burn more. I dont believe I'm getting the bonus xp to begin with either but I could be wrong.  I'm using the Brave broswer

### Reproduction Steps

Go to firemaking

### Expected behaviour

Bonfire should be at 0 until started

### Screenshots

![image](https://user-images.githubusercontent.com/69769089/156171910-52d322ca-a75e-4ac5-b181-e9333da90400.png)

Never clicked on light bonfire

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1806

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-06 19:52
Duplicate of #1903

**Closed by coolrox95** 2022-03-06 19:52 UTC
Labels: bug, Duplicate
