### ISSUE TITLE
[Bug]: calculating offline progression while cooking

### ISSUE THREAD

**Issue by Dread-bane** [MelvorIdle/melvoridle.github.io#2300] opened 2022-03-05 21:37 UTC
### Describe the bug

Loading in to the game after about and hour of offline progress to do farming it showed with error for cooking.

### Reproduction Steps

Haven't been able to reproduce unfortunately.

### Expected behaviour

Open app for offline progress to get cooked food.

### Save Link

https://melvoridle.com/save/Zc9VeKcE

### Screenshots

![Screenshot_20220305-131956_Melvor Idle](https://user-images.githubusercontent.com/74339581/156900589-0b7a23a7-e902-4bf2-befe-e2bcb6aec415.jpg)

### Console output

Error message: An error occured while processing ticks offline:
Active Skill: COOKING
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'hasAnimation')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'hasAnimation')
    at getItemMedia (https://android.melvoridle.com/assets/js/game/main.js?1822:282:58)
    at https://android.melvoridle.com/assets/js/built/game.js?1822:88:1840
    at Map.forEach (<anonymous>)
    at Game.createOfflineModal (https://android.melvoridle.com/assets/js/built/game.js?1822:88:1695)
    at https://android.melvoridle.com/assets/js/built/game.js?1822:70:812
Current Equipment:
Helmet: Crown_of_Rhaelyx
Platebody: Cooking_Apron
Platelegs: Terran_God_Platelegs
Boots: Boots_Of_Stealth
Weapon: Miolite_Sceptre
Shield: Fine_Coinpurse
Amulet: Amulet_of_Fishing
Ring: Aorpheats_Signet_Ring
Gloves: Gloves_of_Silence
Quiver: Ancient_Arrow
Cape: Cooking_Skillcape

Skill Information:
Is Active: true

Selected Cooking Recipes:
Fire: 11
Furnace: 30
Active Cooking Category: Fire
Passive Cooking Categories: Furnace
Stockpile Contents:
Furnace: item: Carrot_Cake qty: 136

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1822

### Are you using any scripts or extensions?

No

**Comment by Halzyion** [comment] 2022-03-05 22:07
Same :( error:

An error occured while processing ticks offline:
Active Skill: COOKING
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'items[itemID].hasAnimation')
Stack Trace:
getItemMedia@https://ios.melvoridle.com/assets/js/game/main.js?1822:282:57
@https://ios.melvoridle.com/assets/js/built/game.js?1822:88:1852
forEach@[native code]
createOfflineModal@https://ios.melvoridle.com/assets/js/built/game.js?1822:88:1702
@https://ios.melvoridle.com/assets/js/built/game.js?1822:70:830
Current Equipment:
Helmet: Dragon_Helmet
Platebody: Dragon_Platebody
Platelegs: Dragon_Platelegs
Boots: Dragon_Boots
Weapon: Dragon_2H_Sword
Amulet: Silver_Ruby_Necklace
Ring: Aorpheats_Signet_Ring
Gloves: Dragon_Gloves
Cape: Knights_Cape

Skill Information:
Is Active: true

Selected Cooking Recipes:
Fire: 11
Active Cooking Category: Fire
Passive Cooking Categories: 
Stockpile Contents:

**Comment by coolrox95** [comment] 2022-03-06 00:00
Duplicate of #2242

**Closed by coolrox95** 2022-03-06 00:00 UTC
Labels: bug, Duplicate
