### ISSUE TITLE
[Bug]: <The bug that was fixed>

### ISSUE THREAD

**Issue by Babeblade** [MelvorIdle/melvoridle.github.io#2323] opened 2022-03-12 04:21 UTC
### Describe the bug

The same old bug came back, before i went to sleep i left the game on combat tab and locked the screen, after waking up and unlocking my phone i got like 4-5 kill loot poopups and the the game insta cloud saved so i lost 1,2-1,4k master farmer kills through the night . I would suggest maybe making a check with the cloud server how long has it passed or smth, because this bug is game breaking. 

### Reproduction Steps

 Lock screen while in app and after couple of hours unlock it and the game will only give you couple of min of combat registered

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-15 19:35
Duplicate of #2316

**Closed by coolrox95** 2022-03-15 19:35 UTC
Labels: bug, Duplicate
