### ISSUE TITLE
[Bug]: Crow + Octopus summoning synergy not raising base rune amount RE doubling

### ISSUE THREAD

**Issue by tbonemalone69** [MelvorIdle/melvoridle.github.io#3120] opened 2022-12-26 17:02 UTC
### Describe the bug

Hello there! Been playing this game for a few months now and absolutely loving it. I finally am dabbling in magic (to beat earth dungeon) and am getting to the point where I want to amass mist runes (for cloudburst spam). With that said, I leveled herblore to unlock elemental potions and summoning to unlock crow/octopus/bear. And so now for the part that is confusing me.

I am making mist runes. I'm at 95 mist mastery (7 runes crafted/craft) but not 95 runecrafting mastery (so not getting additional +5 yet). I have tier 3 elemental potions equipped (25 percent chance to craft 6 elemental runes), along with crow summon (+2 addl rune) and octopus synergy (+5 base rune when using water aka mist here). This leads to a non-doubled craft of 14 mist, with additional +6 random elemental runes. When doubling gets procced, I only get 21 mist runes. By my math, it should be 28 (14*2) or 26 ((7 base + 5 octo synergy)*2 + 2 (crow)). Instead it's giving me 21, which seems to be my runecrafting-only base (7/craft) doubled to 14, then 7 added on (from crow+octopus synergy).

Is this how doubling is supposed to work? It only doubles the base amount from runecrafting skill/craft amount? This is especially confusing/misleading because crow+octopus synergy specifically states that it adds +5 runes to the base amount. Crow is less clear, in that it doesn't denote it adds to "base" rune amount.

PS: Just wanted to say that this game is fantastic, and your work is something to be proud of. I've been really enjoying my time. Thank you!

### Reproduction Steps

1. Equip crow+octo summon synergy
2. Runecraft mist rune (haven't tested on steam rune).
3. Review output amount relative to what should be produced per the summon descriptions. 
![Screenshot_20221226-073812](https://user-images.githubusercontent.com/121451244/209569747-79bd8d13-5817-46b4-b584-7478f2b0e5b6.jpg)

### Expected behaviour

As stated above, it seems _at least_ the octopus synergy is worded incorrectly (adding to **base** rune amount) or the synergy is not working properly (adding +5 runes _after_ doubling).

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

Yes

**Comment by tbonemalone69** [comment] 2022-12-26 17:02
Only mod I'm using is "Show Skill Modifiers".

**Comment by coolrox95** [comment] 2023-03-25 07:17
Duplicate of #3095

**Closed by coolrox95** 2023-03-25 07:17 UTC
Labels: bug, Duplicate
