### ISSUE TITLE
Compost All

### ISSUE THREAD

**Issue by For-Chan** [MelvorIdle/melvoridle.github.io#102] opened 2020-02-24 09:53 UTC
**Describe the bug**
When clicking to "Compost all using available compost for 2000 Gold", it will deduct 2000 gold no matter if you have compost, if all allotments are composted or not.
It will not charge you 2000 gold if plants are currently growing or ready for harvest.

Tested with Allotments, Herbs and Trees.

**To Reproduce**
1. Go to Farming
2. Click "Compost All..." while there is nothing to harvest, nothing growing.
3. When all spots are filled with compost OR if you do not possess any compost,
click "Compost All..." again.
4. Watch your money

**Expected behavior**
To not cost me gold if I accidentally click the button while all spots are currently filled with compost.
In comparison, when clicking Harvest/Plant All, it will not charge gold if it does not plant/harvest.

![gold](https://user-images.githubusercontent.com/61410171/75206271-e296d480-572a-11ea-9d62-f1351184fef1.JPG)

**Comment by mrDLSable** [comment] 2020-02-24 16:27
I think this is functioning as intended. But perhaps a confirmation dialog would be nice. In that confirmation dialog it could tell you if you have enough compost.

**Comment by For-Chan** [comment] 2020-02-25 01:21
Maybe I worded it poorly. It will charge you 2000 gold when it does not place compost. It wont deduct compost, only gold.
When harvesting or planting, it will not charge gold if it does not plant/harvest.

**Comment by MelvorIdle** [comment] 2020-02-25 03:17
I will change it so it does not charge you for using zero compost.

**Comment by MelvorIdle** [comment] 2020-02-26 02:42
Confirmed fixed in v0.13

**Closed by MelvorIdle** 2020-02-26 02:42 UTC
Labels: bug
