### ISSUE TITLE
[Bug]: Green Process Bar sticks and jumps on woodcutting iOS mobile 

### ISSUE THREAD

**Issue by Hellscaretaker** [MelvorIdle/melvoridle.github.io#1666] opened 2021-11-12 15:04 UTC
### Describe the bug

Instead of a continuous left to right scroll of the green process bar on Woodcutting on every second loop of the bar, it sticks and jumps across the screen.

### Reproduction Steps

Select woodcutting
choice normal tree

### Expected behaviour

Before Beta it was a continuous left to right of the green process bar.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1285

### Are you using any scripts or extensions?

No

**Comment by IndexIllusion** [comment] 2021-11-12 20:46
I have experienced this same issue, it seems to happen all the time and it causes the progress bars to lag on the screen.

**Comment by MelvorIdle** [comment] 2021-11-13 00:31
Duplicate of #1636

**Closed by MelvorIdle** 2021-11-13 00:31 UTC
Labels: bug
