### ISSUE TITLE
99 Agility not showing correct numbers [Desktop]

### ISSUE THREAD

**Issue by TheSmeegan** [MelvorIdle/melvoridle.github.io#1251] opened 2021-08-19 18:03 UTC
Agility not showing correctly updated numbers for 99 Agility. Not sure if bug but wanted to report.

https://imgur.com/a/3IfuhIq

**Comment by coolrox95** [comment] 2021-08-20 09:15
Duplicate of #1240

**Closed by coolrox95** 2021-08-20 09:15 UTC
Labels: Duplicate
