### ISSUE TITLE
Losing Offline Progress due to some bug

### ISSUE THREAD

**Issue by Code60** [MelvorIdle/melvoridle.github.io#1525] opened 2021-10-27 09:07 UTC
**Describe the bug**
I get no offline progress

**To Reproduce**
1. Start a skill
2. Let it do its work on in the background while doing schoolwork for example
3. Open to see progress

**Expected behavior**
I should be able to get and see offline progress

**Screenshots**

![20211027_111747](https://user-images.githubusercontent.com/31903776/139035510-839ad14b-b8e8-4559-b010-9e881d21ac61.jpg)

**Browser**
Microsoft Edge

**Comment by coolrox95** [comment] 2021-11-04 08:10
Duplicate of #1478

**Closed by coolrox95** 2021-11-04 08:10 UTC
Labels: Duplicate
