### ISSUE TITLE
Gem gloves Glitch??

### ISSUE THREAD

**Issue by t0m-dot-com** [MelvorIdle/melvoridle.github.io#1203] opened 2021-08-14 10:09 UTC
**Describe the bug**
When mining Rune essence Gem glove charges are being used while not producing gems (as intended)

**To Reproduce**
1. Go to 'mining'
2. Click on 'equip gem gloves'
3. Click on 'mine rune essence'

**Expected behavior**
gems shouldn't be given, but charges shouldn't be used (i believe)

**Browser**
Microsoft Edge
Version 93.0.961.18 (Official build) beta (64-bit)

**Comment by coolrox95** [comment] 2021-08-15 08:11
Duplicate of #1201

**Closed by coolrox95** 2021-08-15 08:11 UTC
Labels: Duplicate
