### ISSUE TITLE
Golbin Raid UI glitch item stats with phone

### ISSUE THREAD

**Issue by CopyrightA** [MelvorIdle/melvoridle.github.io#789] opened 2021-03-08 17:47 UTC
**Describe the bug**
Checking stats on the item pops up in the background and I’m unable to view it. This is only on the phone.

**To Reproduce**
Golbin Raid on phone (One Plus N-100 Nordic 720p resolution)
Finish wave get a piece of item you already have equipped and then click on the right side of the icon to view the stats of the item and the window pops up in the background behind the selection screen of your three new items selection. 

**Expected behavior**
I expect the view item stats to pop up in the front so i can actually see what I'm choosing. 

**Screenshots**
![Screenshot_20210308-183343_9737de6f3e36012ce6703231c8d3c3a2](https://user-images.githubusercontent.com/80279903/110360117-97eab080-803e-11eb-850e-30e472b78f04.jpg)

**Browser**
One Plus N-100 Nordic (720p) Android

**Console output**
No idea how to do that.

**Are you using any scripts?**
I am not.

**Comment by coolrox95** [comment] 2021-08-15 06:21
Duplicate of #731

**Closed by coolrox95** 2021-08-15 06:21 UTC
Labels: Duplicate
