### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Critical882** [MelvorIdle/melvoridle.github.io#3061] opened 2022-12-03 20:13 UTC
### Describe the bug

Using mining gloves on a gem vein will us charges without providing any benefit

### Reproduction Steps

1. Equip mining gloves
2. Mine a gem vein (I used onyx) 
3. watch as charges get used

### Expected behaviour

mining glove charges shouldn't be used
or gems should be doubled (most likely the former)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-12-21 14:23
Duplicate of #2993

**Closed by coolrox95** 2022-12-21 14:23 UTC
Labels: bug
