### ISSUE TITLE
[Bug]: <Melvor Idle Game Load Failure>

### ISSUE THREAD

**Issue by Hydro117** [MelvorIdle/melvoridle.github.io#2279] opened 2022-03-02 23:25 UTC
### Describe the bug

When attempting to load back into my local save it said that the "game is broken." I have attempted to load both the cloud save and the local save with the same messages. The phone and app is up to date and I am afraid to delete the app and lose all of my progress.

### Reproduction Steps

1. Open the application on iOS
2. Recieve 
![image](https://user-images.githubusercontent.com/100810053/156466397-4505628e-147d-4666-a965-1fb09a434db6.png)

### Expected behaviour

I expected the game to load like every other time with my current character and stats.

### Screenshots

![IMG_3502](https://user-images.githubusercontent.com/100810053/156466464-d649e250-c182-4f2e-a2e2-1dd65120ad16.png)

### Console output

getRecipeCosts@https://ios.melvoridle.com/assets/js/built/fletching.js?1806:13:239
getRecipeIngredients@https://ios.melvoridle.com/assets/js/built/recipeSelection.js?1806:27:66
https://ios.melvoridle.com/assets/js/built/recipeSelection.js?1806:6:193
forEach@[native code]
updateRecipeTooltips@https://ios.melvoridle.com/assets/js/built/recipeSelection.js?1806:6:44
https://ios.melvoridle.com/assets/js/built/artisanSkill.js?1806:39:95
forEach@[native code]
renderSelectionTabs@https://ios.melvoridle.com/assets/js/built/artisanSkill.js?1806:39:34
render@https://ios.melvoridle.com/assets/js/built/artisanSkill.js?1806:18:150
onLoad@https://ios.melvoridle.com/assets/js/built/artisanSkill.js?1806:14:12
updateWindow@https://ios.melvoridle.com/assets/js/game/main.js?1806:4:870
finaliseLoad@https://ios.melvoridle.com/assets/js/game/main.js?1806:265:13
selectCharacter@https://ios.melvoridle.com/assets/js/game/main.js?1806:256:233
onloadEvent@https://ios.melvoridle.com/assets/js/game/save.js?1806:74:232
https://ios.melvoridle.com/assets/js/game/save.js?1806:79:837
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84826
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2971
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84807
r@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28088
fireWith@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28852
c@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:79495
https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:81938

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

Unknown

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-05 04:53
Duplicate of #2244

**Closed by coolrox95** 2022-03-05 04:53 UTC
Labels: bug, Duplicate
