### ISSUE TITLE
[Bug]: Golbin Raid History replaces most recent raid instead of getting rid of oldest 

### ISSUE THREAD

**Issue by xanderput** [MelvorIdle/melvoridle.github.io#2421] opened 2022-04-22 14:16 UTC
### Describe the bug

When finishing a raid, it is supposed to add that raid to your raid history. It does do this, but once you reach 5 raids in the history, it starts replacing the most recent raid instead of getting rid of the oldest raid.

### Reproduction Steps

1. Have 5 raids in raid history
2. Start a raid and flee/die
3. Notice that the raid that was previously the most recent raid has been replaced instead of simply being pushed down

### Expected behaviour

I'd expect it to delete the oldest raid, and insert the most recent raid at the top.

### Screenshots

Before: 
![image](https://user-images.githubusercontent.com/39944140/164732122-e5a55861-e7f5-4783-8242-d63873bc1496.png)

After: 
![image](https://user-images.githubusercontent.com/39944140/164732258-7e4a608a-c0a3-452c-b53a-1b1237b34f52.png)

Notice that it replaced the most recent 'medium' raid. 

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment] 2022-05-10 00:58
Duplicate of #2378

**Comment by xanderputTM** [comment] 2022-05-10 05:05
> Duplicate of #2378

It's not a duplicate of that issue. This issue is related to GR history, the linked issue is related to the GR shop.

**Comment by xanderput** [comment] 2022-05-10 05:08
> Duplicate of #2378

This isn't a duplicate of that issue.
This issue is related to GR History, the linked issue is about GR shop.

**Comment by MelvorIdle** [comment] 2022-05-10 06:42
Sorry about that! I added the comment to the wrong issue.

**Comment by MelvorIdle** [comment] 2022-10-31 05:40
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.

**Closed by MelvorIdle** 2022-10-31 05:40 UTC
Labels: bug
