### ISSUE TITLE
Gem Gloves didnt get Charges after buying them

### ISSUE THREAD

**Issue by vyrus26** [MelvorIdle/melvoridle.github.io#1339] opened 2021-09-10 11:00 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Shop and buy one Gem Gloves.
2. Click on 'Bank and equip them
3. Click on Mining and Mine some ore, Not Rune essence
4. Gem Gloves is not activated and iam Not Mining gems Out of ores

**Expected behavior**
I bought about five gem Gloves and noticed that my Charges Font Go up. I bought a next one, but The Problem stays The Same 

**Screenshots**
I'll try one later If necessary

**Browser**
On Windows, Brave, Steam too!
Mobile, Android, Brave and Kiwi

**Console output**
Idk how in mobile 

**Are you using any scripts?**
Yes semi, it worked in The beginning The Problem started i think Yesterday

**Comment by TapitLightly** [comment] 2021-09-14 00:46
I have had the same issue. Mobile use only, no scripts. Bought 60 gem gloves with no luck, went back and bought only one but didn't receive charges then either.

**Comment by coolrox95** [comment] 2021-11-02 22:28
Duplicate of #1332

**Closed by coolrox95** 2021-11-02 22:28 UTC
Labels: Duplicate
