### ISSUE TITLE
Items randomly switch tabs

### ISSUE THREAD

**Issue by grayhha** [MelvorIdle/melvoridle.github.io#1417] opened 2021-10-02 13:22 UTC
**_Edited 3rd Oct 2021_**

**Describe the bug**
Certain items won't switch tabs by dragging and dropping. Instead, they'll transfer the last item in the same tab to the target tab.

**To Reproduce**
I have thieving mastery tokens and marksman's sigils in tab 0. I drag and drop one of them onto tab 2 and the token/sigil stays where it is but the last item in the tab disappears into tab 2.

**Expected behavior**
Only the correct item to be transferred

**Screenshots**

**Browser**
Latest version of Chrome

**Console output**
Not sure how to do this

**Are you using any scripts?**
No, everything is vanilla

**Comment by coolrox95** [comment] 2021-10-03 08:01
Duplicate of #1213

**Closed by coolrox95** 2021-10-03 08:01 UTC
Labels: Duplicate
