### ISSUE TITLE
[Bug]: Monkey + Leprechaun synergy wrong?

### ISSUE THREAD

**Issue by 0syrs** [MelvorIdle/melvoridle.github.io#2784] opened 2022-10-24 08:22 UTC
### Describe the bug

I recall the synergy for Leprechaun & monkey to be "Automatically sell common drops for thieving for 150% of their base value". It is now only 15% of their base value. Is this a bug, an intended change, or a Mandela effect of me just misremembering?

### Reproduction Steps

Explained above.

### Expected behaviour

Explained above

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-10-24 18:44
Duplicate of #2680

**Closed by coolrox95** 2022-10-24 18:44 UTC
Labels: bug, Duplicate
