### ISSUE TITLE
[Bug]: Error when returning to the game

### ISSUE THREAD

**Issue by drvic10k** [MelvorIdle/melvoridle.github.io#2140] opened 2022-02-01 14:41 UTC
### Describe the bug

When I opened the game, I received this error

An error occured while processing ticks offline:
Active Skill: COMBAT
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'qty')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'qty')
    at BankHelper.addQuantity (https://android.melvoridle.com/assets/js/built/utils.js?1524:46:119)
    at https://android.melvoridle.com/assets/js/built/utils.js?1524:50:49
    at Array.forEach (<anonymous>)
    at BankHelper.consumeItems (https://android.melvoridle.com/assets/js/built/utils.js?1524:50:27)
    at Player.consumeRunes (https://android.melvoridle.com/assets/js/built/player.js?1524:123:98)
    at Player.attack (https://android.melvoridle.com/assets/js/built/player.js?1524:100:68)
    at Player.act (https://android.melvoridle.com/assets/js/built/character.js?1524:186:69)
    at Timer.tick (https://android.melvoridle.com/assets/js/built/combatManager.js?1524:166:89)
    at Player.tick (https://android.melvoridle.com/assets/js/built/character.js?1524:177:49)
    at Player.tick (https://android.melvoridle.com/assets/js/built/player.js?1524:26:14)
Current Equipment:
Helmet: Fire_Adept_Wizard_Hat
Platebody: Fire_Adept_Wizard_Robes
Platelegs: Fire_Adept_Wizard_Bottoms
Boots: Fire_Adept_Wizard_Boots
Weapon: Fire_Battlestaff
Amulet: Gold_Topaz_Necklace
Ring: Gold_Topaz_Ring
Gloves: Rune_Gloves
Cape: Thievers_Cape
Summon1: Summoning_Familiar_Octopus
Summon2: Summoning_Familiar_Witch

Skill Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: 0
Is Attacking: false
Standard Spell Selected: 7
Ancient Spell Selected -1
Aurora Selected: 5
Curse Selected: 1
Active Prayers:Mystic_Will, 
Equipped Food:
Item: Shark_Perfect, Qty: 159
-- End Player Information --
-- Start of Enemy Information --
Enemy: WetMonster
Next Action: Attack
Next Attack: 0
Is Attacking: false
Standard Spell Selected: -1
Ancient Spell Selected -1
Aurora Selected: -1
Curse Selected: -1
-- End Enemy Information --
Current Area Type: Combat
Current Area ID: 2

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1525

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-07 19:32
Duplicate of #1815

**Closed by coolrox95** 2022-03-07 19:32 UTC
Labels: bug, Duplicate
