### ISSUE TITLE
[Bug]: Clue Chasers Insignia solution not working

### ISSUE THREAD

**Issue by kiko2412** [MelvorIdle/melvoridle.github.io#2709] opened 2022-10-20 13:58 UTC
### Describe the bug

I have collected and placed the items in the correct order and yet the Insignia does not show up in my inventory.

### Reproduction Steps

1. Collect 42 Maple logs, 23 redwood logs, 16 raw swordfish, 15 raw crabs, 8 herrings and 4 burnt cave fish
2. Empty the leftmost bank tab
3. Place the items in the order stated in point 1.

### Expected behaviour

Clue Chasers Insignia should appear in the inventory

### Save Link

https://melvoridle.com/save/JkX87vRk

### Screenshots

![image](https://user-images.githubusercontent.com/116285661/196967521-5f7d6b96-0523-42db-8469-523cabfd89b1.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4500

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-10-21 02:07
Duplicate of #2650

**Closed by coolrox95** 2022-10-21 02:07 UTC
Labels: bug, Duplicate, Reproducible
