### ISSUE TITLE
[Bug]: Account stuck stunned.

### ISSUE THREAD

**Issue by TucCrackers** [MelvorIdle/melvoridle.github.io#3074] opened 2022-12-07 11:36 UTC
### Describe the bug

My account is stuck stunned and has been for hours. I got a error about being unable to calculate offline progress and since then I’m stuck stunned

### Reproduction Steps

Thieving

### Expected behaviour

Become unstunned after the stun timer

### Save Link

https://melvoridle.com/save/3T0Yi0Up

### Screenshots

![20A9D029-5522-41E4-97A7-7DBD7EF60431](https://user-images.githubusercontent.com/29133066/206169475-8572371e-bbd2-417a-903b-ba8ba3ca2dc0.png)
![33BB7E6A-8FB7-48CE-9D54-E23D40E5E3CE](https://user-images.githubusercontent.com/29133066/206169487-1b5edb32-1df1-4368-b881-ab48f87ef753.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

4937

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2023-03-25 22:56
Duplicate of #2912

**Closed by coolrox95** 2023-03-25 22:56 UTC
Labels: bug, Duplicate
