### ISSUE TITLE
Bug when dying in Golbin Raid

### ISSUE THREAD

**Issue by Bassiev** [MelvorIdle/melvoridle.github.io#1521] opened 2021-10-26 19:29 UTC
**Describe the bug*
Error happened multiple times. When I die during golbin raid, this bug/error appears. I was also fighting golbins as background activity.

**Browser**
Latest iOS app on iPhone XS

**output**

An error occured while processing ticks:
Active Skill: COMBAT
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'items[itemID].hasAnimation')
Stack Trace:
getItemMedia@https://ios.melvoridle.com/assets/js/game/main.js?1209:360:57
getGolbinRaidHistory@https://ios.melvoridle.com/assets/js/built/raidManager.js?1209:126:1343
loadGolbinRaidHistory@https://ios.melvoridle.com/assets/js/game/golbinraid.js?1209:2:163
changePage@https://ios.melvoridle.com/assets/js/game/main.js?1209:71:154
stopCombat@https://ios.melvoridle.com/assets/js/built/raidManager.js?1209:23:118
checkDeath@https://ios.melvoridle.com/assets/js/built/baseManager.js?1209:14:31
tick@https://ios.melvoridle.com/assets/js/built/baseManager.js?1209:8:77
tick@https://ios.melvoridle.com/assets/js/built/raidManager.js?1209:12:11
tick@https://ios.melvoridle.com/assets/js/built/game.js?1209:28:75
runTicks@https://ios.melvoridle.com/assets/js/built/game.js?1209:26:100
processTime@https://ios.melvoridle.com/assets/js/built/game.js?1209:25:14
loop@https://ios.melvoridle.com/assets/js/built/game.js?1209:39:60
loop@[native code]

**Are you using any scripts?**
No

**Comment by coolrox95** [comment] 2021-10-30 06:52
Duplicate of #1450

**Closed by coolrox95** 2021-10-30 06:52 UTC
Labels: Duplicate
