### ISSUE TITLE
Into the Mist (ITM) the boss can't attack during phase 1

### ISSUE THREAD

**Issue by abcras** [MelvorIdle/melvoridle.github.io#853] opened 2021-03-17 17:59 UTC
**Describe the bug**
After fighting the phase 1 boss for a bit it gets stuck on the attack animation and won't finish, effectively making the boss trivial.

You can freely hit the boss during this and nothing will change, until the boss is killed and the next phase of the fight begins.

**To Reproduce**
These are the likely steps to reproduce it (I haven't tested this again sry):
Step 1: Equip fighter amulet
Step 2: Hit boss and trigger fighter amulet during Reap and Return attack "animation"
The boss is now stuck in the "animation" forever
Step 3: ...
Step 4: profit

**Expected behavior**

**Screenshots**
![Into the mist fight broke](https://user-images.githubusercontent.com/3748122/111514655-3c14db80-8752-11eb-9b87-d0e752744bba.png)

**Browser**
Chrome Chrome 89
Please tell us what browser you are using and what version.

**Console output**
Don't have it, sry didn't cross my mind I was just happy that I could beat the boss in a timely manner!

**Are you using any scripts?**
No scripts

**Comment by MelvorIdle** [comment] 2021-03-18 00:43
I don't think it's the Fighter Amulet causing this issue, because it's not possible for the Passive of the Amulet to proc on Ahrenia.

It requires you to hit 70% of your Max Hit to activate, but Ahrenia has 40% damage reduction which means you can only hit a maximum of 60% (Unless there is a bunch of hidden modifiers somewhere).

I was able to reproduce this once, but not due to the Fighter Amulet I don't think. No errors showed up in console but I was unable to eat or fight back. Will continue to look into it.

**Comment by coolrox95** [comment] 2021-08-15 06:25
Closing as combat has been rewritten as of v0.21. If issue can be reproduced in the latest version please re-open.

**Closed by coolrox95** 2021-08-15 06:25 UTC
Labels: bug
