### ISSUE TITLE
[Bug]: Offline progression bug with new in-game afk progression calculator. 

### ISSUE THREAD

**Issue by VioletVi-u** [MelvorIdle/melvoridle.github.io#4436] opened 2024-06-23 14:10 UTC
### Describe the bug

I'll leave the game in say, agility training, save and exit the game, and come back 10 hours later. When I come back and I have to click on my account, it says "training agility for 10 hours" when I open said profile, the new afk system does it's little loading animation, only to think i've been training wood-cutting for the last 10 hours and replace all the afk time I had with something completely unrelated to agility training. I don't understand why this is happening but this has happened multiple times since I've updated the game for the abyssal dlc.

### Expected behaviour

I expected to see all the progress I had made in agility training, not having it be replaced with woodcutting. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-06-24 20:24
Duplicate of #4410

**Closed by coolrox95** 2024-06-24 20:24 UTC
Labels: bug, Duplicate
