### ISSUE TITLE
[Bug]: Can't take any active actions

### ISSUE THREAD

**Issue by H4sh01** [MelvorIdle/melvoridle.github.io#3130] opened 2023-01-01 01:13 UTC
### Describe the bug

Unless I am not seeing something obvious, I believe I can't take any active actions, such as chopping trees, fighting etc. Selling and farming work fine. Tried it on both mobile, web and pc version, same problem.

### Save Link

https://melvoridle.com/save/MtZC7c5U

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by ekuland** [comment] 2023-01-01 02:02
https://melvoridle.com/save/p3EPXGYl

You were supposedly doing herblore, but also had woodcutting trees selected, I cleared what you were doing and made you wc.

**Comment by H4sh01** [comment] 2023-01-01 10:29
Thank you thank you, everything works now. I had to force load the save, it said it had some content from the expansion, which I don't have. Hope I didn't break anything.

**Comment by coolrox95** [comment] 2023-03-25 06:44
Duplicate of #2779

**Closed by coolrox95** 2023-03-25 06:44 UTC
Labels: bug, Duplicate
