### ISSUE TITLE
[Bug]: Consistent Crashing with Repeatability

### ISSUE THREAD

**Issue by SeakersNight** [MelvorIdle/melvoridle.github.io#3421] opened 2023-05-23 22:25 UTC
### Describe the bug

when using the shop tab. Specifically the materials tab of the shop. When using the custom amount over 100,000 pressing enter to confirm 100,000+ the game soft crashes. sends me off the character with a save (luckily) forcing me to re load back into the character. Replicated on all 3 of my active characters.

### Reproduction Steps

1, Go to shop. 2, Go into materials. 3, open custom amount box. 4,enter 100,000+ and press enter. Dont click out of the custom box because the bug wont show

### Expected behaviour

Game will likely force save on current character then return you to the launch menu/character select. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-08-26 13:14
Duplicate of #3383

**Closed by coolrox95** 2023-08-26 13:14 UTC
Labels: bug, Duplicate
