### ISSUE TITLE
Smithing Gloves displaying incorrect Bonus Percentage On Smithing Tab while Worn

### ISSUE THREAD

**Issue by SQiRL** [MelvorIdle/melvoridle.github.io#1356] opened 2021-09-16 14:26 UTC
**Describe the bug**
Smithing Gloves displaying incorrect Bonus Percentage On Smithing Tab while Worn

**To Reproduce**
1. Navigate to Gloves page in the shop. Verify Description states 5k Charges and 60% XP when worn until depleted.
2. Buy Smithing Gloves and Verify they are in the bank.
3. Hover over them and you see that it says 60% XP when worn until depleted.
4. Left click Smithing Gloves and hit Equip Hands.
5. Navigate to Combat Page and verify the Gloves are in fact equipped..  Hover over the gloves and confirm info is the same as above.
6. Navigate to Smithing Page, Look at the top to the Right of the XP bar,  Verify that the Smithing Gloves are shown.
7. Hover over gloves - Gloves now only show 50% Smithing XP.

**Expected behavior**
Upon Hovering, I expected to see the same Percentage of 60% as stated on the store page for the Smithing Gloves.

**Screenshots**
![Smithing_Gloves_Description](https://user-images.githubusercontent.com/12894754/133630026-d3ce87d0-d01e-4df4-a9ef-8e914ebbbd3a.JPG)

**Browser**
Steam Client.

**Console output**
Please open the console by pressing F12 and copy it here.
 - Does not appear to work in steam client.  If there is another way, please let me know.

**Are you using any scripts?**
Scripts Applied via the Melvor Mod Manager
1. Semi
2. Melvor Action Queue
3. ETA
4. Obstacle Filter

**Comment by coolrox95** [comment] 2021-09-29 04:14
Duplicate of #1294

**Closed by coolrox95** 2021-09-29 04:14 UTC
Labels: Duplicate
