### ISSUE TITLE
[Bug]: Significant Lag for Every Action (mobile)

### ISSUE THREAD

**Issue by Bulletphil** [MelvorIdle/melvoridle.github.io#2982] opened 2022-11-16 18:29 UTC
### Describe the bug

Phone: Samsung Galaxy Note S20 Ultra

For at least a week or longer, I have been experiencing significant lag (at least 10 seconds) for pretty much any action I do on the mobile app. It occurs for any page change (e.g. bank to dropdown menu) and also for most actions on a page (e.g. changing to a different fish while fishing, attempting to sell/buy an item). If I don't press any action, the game seems to run fine (e.g. when woodcutting, acquired items will pop up with any apparent lag).

### Reproduction Steps

1. Open mobile app.
2. Lags immediately due to the "while you were gone" page appearing.
3. Pressing nearly anything will instigate lag

### Expected behaviour

May seem obvious but I think I actually have important information to share here. I have taken a long break from playing this game and only just recently restarted. I already owned it but decided to purchase it again through Steam. I started playing again when the DLC came out, and I think I had at least a week without this issue, so something changed since after the DLC.

### Save Link

https://melvoridle.com/save/PCNpdPR3

### Screenshots

![Screenshot_20221116-122708_Melvor Idle](https://user-images.githubusercontent.com/80265675/202263043-a5841ae8-82ec-4483-8a97-c66e6287507b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 22:37
Duplicate of  #2694

**Closed by coolrox95** 2023-03-25 22:37 UTC
Labels: bug, Duplicate
