### ISSUE TITLE
[Bug]: AoD unlocks missing

### ISSUE THREAD

**Issue by Drexen2022** [MelvorIdle/melvoridle.github.io#3680] opened 2023-09-19 01:45 UTC
### Describe the bug

After clearing Golem in AR mode, I only received 3 skill unlocks. This can be confirmed by counting my max skill levels and 2 others double-checked the counting in discord. I have no choices available above the skills on the menu.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/118573277/0829cda9-cd92-4e47-b3c9-f0b07480c048)

### Expected behaviour

Should have 55 unlocks

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7841

### Are you using any mods?

Yes

**Comment by Drexen2022** [comment] 2023-09-19 17:41
The mods I have are not game changing to my knowledge, ETA and combat sim etc.

**Comment by MelvorIdle** [comment] 2023-09-21 01:15
I cna't seen to reproduce this bug. Do you have any further information? Here is what I see:

Showing no cape equipped: https://i.golb.ink/u/nFT7K2.png
Showing interval with no cape: https://i.golb.ink/u/jZNPoY.png

Showing 99 cape is now equipped: https://i.golb.ink/u/Mi0bK9.png
Showing reduced interval from the cape is working as intended: https://i.golb.ink/u/MOblam.png

**Comment by MelvorIdle** [comment] 2023-10-02 03:50
This should now be fixed as of Game Update - v1.2.1

**Closed by MelvorIdle** 2023-10-02 03:50 UTC
Labels: bug, In Progress
