### ISSUE TITLE
[Bug]: Mining Rune essence consumes mining glove charges but doesn't double

### ISSUE THREAD

**Issue by Dr34mR** [MelvorIdle/melvoridle.github.io#3027] opened 2022-11-24 00:16 UTC
### Describe the bug

When having mining gloves equipped with charges and mining rune essence, charges decrease, however rune essence is not doubled.

Removing the mining gloves provides the same rune essence per hit confirming that the x2 mining glove perk isn't applied

Bug applies to multiple browsers (brave + chrome + edge) with 0 extensions enabled
Also reproducible on mobile

### Reproduction Steps

Go to Mining
Mine rune essence and watch return (x2 runes or x4 runes as part of standard doubling)
Equip Mining Gloves with Charges
Rune essence returns remain at x2 runes and x4 runes and mining glove charges decrease

### Expected behaviour

Either mining gloves should double rune output (as charges decrease) or charges should not decrease like gem gloves when mining base rune essence.

### Save Link

https://melvoridle.com/save/aOt1zmin

### Screenshots

N/A - I can provide a screenshot if you would like

### Console output

style.css?2:1          Failed to load resource: the server responded with a status of 404 ()
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
5[DOM] Input elements should have autocomplete attributes <attribute>: (More info: <URL>) 
cloudManager.js?4908:199 Silent Sign in with JWT
cloudManager.js?4908:199 Validating Melvor Cloud token
cloudManager.js?4908:199 Storing Melvor Cloud Token
cloudManager.js?4908:199 Initializing PlayFab login. Method: customID
cloudManager.js?4908:199 Logging in with Custom ID via PlayFab
cloudManager.js?4908:199 Login with custom ID success
cloudManager.js?4908:199 Getting account info
cloudManager.js?4908:199 Account info retrieved
cloudManager.js?4908:199 Authenticated w/ Melvor Cloud: true
cloudManager.js?4908:199 Authenticated w/ PlayFab: true
cloudManager.js?4908:199 Checking for valid full version
cloudManager.js?4908:199 Checking for valid TotH purchase
cloudManager.js?4908:199 Loading Game Data...
save.js?4908:111 Registered Demo Data.
save.js?4908:111 Registered Full Version Data.
save.js?4908:111 Registered Throne of the Herald Data.
cloudManager.js?4908:199 Initializing Mod Manager...
cloud.js?4908:147 PlayFab Data Stored successfully.
cloudManager.js?4908:199 Checking for Mod Updates...
cloudManager.js?4908:199 Loading Mods...
cloudManager.js?4908:199 Loading Mods (1/2): Bank Tab Values (v1.1.0.4395)
cloudManager.js?4908:199 Loading Mods (2/2): ETA (v1.0.0-52)
cloudManager.js?4908:199 Loading Local Saves...
cloudManager.js?4908:199 Loading Cloud Saves...
cloudManager.js?4908:199 Getting saves from playfab
cloudManager.js?4908:199 Saves retrieved
characterSelect.js?4908:5 Loading character selection
cloudManager.js?4908:293 Connected to PlayFab successfully
save.js?4908:39 Copied to clipboard successfully.
main.js?4908:15 Game Loaded
7633c881-d4df-412b-88ea-f84c7c8fd1d7:587 ETA : Loading...
7633c881-d4df-412b-88ea-f84c7c8fd1d7:587 ETA : added settings menu!
7633c881-d4df-412b-88ea-f84c7c8fd1d7:587 ETA : Loaded!
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
t.announcekit.app/collect/client:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
t.announcekit.app/collect/client:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?4908:29 Synchronising with Cloud
onloadwff.js:71 [Violation] 'setTimeout' handler took 80ms
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
onloadwff.js:71 [Violation] 'setTimeout' handler took 52ms

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

4908

### Are you using any mods?

No

**Comment by MiccWan** [comment] 2022-12-18 15:09
+1

**Comment by coolrox95** [comment] 2022-12-21 00:47
Duplicate of #2993

**Closed by coolrox95** 2022-12-21 00:47 UTC
Labels: bug, Duplicate
