### ISSUE TITLE
[Bug]: Farming unlock popup appears at game launch on Adventure Mode when tutorial crops are ready

### ISSUE THREAD

**Issue by danielreay** [MelvorIdle/melvoridle.github.io#3203] opened 2023-02-03 13:17 UTC
### Describe the bug

If you choose to plant the potato seeds in the tutorial on Adventure Mode, when they're ready (not sure if they died or not) there are a few issues:

1. The green square that flashes around the Farming skill when a crop is ready appears despite the skill being locked
2. The "Skill locked" popup box appears automatically when loading into the game (true for Android app and web browser, not tested on Steam or iOS)
3. Possibly unrelated, but when this happens the open page on launch is defaulting to Woodcutting (also locked) despite having chosen Active Skill

Thanks!

### Reproduction Steps

1. Start Adventure Mode and plant the potato seeds in the tutorial
2. Play until they grow (unsure whether they have to be successful)
3. Exit and reload the game, choose Adventure Mode character

### Expected behaviour

The flashing green square indicator might be expected behaviour, I'm unsure if that's a style choice - however I would not expect the "Skill locked" popup or the Woodcutting skill tab to appear.

### Save Link

https://melvoridle.com/save/6LZbWKwU

### Screenshots

![Screenshot_20230204-001401](https://user-images.githubusercontent.com/9005597/216612685-95619288-33e4-4eeb-b1df-3e876b787e2b.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 06:43
Duplicate of #3102

**Closed by coolrox95** 2023-03-25 06:43 UTC
Labels: bug, Duplicate
