### ISSUE TITLE
Mining gloves no charges

### ISSUE THREAD

**Issue by Legendary233** [MelvorIdle/melvoridle.github.io#1543] opened 2021-11-01 06:27 UTC
**Describe the bug**

I had purchased 40k charges as I'm mining mitheil until 99 I logged back into the mobile app to see I had zero charges left which is incorrectly stated. 

PS. Will these points be refused? 500k per 500 charges.

**To Reproduce**
1. Go to '..store purchase gloves.'
2. Click on '.exit the game ...'
3. Scroll down to '..not needed ..'
4. See error 0 charge suddenly

**Expected behavior**
To have my 40,000 charges 

**Screenshots**

Unavailable

**Browser**
Please tell us what browser you are using and what version.

Mobile app

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

None

**Comment by Legendary233** [comment] 2021-11-01 06:27
In game user "legend"

**Comment by coolrox95** [comment] 2021-11-02 22:30
Duplicate of #1332

**Closed by coolrox95** 2021-11-02 22:30 UTC
Labels: Duplicate
