### ISSUE TITLE
Agility 99 Item Masteries appearing to be broken

### ISSUE THREAD

**Issue by MonkeyMan1242** [MelvorIdle/melvoridle.github.io#1243] opened 2021-08-18 17:50 UTC
![99 agility masteries](https://user-images.githubusercontent.com/89157021/129947344-27f4a887-166d-42b0-9fcd-1d14a8f6ba1d.PNG)

**Comment by coolrox95** [comment] 2021-08-20 09:14
Duplicate of #1240

**Closed by coolrox95** 2021-08-20 09:14 UTC
Labels: Duplicate
