### ISSUE TITLE
[Bug]: Missing info page for Astrology

### ISSUE THREAD

**Issue by ChazTech3030** [MelvorIdle/melvoridle.github.io#1973] opened 2021-12-24 18:05 UTC
### Describe the bug

Every skill has an information page when clicking the skill icon in the top left corner of that skill's screen. Astrology has the button but it doesn't open anything.
![image](https://user-images.githubusercontent.com/45007570/147368134-890a0cf2-51b1-49c9-8683-612c1ac69cb3.png)

### Screenshots

![image](https://user-images.githubusercontent.com/45007570/147368130-89cae6cb-e0b0-47dc-afe8-9d09228654cb.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment] 2022-03-06 19:57
Duplicate of #1605

**Closed by coolrox95** 2022-03-06 19:57 UTC
Labels: bug, Duplicate
