### ISSUE TITLE
Unable to keep local saves

### ISSUE THREAD

**Issue by Zaparaa** [MelvorIdle/melvoridle.github.io#919] opened 2021-04-04 16:38 UTC
**Describe the bug**
Everytime I close my chrome my local save is deleted.

**To Reproduce**
Not sure this is possible as it's dependent on my chrome/pc.

**Expected behavior**
It's supposed to save the game locally when I close and reopen chrome.

**Browser**
Chrome Version 89.0.4389.114 (official version) (64-bit) 

**Console output**
Failed to load resource: the server responded with a status of 403 ()
cloud.js?832:76 Connected to PlayFab successfully
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
No scripts, also disabled all chrome extentions. 

I've tried to check the "clearing cookies on exit" in chrome and it was turned off. Furthermore I've whitelisted melvor idle in the cookies section.

**Comment by MelvorIdle** [comment] 2021-05-25 03:03
This seems to be an external issue unrelated to the game. Something on your device is clearing data when closing the browser/game. The game never performs a delete action unless the specific button is pressed and confirmed.

**Closed by MelvorIdle** 2021-05-25 03:03 UTC
Labels: bug
