### ISSUE TITLE
Buried magic bones are not giving prayer points

### ISSUE THREAD

**Issue by Meegin** [MelvorIdle/melvoridle.github.io#1355] opened 2021-09-16 06:30 UTC
Buried magic bones are not giving prayer points. Mine are stuck at 169(lol),247. I've buried about 10,000 bones with no increase. I expected to get 10 prayer points each but now I see my current 5 are worth 0 each totaling 50...

**Browser**
Chrome vs.93.0.4577.82

**Console output**
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by coolrox95** [comment] 2021-09-29 04:15
Duplicate of  #1326

**Closed by coolrox95** 2021-09-29 04:15 UTC
Labels: Duplicate
