### ISSUE TITLE
[Bug]: Android loading fail (render error)

### ISSUE THREAD

**Issue by NemyTR** [MelvorIdle/melvoridle.github.io#3390] opened 2023-04-28 22:42 UTC
### Describe the bug

An error occurred while rendering:
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'bar')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'bar')
    at MultiProgressBar.animateFromTimer (https://android.melvoridle.com/adfree/assets/js/built/agilityMenus.js?5911:58:112)
    at Agility.renderProgressBar (https://android.melvoridle.com/adfree/assets/js/built/agility.js?5911:165:158)
    at Agility.render (https://android.melvoridle.com/adfree/assets/js/built/agility.js?5911:135:144)
    at https://android.melvoridle.com/adfree/assets/js/built/game.js?5911:181:63
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://android.melvoridle.com/adfree/assets/js/built/namespaceRegistry.js?5911:37:44)
    at Game.render (https://android.melvoridle.com/adfree/assets/js/built/game.js?5911:181:39)
    at Game.loop (https://android.melvoridle.com/adfree/assets/js/built/game.js?5911:197:35)

Active Action: melvorD:Agility
Current Equipment:
Helmet: melvorF:Skillers_Hat
Platebody: melvorF:Skillers_Body
Platelegs: melvorF:Skillers_Leggings
Boots: melvorF:Skillers_Boots
Shield: melvorF:Fine_Coinpurse
Amulet: melvorF:Jeweled_Necklace
Ring: melvorF:Ring_Of_Wealth
Gloves: melvorF:Bobs_Gloves
Cape: melvorF:Cape_of_Completion
Passive: melvorD:Aorpheats_Signet_Ring
Summon1: melvorTotH:Summoning_Familiar_Owl
Summon2: melvorTotH:Summoning_Familiar_Eagle

Action Information:
Is Active: true

Active Obstacle Tier: 14
Built Obstacles (tier|obstacleID):
1:melvorF:BalanceBeam
2:melvorF:BalanceSeesaw
3:melvorF:GapJump
4:melvorF:MountainClimb
5:melvorF:TreeBalance
6:melvorF:HeatTrap
7:melvorF:SpikeJump
8:melvorF:IceJump
9:melvorF:BoulderMove
10:melvorTotH:ForestMaze
11:melvorTotH:RuneCrawl
13:melvorTotH:ForestClimb
14:melvorTotH:LavaTrail
12:melvorTotH:BalanceTrap
0:melvorF:CargoNet
Modding Enabled. Loaded mods:
Dev

### Reproduction Steps

Error message upon login, can't do anything

### Expected behaviour

Play the game

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by NemyTR** [comment] 2023-05-02 05:53
I did reset skill levels to 99 before, but had all the agility obstacles built. After getting to 118 again (the game froze only when finishing a course), the bug is gone.

**Comment by coolrox95** [comment] 2023-08-26 08:35
Duplicate of #3111

**Closed by coolrox95** 2023-08-26 08:35 UTC
Labels: bug, Duplicate
