### ISSUE TITLE
[Bug]: stuck at no plant no harvest case

### ISSUE THREAD

**Issue by menghuan007** [MelvorIdle/melvoridle.github.io#2724] opened 2022-10-20 23:59 UTC
### Describe the bug

I cannot harvest nor plant my trees

### Reproduction Steps

Seems like system once think I am demo user, then it happens

### Screenshots

![9D446C05-2F2F-45B1-8472-D4C244FF6586](https://user-images.githubusercontent.com/8843145/197080892-b43cf95b-2e9b-44d6-a52e-eab1a39554ee.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-10-21 04:51
Duplicate of #2693

**Closed by coolrox95** 2022-10-21 04:51 UTC
Labels: bug, Duplicate
