### ISSUE TITLE
[Bug]: Game Crashing while using Cartography

### ISSUE THREAD

**Issue by snuffyboots** [MelvorIdle/melvoridle.github.io#4579] opened 2024-08-16 21:02 UTC
### Describe the bug

I am receiving an error message when I try to use the Cartography skill.  This crashes my game.  It has happened multiple times over the last 24 hours.  I have tried to remove certain mods and test again but I keep getting this error message.  

An error occurred while rendering:
Error Name: Error
Error Message: Tried to update discovery modal, but costs are not in DOM.
Stack Trace:
Error: Tried to update discovery modal, but costs are not in DOM.
    at Cartography.updateDiscoveryModal (https://steam.melvoridle.com/assets/js/built/cartography.js?11743:404:7)
    at Cartography.renderPOIDiscoveryOptions (https://steam.melvoridle.com/assets/js/built/cartography.js?11743:126:6)
    at Cartography.render (https://steam.melvoridle.com/assets/js/built/cartography.js?11743:45:543)
    at https://steam.melvoridle.com/assets/js/built/game.js?11743:308:63
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?11743:50:44)
    at Game.render (https://steam.melvoridle.com/assets/js/built/game.js?11743:308:39)
    at Game.loopOnline (https://steam.melvoridle.com/assets/js/built/game.js?11743:355:35)
    at Game.loop (https://steam.melvoridle.com/assets/js/built/game.js?11743:342:31)

Active Action: multitasking:multitasking
Current Equipment:
melvorD:Boots: melvorF:Boots_Of_Stealth
melvorD:Amulet: melvorF:Jeweled_Necklace

Action Information:
undefined
Modding Enabled. Loaded mods:
SEMI Core
SEMI Auto Master
SEMI Auto Loot
SEMI Auto Farming
SEMI Auto Slayer
Multitasking
QuickShards
Shop Item Owned Indicator
Time Skip
[Myth] Music
Unlimited Offline
SEMI Drop Chances
Item Uses
Add Items
Upgrade All Potions
SEMI Auto Collect Stockpiles
Ancient Relics Doubling and Preservation Enabled

### Reproduction Steps

1. Train in Cartography.  After a while, this message will appear.

### Screenshots

![image](https://github.com/user-attachments/assets/c2575cdc-d429-4ca9-b8a6-154bc47f671a)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11743

### Are you using any mods?

Yes

**Comment by Flurryous** [comment] 2024-08-17 23:18
If your backup/cloud save is up-to-date, try clearing cache? If on steam you can use the "Reset Client" button below the logout button at the character select screen.

**Comment by coolrox95** [comment] 2024-08-21 03:22
Duplicate of  #4581

**Closed by coolrox95** 2024-08-21 03:22 UTC
Labels: bug, Duplicate

**Comment by DBLeJeune** [comment] 2024-08-25 17:54
I just made a post yesterday about this same issue. I can't load Cartography skill. Hopefully we get a solution soon.
