### ISSUE TITLE
[Bug]: <Rune fishing rod>

### ISSUE THREAD

**Issue by lekingboo** [MelvorIdle/melvoridle.github.io#3226] opened 2023-02-24 00:37 UTC
### Describe the bug

So im kind of a new player, but Ive seen on the wiki that the rune fishind rod is suppose to give -30% fishing interval, but when I bought it it stayed at -25% even if the name of the current rod changed.

### Expected behaviour

Supposed to be at -30% for fishing interval, and -20% for woodcutting and same with mining, its always one under.

### Save Link

https://melvoridle.com/save/Ke3lM3bc

### Screenshots

![efefe](https://user-images.githubusercontent.com/126212255/221062632-46522d8f-c741-43a1-a2d5-f6d1e24136c9.PNG)
![gggggfd](https://user-images.githubusercontent.com/126212255/221062633-669b77b1-84e6-4eb4-8867-bfe1ff20ad80.PNG)
![ggeeee](https://user-images.githubusercontent.com/126212255/221062634-c1094624-8dad-4ade-bae2-9764eb8f147c.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 09:16
Duplicate of #3034

**Closed by coolrox95** 2023-03-25 09:16 UTC
Labels: bug, Duplicate
