### ISSUE TITLE
barbarian gloves destroyed after equip iron gloves

### ISSUE THREAD

**Issue by joseanjim** [MelvorIdle/melvoridle.github.io#1041] opened 2021-06-16 01:07 UTC
I had the barbarian gloves equipped and I equipped some iron gloves, instead of the barbarian gloves going to the bank, they were destroyed ... V0.20 Steam
edit: it was not a bug but a visual glitch, the gloves went to an apparently empty tab

**Comment by coolrox95** [comment] 2021-09-05 01:21
Duplicate of #502

**Closed by coolrox95** 2021-09-05 01:21 UTC
Labels: Duplicate
