### ISSUE TITLE
[Bug]: Mobile Custom Amount Log Off

### ISSUE THREAD

**Issue by Googlesomething** [MelvorIdle/melvoridle.github.io#3412] opened 2023-05-15 19:00 UTC
### Describe the bug

On mobile, when entering a custom amount into the field for buying more items, then hitting enter, it reloads the entire app and pushes you to the character selection screen 

### Reproduction Steps

1. Be on Android Mobile
2. Go to cooking 
3. Select to buy more ingredients from the cooking menu
4. Choose a custom amount and change the field to 10000
5. Press enter
6. Watch as the app seems to crash and you are taken back to character select screen.

### Expected behaviour

Custom input should be taken without being forced to select your character .

### Screenshots

![Screenshot_20230515-125917](https://github.com/MelvorIdle/melvoridle.github.io/assets/44200472/c4334d09-4a9b-4da5-9240-c53caccbe7f6)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

Yes

**Comment by Sammehbrah** [comment] 2023-05-25 02:07
Same as above.
Pressing enter in custom amount box closes to character selection

**Comment by coolrox95** [comment] 2023-08-26 13:04
Duplicate of #3383

**Closed by coolrox95** 2023-08-26 13:04 UTC
Labels: bug, Duplicate
