### ISSUE TITLE
township Items are affected by store modifiers (ex. buy x100)

### ISSUE THREAD

**Issue by KingBagool** [MelvorIdle/melvoridle.github.io#3024] opened 2022-11-23 10:24 UTC
### Describe the bug

when the store modifier for buying multiple items is more than 1, township Items increase in price even though you don't get more than 1 of the item

### Reproduction Steps

1. go to the shop.
2. select a buy modifier (x10,x100,x1000).
3. go the township tab in the shop.
4. township items now have increased cost.

### Expected behaviour

either to have township items not increase in price OR to buy multiple of the item (preferably the first option)

### Save Link

https://melvoridle.com/save/souHS2D9

### Screenshots

before:
shop modifier at 1
![image](https://user-images.githubusercontent.com/118892777/203522886-e4339ff8-beb9-4fdf-9276-68300684ee0e.png)

township items normal cost
![image](https://user-images.githubusercontent.com/118892777/203522928-f00bda8a-e096-42ba-a91c-7bb4cdc1baae.png)

after:
shop modifier 10
![image](https://user-images.githubusercontent.com/118892777/203522958-f7f7d286-b5c2-4472-acd4-faa42a90c84c.png)

township items 10x cost
![image](https://user-images.githubusercontent.com/118892777/203523187-ad2629ba-d16d-42b9-bdd8-043da6eae9f8.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-12-21 00:46
Duplicate of #2903

**Closed by coolrox95** 2022-12-21 00:46 UTC
Labels: bug, Duplicate
