### ISSUE TITLE
Dragonite Ore Depleated

### ISSUE THREAD

**Issue by illusorum** [MelvorIdle/melvoridle.github.io#1157] opened 2021-07-31 20:28 UTC
**Describe the bug**
My dragonite ore vein's been depleted for multiple days now with no signs of recovering.

**To Reproduce**
I'm unsure as to what exactly might have caused this. Maybe some quick going in and out of the app or some save state error.

**Expected behavior**
I tried mining different ores for a while, then tried doing different activities such as getting logs. However, in the end, all the other things were recovering normally, and the dragonite vein still was depleted.

**Screenshots**

**Browser**
I am using iphone to play the game, so I am unsure.

**Console output**
Again, I am unsure how to do this on the iphone.

**Are you using any scripts?**
I am not using scripts.

**Comment by coolrox95** [comment] 2021-10-01 01:17
Duplicate of #881

**Closed by coolrox95** 2021-10-01 01:17 UTC
Labels: Duplicate
