### ISSUE TITLE
[Bug]: Astrology Mastery bars not turning green at 99

### ISSUE THREAD

**Issue by JakeSynth** [MelvorIdle/melvoridle.github.io#2044] opened 2022-01-10 19:22 UTC
### Describe the bug

The mastery bars turn green when they reach level 99 on every other skill except Astrology. If you "Study" the 99 Mastery star it will update itself and turn green.

### Reproduction Steps

1. Go to Astrology with a star that has 99 mastery.
2. You should see the mastery bar on that star is blue and not green.
3. "Study" the star and it will update to green.
4. Reload
5. Go back to the Astrology page and all the 99 mastery bars are blue again.
6. cry

### Expected behaviour

Level 99 Mastery bars should be green on load

### Screenshots

[https://i.imgur.com/zef31Cr.png](url)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment] 2022-01-11 01:06
Duplicate of #1754

**Closed by MelvorIdle** 2022-01-11 01:06 UTC
Labels: bug
