### ISSUE TITLE
Left Menu Disappears if used when window is too small

### ISSUE THREAD

**Issue by brandonglee123** [MelvorIdle/melvoridle.github.io#704] opened 2021-02-20 21:59 UTC
**Describe the bug**
When I try to use the left menu to select a skill and my window is not maximized, the left menu will slide away to the left and become unable to be used until I refresh the browser.

**To Reproduce**
1. Resize your browser window to a smaller size.
2. Click on a skill such as woodcutting, farming, etc.
3. Left Menu slides away and is no longer visible or usable.

**Expected behavior**
I would expect the left menu to stay there as usual. I heard that sometimes the menu can disappear into another button on the top left, but I haven't seen anything like that.

**Screenshots**
![Step 1](https://user-images.githubusercontent.com/7371148/108609535-61950c00-7383-11eb-912f-494b822d1735.png)

(as you can see in this 2nd picture, I have clicked on "Fishing". Notice how you can sort of see the sidebar as it slides away.)
![Step 2](https://user-images.githubusercontent.com/7371148/108609537-63f76600-7383-11eb-8355-73d5e3b5b589.png)
![Step 3](https://user-images.githubusercontent.com/7371148/108609543-678aed00-7383-11eb-8717-966f6cfe31c7.png)

**Browser**
I am using Google Chrome version 88.0.4324.182

**Console output**
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
perpetual_haste.svg:1 Failed to load resource: the server responded with a status of 403 ()
save.js?669:9 Loading Save Game...
save.js?669:25 Save Game Loaded...
mastery.js?669:2 Loading Masteries...
main.js?669:6 Game Loaded
cloud.js?669:96 Connected to PlayFab successfully
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
Nope.

**Comment by coolrox95** [comment] 2021-10-01 01:02
Duplicate of #493

**Closed by coolrox95** 2021-10-01 01:02 UTC
Labels: Duplicate
