### ISSUE TITLE
[Bug]: Slayer Coin Notification occurring when untoggled

### ISSUE THREAD

**Issue by tomkrall** [MelvorIdle/melvoridle.github.io#2147] opened 2022-02-02 15:05 UTC
### Describe the bug

While doing Slayer tasks - with "Show Slayer Coin Notifications" turned off, still seeing them pop up in combat.

(I did have SEMI AutoSlayer, but have them disabled and it was the same).

### Reproduction Steps

1. Slayer
2. Kill mobs
3. Settings
4. Untoggle Slayer Coin Notification
5. Go back to Slayer
6. Still seeing coin alerts

### Expected behaviour

Expecting to not see slayer coin notification (similar to not seeing GP notification or Item notification)

### Screenshots

![slayercoins](https://user-images.githubusercontent.com/2437874/152166576-cf337eb9-efce-4a3c-8f92-dc99398d17f9.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

Yes

**Comment by coolrox95** [comment] 2022-02-18 23:37
Duplicate of #2206

**Closed by coolrox95** 2022-02-18 23:37 UTC
Labels: bug, Duplicate
