### ISSUE TITLE
[Bug]: Fire Making Incorrect Mastery XP Display

### ISSUE THREAD

**Issue by JPKluding** [MelvorIdle/melvoridle.github.io#3350] opened 2023-04-15 19:27 UTC
### Describe the bug

Fire Making incorrectly shows bad mastery XP gain as greater than it should be. A separate modifier is seen adjusting amount to what is expected. 

### Reproduction Steps

1. Open firemaking.
2. Check mastery XP gain.

### Expected behaviour

Should display correct base amount without adjustment.

### Save Link - Required if issue occurs with a save

eJzFfAl4VEXyePWbK5lAEg4RBDUiKiCLHIKc0o9AEo5AJCAgR5gkL8mQyUyYmRDCuhJ0PfDAC1Rc1x9e633sqnhrPJf1XFHUXS92ddH1vkXF9d/V9ySDuP/v932/2c9QXa+6qrq6urq6+r1t8mKrE0mAAx8GAML+CzVxzDTWqmTNnMp0JF4bSdYC/g5xm1piXroqUVdVHInVtMQiaa+2qiKZaEqko4k4Z9B7aksyHo3XVxnaRRXgsCcHdX3CuCdrW1Jp8LHnPQy+JJpqYJTgZ+jCqZFkdSQZjcSrSmOJ1V4KAoh1ayNNkXi6qrIm2hRlbCDIsD0NC7empiUZqWmDEMPnzWuJe1XTIvX1XhJyGCLMEZWtCTayXGyXR5pjXtXsRH0KwjjuxV6raOWxVu68SGvV/GSiJQ3deGfWrIzEmtiQu3PuESSuTqUZ93yGCMqHBWhQ9aAQ2RYnIrGquUkPeiCfymhstZfk7Z7IpzyabkhGBUEvhsiXg4ymPY7rjbpUpj0vVsWMAgcgx9JErJa3+tgcEHFgJw6I6yvHrtr9WLv7tGSkPqFRByGfhV40WYv2TjRDf0RUJNKRdKKq0vNqYQAymRtnMy7aB2O7NJJsaRLtQ1i7W3GkujpS7wnMochifqJJsyhCuXMjjcyqnqQ5DFGViZZkK2sJ1EAcQSVrp2sSSSnscMSVsyFFYm1NsusgdIiF0Vgs0WoxPIJhCyrTyUhrtZdMtgnkkdh9tsdmJ90Wk4RHIaFwANN7MCIXMgdPshWhRjoERzZ3TdSIHopao7OYnkejNpXxSLNXVZqMpFICOwz9ghstBb9Cv5AGguE4i8I2zLeP4VOshgwjUKAeQ5QRjERjG71gFJrWkgajGSIwP9EcWQvHWh5QVebFmrw0jLFxlQ1RL1YLY/nqk7gKXNXVido2OK4LOuaxFTHO5iCX5Hg0g8JNTSTSKZiAvSuiSdYtxVZHKl01D5f0RLQrRoI0iyGrPb7UYRLaQLgYYzYZh1icaG6Wa+N4NNf8aJw3puDDqclEfK1wV4qSZ7B21agyuaBdbhK+TARiKiI4jRxwsTArpxCYaagBJ0Eh07nj8eeaa4la6ZUsZkXjHpQiE0RMZX5Xh8MoQ0XV4xnYKMNZY6OeqTorxCzuAommZmYYmG0FAxxTuV7YqMwcHKFa2EKXuehiGqUiYAVa3ESAdDrmRdZ4cAJfMRItY+A8lIDrj8e4Sr7kxfrhiPl2FznFC9Az53uqz4k2iTTiQltT4QWLbDLpgouV4Sq9SEMimfLgJL7VqNYS1vJP9bw6WMp9mQfeZTrwMlZNzbCcx1kBV3GGGNGnp1JevMaDFcgQWVRVRD2IYIvPFDKt5puKfFZV4SXrvJo01HC/iqSiNVUsCDUD7ng9TVvTeRlhik1nNdSZ+Mfb9Xx2vAhbNNG1ayNVlbEoU6nBnh2zmqJd0HztrUTxVvAqbmmuiTR60IgbaVe8Vi9mL0452U324hQOFEep3JqNTI00c3u+DhNo74UNkZgHzTjdPM5WzYu0wSrlwCWROPf1JJJWNkSSjZBS5i1ORqohjZRzEskmttNxT2nRSwt9ezXOW3GD57GJbkVYkMIa5MdWUk0jtGEHsX+nPViLD8oj9dEa+DXGjulNzem2qumrWqLNTV48DSfzgBiN1zKrRJmFfoNtQVSSSNTCKXzCWtl0tJWz4Itb8Tq+QTVEaxq9eFUx7nHtOGUL4rVepBbD6GqvDXOe9eiILEephlP5CmHsalrSaVy/p6GUkmjSa4o0Yvu3uJ5V2nK6WNwJ/uQMHGR5FDMfOJP7OVutnOwsHvnZ0lmNrQ2cQyTZhI2z0folbGZqOOU5PHdIRuq47HOVu9cozHn4HH0vlmABYyNycuujsWi6Dc7nG0pLE9vxkPICbLqpdDIRS9S3wYVi82mNM8Wb4SLWcua3wcVosoqWWhbH6qe11DSyJbRJT6LLQspmNBdvySFXzWOWvgT14tgKZloMPZeCTliw22V8/tYw72WuEG9kCyORhi18fjiN6nY5oqbGIjWNGvU75CSWI9sn4Are5BTI+Pe8A39awraWCFtuV6KHC7a2jv/D93q13CTzrYjUG51EXsWQvaQfy7mswgmHq8FKtFD6NWgNDKYZZNeiAkJFW4HrkK3qbT/4Az6QQTiD0fXIiAfeDPQNYo9i5q7Xg76RbyQCh2a6CaOIyGwy+t6MQ1ADxiHcgsIVwtbqVhwbD6029jbkK9LGDPztOhArK96BGpW3xNJRniHBH7mpW1geOJ3Fx/lRtuPNgD+hkE7IGXAnn1Sx08tIdhefdkxN53hs37wbHX1aNMJ8uxa24WKd11LdBvegFrKjCHf3WqzkdnYfKqKI1A56P98WMaFmmxc8IEKcF4vBg8iyNIbZ3NQEbqzwkBhqNQvDVbhG2gCPUCHsXBZJwyNcm0SzBx1c50QrW3O4AB9FqulNXjLCNszHLL3k5vg4351UfqP28CesIYmN9UkeLxNxNpSnhITatio0PfwZVIYo2tstIXKj/gsqMZuFxAZm1Kc5b74fyk3kGR6mIs3NDegsz1oamQ3quc5Yvps9b1lVZ04vMGTv8giG3raq+QkMujIe/hV9WEQMzfjFTBxnuwOHJLYQPviXQCV00mova4Sc3p2gMzyJecVgZKdXQeeJgu1raMh57DzaVjXLa4O/oZVYVoI7Pfwd+GmChymt1+ug80TtQ28YQjN/b+L6EsjiZCKVqk5gKhiphbeMVtLH32aYPpnW0jvGLvasX+Yze1P6B6rDllkk1ZJkK74B18g/Ge6AzC5qm3qHhyIvlcJz2gwW2ZVvv2t5jJtMMt+Ff/FIHmPdUg1saezGQcrgWMmytjQbELyHSC4VD+ALo+nW6Bp4n3tXpJ4f62Msb4J/o3eVCOdLwQdiSddXCV/+sJOZuUt8hDTT6+vlkD6GjCMgz7k+4VaTYXV+A9MZY9KseLTOg09xqRQzszTBZ+iKpV7cYzllisfCqsrmaDKahs/BOuyYifsCPW8aKisW05eQcX7ksr/qamK1+X+NjxTXmSyvYBbkE5+Cb8A6S3I+33I+cgyZxHuM/2Q++M7Yi89UOtqcgu/tsRj0D2Clmga9VzixqPNIE/8IVtouXeA/aEY2KSzn+glzGnZAqY7GseYD3Wa2sJNtErMXL0kQ5StOtBJHLzA2EfUNaeLj6QbL2iI1MY/4xS7ENgfZMcBjaiRe79VK5ljUCcz2vJoGwus4fD+VzLCOE5JZHMnlIUsmswRLOOGTEk3VUa+MjYvkyZVc3xKLkW4iWYjXRtPzkxF2VPMIVnG6lSQTa724m6xhfkmwjJNbxnbj0igbMMFKjjrZSPGF3KtQPMFiTrdylmNFlDpYzgkKBQhWcgKlDeygR7CA002gWfStZXKwhpNbziKCkNOHc+KuJG2CVZyg0JZg9aa7ULM8wjK6dAPBAk4u74vJN8HiTX5xIl7XkvJqxeGb9Of7gZeW2S8ZwGUkoimNOZhPRE06utqrbGRjJljBCbppNk2N5FBu2XTSi9czeUV8y/Xq8JRFDhNGSjcnovF0imC5Jiimj2CZJliRjLQx9lieCVbGOIxFGR/LlQgWYoIi3SFYgPFjhkOw6hLgCQvBWkt3dsBACgwxXooMFahkpDnuxeYxbZMEiy0FLOTFaxrm1k3zUs2RaJJgrSVcydJjL+2yZU+w3hJmi3Z1IsmOfEmCJZfw3GYvznfJFMGiS3d+GsL9Co83ZATYlUcZMQkWX3qymWvG4MICJDst4COCRRg/RhOC1ZeQTMcI1l98LA8jWHTJYws2yXYWPE0SrLioOhw74xMstVh1OESJMgsbfRqPORXs35FkfBfcKDKhC240mdgFdyyZ1AU3hkzughtLju+CO45M6YIbR2gX3HiClZeCTJ1HkKldkSNJcVfkKDKN+xMLhWK00+3mKFJiN0eTUrt5LCmzm2PIDLs5lsy0m8eRWXZzHJltN8cTLL/kYrYq1JhjN0eRuXZzNKmwm8cSLLb457CtjGCJBf0iWN6SilTjMb9Q1tYnqGDrnO6O3I3BGmDqmjXe794t0v+i56CBRRd2tPFKI01YewgLzPxkC7ZMub6kbxYW4mc0yAUCDmPshwAEIQQ5vPjdTdI5vPR9MJa8A4VcAXwyhte4j+OF7YGcCoPhAbyejfR+rGUftoNXsCfxsvWRvFCNwTzIa9RH8tp0b16QPgxL0AVTeOH5UF5rRu49eZHZxyvLDq8n/5ZXkQmvHHfj5WKHV4gnch0ILwM7vPBLeKHX4ZVdh9dyCS/eEl6tJbxCezgvyjq8CMtvObAEyzYXFgh8Y7HmGuiJpdZgOy+vbuLzNpNXUvtK2xBeTMUtp5DfKAT49BA+SsLvKQi/gSDcooRLIfzag/CSK+F9CS+1El5ZJbyQSnjplPBqKeHFUdFzkoTSMDkEx/tgig96+IH64YAAuAEYEISDg3BoEA4PwmFBmBqA4gBMC8B0P5QEoDQIZUGY4YOZPjgkCLOCMCkPZgehpx/KAzDHB30CMDcMFWGsDfbyw4EBmBeGoiAcGYRKAvMJDGcWCkHfACwIQyAMRwThRAJhAgvDsCgMi8NwkgNLmH84sNQHy3wwMAiDgjAkCMsdqPLBCj/0D0LEB9U5UJMLtbng5UK+A3UhqA/BMSFoyIVCH4wIQTQMK8MwMgSNPoj5YFgQxoRhfBiawhAPQzAMbC93wpBwoNkH/QKwygeDgzA0CEcF4egg+MLQ2w9JBw4KQMoHo0IwOgRjwzAhDOPCcFwY8tjkhCHtQHfmtz44NhdCYcgNQ04YJobl3PqhBaphNS9HodkvkPMHsEb+y37D5H/8XL9do3/mF5SO00ZgLeG1K+VKwJcQOvzJ+D9iwY4F+yzYL+BcxjUnIOCxiA9aNCELzrHgXAsOW3CeBXez4O4WnJ+h52+s4TkgQpSPV9hA/sVS66Sf5E+Nt4sxcVXhDstLfb/ImAHxj4/w4h2/NJmk7bmuM3Xo51hlapfl5/ByIOHlP9StVq9nNQSbxfZfOgSl7an/i/7A4YAF/9/5gxoKEZ5gm6hAPwQ5HgAeM8W0cp25slxLrh7XiyvENeEq5Fty9jEf+53brj/fz3rEfid26prW03MW/vW/EMgOYbx8DLxoDLxa7DBL+HmpGHiRGHhxGKSXbOB/z+Z/z+F/z+V/z+N/N/K/5/O/F/C/F/K/F0lpDlzMy7eH8rIt4WVawkuzhFdkCS/BTuBVV8ILrYTXVwkvqxJeSSW8cEp4pZTw0ijhdVDCi5+EB0XCa5uEFzIJr1oSXqQkvCxJeDGS8NIj4fVGwouLhBcTCS8dEl4uJLxISHhVkPAqIKEDjfHsGUEfcuh9xvp024uazm2pW0UF7KPjNAl3ORfOb1Y86Df3KAY+966/nhCU/elGRcJkPNGmYH7stHQAekuRlkk/+9HwvflB3d+tX79J9aeXaL4B2luz8dENb27BH4gV4aMbFxkZV9ygwCC9WsOOe9I9r2nZMa2Hny7u0PSc1+frt2penxa26/5bQ8f3VnzPaTf9T6swYzI68lM23UEV8wD9uKfR8YXhhu9pn8ySjRD9cIWi99FHhxm+d5aYMT05wsg++zL4mV+4k0459LQiBftcOl43aI0eTx69c5CCA5adgnS6GRs9VeNDdKiRR++8CP7L32P80ot7Kr3wFoHroTH/vk9glmvMibIfXmRy/6Rzte4hOkfDOfQKlZACP4DJn0MLJXS85vl7STmlCwY78hBMr6nW3KZ8ZnFTQrDezn2d1naopwF6gxLGbFandSug0zSHID1ew8Tq62h4ttbqN3LmB2itXM2zOz1S88mjX0ozYdmf7yPWqi7UcKV+ep12kny6QfrzNi3ldMuSBnbco+5Ic+geTXl1T0NpYMcdfYkI43i7IKyk1ek0OwYO0GuXKzjX8sQCaoiCdIKE0FH4PqnnFzkb2LFgP716tYDu1/oMsnoNsnoZOEBvHmD0SbUbHZZqhQpomcTjqUv4px5EJ88x896dFms4z+3XTbBYAdqq2l0InaQpHQ3115SxXYYyx5J1lQypWMUQVmrtUE/zaXW76eVavRT8gOZfY8ZiwQ69WEIPasrqrYbSwA69SMIPGZ7U4kkN5cUSfthQrrAoVxjKJ94RA3jESC+ypBcZyosk3KEpIxbPE9sN5RkSflRTlrUbyjKLskXuUY9pykvfMJQGdtwhb4gKBl5c8Vmw/MH4ZCc/0fATmv9w/ZRYsPGoJ/+/+D+l+V+sd1NiwQ69VwrDeoPwbTt2mX3GsbTqTgdrOI9+eq2A/qxlFVkcDOxQtclt15S9LUpbloIP1ZTLO4x0s17y3JwrBIR3emIVmGTJTpwcC/bTy+Q+jBuAiMNpOeNPa4kpnacQC3bo81UC4m/ncMplWrcQndeu4Bx6y9OGQ4nGOzruPaNkWXOXGU8kIa++CK1uftbwtDOswSuEVZ7VlNd8ZSgN7LhDB8zm0HOaMrnVUBrYoedIVZ7XlFq1fey/L+x3RAo6WPM0e2h37SHoV3uLBHSYppwLhjLHovxcRsLpmnLLHqMn1fzZ/itHd4CmvMrkAHSqpecFuwSEOLGbFOmnufQUnXMHaEd/BQfpQk1TQGdoOHMVzJcQshC+p2Lyao05VmIwnRderRkw733qIDWkzFlQSesOyBYrTta0mTMyRkK4X/383KkI8NJ+KVX++PIvptz5iynd/VKqEeGdd1c73DU3e69REnpV9bKy4IxeFt6hTVRAr+leo/bRa5TVKy17TdO9RpuxWLBDf61PIn76u6UCwoOD8MmxVq+xVq/1eiHl0o16LQRpFVVwgL7wkoIL6PwOAeGtgvDAConBtwB+2e7/d03pUUNpYIdulnCZprxnkKE0sEPf+FhAs7Q+6jyFq0pEXRNRQ9aOkEMv9BueIzXeoQuk9Jmag4kMISue5NDqDsPB7IYOTUo8vvcgZk0nj2x2tsfbda8BVi9vl4AwaRCj1uk2o+xrUc6R0CTIEm+z7u9vwv723KiE3tKUZtSZsfEGOTpM8YXNlW+/rfsaK2XmospK5ZqywZJiYIc+Lqo8/LVeIeUaUQfitySi701nm7436fjsuAdPu5dDu3Rftdv20pitcYE5UGOulxc8uBTFqjE2D9BXj5TDZivlQv0gSFdpnQus/T1zvtokTQV0PQEF6GP64JpLT9YHlaB1viugDbsMZ9PXoREJ4X2asIk5XRILdugDcnXj+8ldY11HWPfKiHXq/LJY9bJ8xk8f22ZkFVm9NkoI00e5giytpliUN//dcHuxol3CPq0D3g7+/JkxouEA3bmjQ8K59IJbFL6AVinGzKonS9b4EhDJ4IzX32KMq3YpXL4FE+sc7dAyCeHJW1i+XEvpbkXmPDdXnumKNKU5M3anU9sNZaFszNeabNFRPZ9u1BND9DkdNXlE5tX4CpM40a/Zqp4Wanii5qlyBrT520OV+IzdxO09SwgI6F5z9FNijdRx+zvKZf30j6Imy9+YErZV9bV39dj3dX65VSSb/MpCjGLDHWbsCq7X+tRS89TAxIIdDTdr6ZWWdAM7rk9CKU25tMNQGtihX3y0gkN99RgfFnVkfr/a+bSSmX/ukWeQEzXlBebskLHu1ByF9XhvqzP6XNluKD+7TcH59EoJLYT9nXE21SrYrLuTtFZ7+lPda0/fFaqXO+eQNRxaoilNxSBkwTn0tr0CwpAqrHRCh8As033N2ZBYsMl5BmnK4/TT7JWugful/FiWw4doyhEWZW+LUp0R/qUp91cd2g2/NB9+D/a3PypKfB3Q6cSzUMMky1M/ff2mDg79G5TN18tNKKLlnqTpQ1SXldl8ddwvoBpNaTKTzCxlTbuAajVlOzWUBnboHRL2NOVsi6eBHXq6hPI1panGEGum2GlL8sTFIDy8pkM9zbdgYsEOvUQG7g80//VWLDWwQy+UML7qJKLQJnVxwPgrGG/AhYVVrt6w3zHGJMTfh+OUM/XTEJ2o4Rx6jVVPsCOk2gs+1LL2Ve1UnPGF0K6nwi13mF4G71BV7MGUet++F9X6G7/108fXKNhnr4IM/q0rBDRC8aeX66f5Gv4E/puZvUGOZaXu9dsiQ2lgxw2qEG9pi2+8do4Gmf6mzuAjtc7rNc98DeOIhT+o6y/8/khY6dQLFH2IFrcrOIfesMJIXG/V2V55XBDFNAezo4XoCRrOofdMNhwWarxDt70joGHQdS1313QY616T+xF++fTzWZbeLliW9c43Cs6lF3UomGXCGi6g1bJ3XHG2vCJAP5qjSHPpVr1/BS07FNCVRVqTjFiqTmf8ldcunD9/RXVjnLWeQbpOr6kC2rxLQPhGUdcouuNxIQBrA53vFPx05wvtSquMuP0bqdXniifVD1kOpulA+omWiF+SiTn6k86EiQU77pCnxLFklaYsB0NpYId+Iy/m+ykp+tT2BXTNUTOyOPqM9JkvYX+xRa2OwZAt2zGUea7TIaChmlKdzTvnRW/LDPYoTWn27szd+V/fCehoTVlkUVo8XSL38d6a8pFLzYiufUKPyO12nlALS59ixnVyzda4gYkFO1SqzF9dz5xTXxdMUuvwN30hRCzYcUu3i3EcpPrq2pFfa2XXwK0ZcfuuVLCfnitFfqMl3v6B6WVgx+2REgdC3MGEx5qKdL6Gv9XSzS1VvgUTC3bo9R0C2qOl11qUtRblI1RA32nKlbsMpYEdevVaAX2vKfd1glDwD5ry/VMMpYEdDe/9xTzxbNT5LjVfw2MhWyR55i4BTfjZp+N+9ulxP/s0T2u1iRqtNslk+scsfc0+/h899n2dEeZJKA37y29X7BJQgeY5T+tDrDyHeYjcDfFFpcx6XUhjlJ/nQud1hOu7c8wP0iUazqXrihQcoDvUAFjMV1VKPIX/JDnlWHUBQq+5w/T0LO72rbyhD1mr0a4w+hWeKH1zMnzrTOudFnNLAXTtVsPB1H1CVsQMZthR8uTfkAgpFEwvkyUAPU+HCj/VBRYc7wqjSbWG2XiLjBRZqeEfqAgpdrXu+XrVCFj1iCA9XY8F6KV6vH4a0X0d2qA1DKm7EPHVC5eiaiv4dIGmBH0bh9wWdRiJrXqMhD6o9Q/QlMbreg3/mkZIMfZnOls58fMlhsOpliaLLU1u3Gs0qVthpEie/BMdaTGtD6H/3K6UDtCL1YtOTPpmXagL0datRsrd+ljgp806LWXWkwyDWop9Rj1XSwzQae1Giql92+dAf8bpzqz/kIL5F0VCiqkcsb2EGin1WmLQivL2CdOx+gI9RefEfvUOB/9MSUgxKytk1aSC1lgIPd+SbqqcQBdpGn9GBVatSowpfG4yauvm7iFgWSOosTaHsOKQcc5ZrOGAlYVkcFD0/CsrMVL7jL15l+FgVj3Q5ZqHPaJgxq2GfXshefLPt7rqaap4AUu37Hp2V3paHOw3WvxWFmLHw2DGHUNUw/ZbfEZKvpKSoY/N4dQOw8GczYCa15n9VAcGcCw+IS2lIMtYCG3ZZTibjNPOkv02twz7W5UgzXOdHkv7+6bXeTmm1+0moNAnE0bKyfqemLhOTAkN0FtvMuNqF9UH/kWdkKI3ODaWFxe0617t9xqJp+kIDPTOd43E+q1Gw7VFRoqs0/GP9br6j7nlyvDzbHdO/OO+rjZfpwbHOJhqXdCC7bcKgTZp3TIilZbSS0mxZidk3dDbby34rVkLZlS0r9BSAtZ7hPoNP/5FYmcvJXQDmF5jNBy01mPIWiNAvRVZx6J48q8cO0vJzAHsWLdZ39f6rdjOtDrLaGXqSsZifbQUM4Mh6x4iaFmPWCf8gHULCPSSXUa6mTszFrxXE+/Bllrc/ny+4ZbSe26QrtE7AtCb7zKcF2uJjhX/Q9a7ID4tsS909begta6Jrs6gdOtVaavamLHes3p1vyxSQtb7scEMK21aajibe31CT99lNLGit5ZyEHT1BLCyWH/G3BVZ0s1cZEZO660CLQVfSAlB5xVqW8mOisbH/BkWtvZZzXkAZFv76l480/5Bay2AlaP6MyxsVVu0lIOzSklQI8XezYssbkYgWHPnzzbjIE7Avqlrmmf38Ys47TZdrI7SxA2371J9LL64/4bciojKmHPctt1/2KX69OilAz7drKN1Ht31meLlo9eqkjHj+47e7gO01Vo3b/VRIsP0Fv3uVjdLD9ujdT/O5zHFEhw3ekSJpPNZdH67E23UnAjdUms9IYQQDSDI/2qo0w/IIfIyhp0rCOhPO7P/gqtHDh85XDlvX/6ZdS7956/OffbZZ58mpEg0y46sq6urJeJLa/rPEf22bNmymZCBovnAD09d/+kNhOBrubmGNX40MhCy/uwvXfh32aYb/zTb4oLvNi9wyQn8fIEDC8Aa+srk3YnxX88kR9LPHoDN4657kxxFX/B3pJ8ofJ0Mpu+1xm/Y0vtbMsT1P//UPTOWufSbXps7/uc+/lItZocyv8drkSvdyvPJsGeffYVwscvptn5Lfjrq/G1QSi8d32dVw90AZe6UXN+Uh26ohVl0xus3rX4j73I4yU2XV51z3LhnmC+0/n79WWTnNsint4UX9j35xmGQcEunP/D9jOVNkHRrLzvlsn8UXO7W/Dj2siXd+fkFjbpQfABKhkKaHA2lZBiUkV/BSWQ4dCPHkBFkJBFzgu9kLHcLn8eNZpkYfguds+G9yJfPnAWV9KFl8QV7nh0E8+m5dx70zplvFcCJdNui8Mv9Zy5lHvvhYS+sXvybR+mLuas71s/hRRk8DMr3JsF/B1OC5dv4Jsh1LvnL42xG9hJuoyra/PqJHy7a+ykspTf2u2ndNfNuhBm0Jqf/0aPbXoSZtO6wB854qqYPLKHpradWbj9iEiyjFROGn3P1+/dBhL58/5ETpl1xJtTSvzcuLrl72LfQQBes3Pbcxh96QCFd+/AhN/fevBQaXefMG/r+pW0E/WxI04otP+nPG7jv+8hoKCTHQiMZQ8wbVWfiOdYdN7ZAeUMuHE+/7v/apTuueRCm0K8eKq7xvTARVtC3vpn5RsGenTCd/vu2Kde/WPYd9HDnvvDSgHNva4Se9IK3n7rr0/lhmEP39n730Zk1t0Iv+uWtB+RXzwLo7fa7yv34s/KN7tg+U5/encSX+Phb4IOE+6zAf47m//FsbQz/b4oBebwbwf/DJI+/n7qUv83DL+Dy+Ss3vC41jr8vw18qPZYXUnnf6fwzfB5EgvzzewFKC8jvPlkO4tziHn3+5coQLlB39Nc3P7n7dx/AXfQfmx9f2OO+I+FeOvqJ0y45/NAo3EeLbz7ron/lPwL30yWFK75eNuVCeJwe/kiocuW7p8MTtHHgpEevux7gSXr43z/5csNOCn+hJzanH/7i3e7wHP26tXbAiwumw/N0TLDbw39qTMMLdNB5t84e/PA6OMAdUTLeiS4fBVPpoFf3vnVPehespmvXPL1u8bUUXqSD3liUGnLnvbBDQ8UaeklDL2top4ZcOujNZ+fO3X4zvEIHvT946pA2Aq/SI8LvnT1l6P3wGi0eUrH2tHcug2m08bRDHx3whwehhK53y1Y9c89CeJMu2LF7+87ISniLbvrorad+uvF6eJ2Wbvd3G9RUBm/T6cPmPHT3nmFQTnff/e8fvut/KvRxJ51y8s4hq+bAge7YP90xbdms8TCXHvWPrye+cU4tVGjoBHrNbW/ecd4pcVigcYs1tIieXQplj9z0Psyj4w565eSrS+pgIZ13wsgbW0sPho/ohF+fsqE4dw+sdPN//0bswXwffEpnrfr+ttWnXw9NdOItRb+dN6Ya4nTozvd/eO7NP7A9SEHjNTSGzvrjk09sOPev8AW99/4He9auPAaidFKvoz7ZtGoj9HUrT388eNSgVvjG7VN4XcGL3d+FPfTK/CU3LvkoDd/R27ZM2Tzz9kPhezrsnObI3qcq4Ad38t+88vCtK2EvHfb8wB0ro3fCWDr81PE7ty9aAhM0NI6OmP3VNY+e/B84jo54d/LqVfRDFv9H5gwesXbdGpZLSchdduy34384g58ycE8YzD87x2T+V5D1t6/vJs9mYeBNd+BfX1FO3gMm000HDnj9j889CL+iD5zpDCsc2AHD6Ude0b9WuGdBPd3Y/bXdb26MQx29bNun109YdxEcQ3+85IEPLztmOQuXL93+RcPVix+CEW6Pfl8cc+eg3fAJ3br0Nffqq1+CkfSDSf37Tr7xFRZMP3p8S93St3rDV3T9oZfeHfrHPTCKXrX+seff/+5B+Jaubb6p9rE94yDsFtw+JbzhznEwmqYH/zSo45LDIc8N9uh1xDPrhrqFzryir9ZgOtuPjHcIDCfQv5b9oypoZEI25MRsyEnZkJOzIY/PhpySDUmzId1syKnC+uY2tLgzYlpnxHTG51vB51v6pEhgSUk2ZGk2ZFk25IxsyJnZkLOyIWcLHeu1juWdEXNYtzzRLY++J471ZG42ZEU25AmCn3nrSfx6gX/n5ZD/B/GpMJnDmttNcy74XwmaZgXAoij4ZnWIJtsNFm0zzRKAxXmmyc59i08yTZYgLbaIZ7Dmj6Y5E+Ck5aY5C8ipZ4Azql00x7PmH01zAmu+Z5oTgZyWa5qTWJOa5mTWXGWax7PmdaY5hTWfMU3Kmv8xTZd/RzwIsv46BQP81rhov5Tn/SKqjb+ICs/SXb7p70TV6WttfnsS4P+3nwJBOrWdTm1fp7a/U5t/Sm3e3tqXquqHr8oN+cXU/NvsBbqF/18xZTL96vS7IAsOR3PhFAicMoXs88t16/8m5v8BT1qjMA==

### Screenshots

![67698CFE-63C8-4647-8301-32BEFE120666](https://user-images.githubusercontent.com/130575239/232249676-73fa0b93-9347-453c-a2c7-73aeb04e296b.jpeg)
![3B029B8C-9247-4C62-930A-5D2859291F42](https://user-images.githubusercontent.com/130575239/232249677-d982657f-0228-4516-bc66-96bee75ce9df.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5867

### Are you using any mods?

No

**Comment by MelvorIdle** [comment] 2023-04-17 04:10
This seems to be working as intended and is displaying the correct amount.

I've loaded up your save and tested - The amount shown on the icon is the correct amount of MXP that you gain. The tooltip shows you the math to get to the final number. For Maple Logs in your screenshot, it is 93 Base MXP minus 32 MXP from modifiers which equals 61 MXP gained per action.

**Comment by JPKluding** [comment] 2023-04-17 14:58
The issue isn't that I'm not getting the correct amount of XP but that there's no reason for a modifier to show. I have nothing equiped/no reason to get a -15% modifier and the actual base XP I should be receiving is 61 and not 93.

**Comment by MelvorIdle** [comment] 2023-04-18 01:54
Ah okay, thanks so much for the clarification. I can see where the issue lies. This one is only a visualy bug due to an incorrect number used in the visual calculation (the listed mastery XP you gain is correct and accurate).

I'll include a fix fo this in the next Minor Update

**Comment by MelvorIdle** [comment] 2023-04-18 04:36
This should now be fixed as of Minor Update - v1.1.2 (?5890)

**Closed by MelvorIdle** 2023-04-18 04:36 UTC
Labels: bug, In Progress, Visual Bug
