### ISSUE TITLE
[Bug]: things disappear after buying from goblin store

### ISSUE THREAD

**Issue by TimonBiu** [MelvorIdle/melvoridle.github.io#2434] opened 2022-05-05 17:44 UTC
### Describe the bug

after buying something from the goblin store it just disappears after buying from the store, like food or other

### Save Link

https://melvoridle.com/save/l7geW1YD

### Screenshots

(https://imgur.com/a/eiG48i8)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment] 2022-05-12 01:02
Duplicate of #2378

**Closed by MelvorIdle** 2022-05-12 01:02 UTC
Labels: bug
