### ISSUE TITLE
[Bug]: Prayer point display error

### ISSUE THREAD

**Issue by eetazeeba** [MelvorIdle/melvoridle.github.io#1645] opened 2021-11-11 20:45 UTC
### Describe the bug

It is possible to get different prayer point totals displayed on the combat screen and the side bar.

### Reproduction Steps

Unclear. Game mode is Adventure. Origianlly occured burring 1000+ 'holy dust' but have been unable to reproduce with smaller quantities of buried items. Will attempt to rwproduce after restoring more bones

1. Bury bones from bank
2. Observe disparity in PP values
3. Reload of save removed error

### Expected behaviour

Immediate updates keeping correct total displayed on sidebar

### Screenshots

![image](https://user-images.githubusercontent.com/46096410/141365573-e07cc6ab-e9e4-4860-9021-af5111a906ec.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2021-11-11 20:48
Duplicate of #1598
Issue was also hotfixed, hence why you can't reproduce it

**Closed by coolrox95** 2021-11-11 20:48 UTC
Labels: Duplicate
