### ISSUE TITLE
Christmas Cracker ‘Find A Friend’

### ISSUE THREAD

**Issue by sonoflucien** [MelvorIdle/melvoridle.github.io#1461] opened 2021-10-13 17:01 UTC
**Describe the bug**
‘Find a friend’ option for Christmas cracker displays notification for ‘Merchant’s Permit’

**To Reproduce**
1. Go to cracker and select
2. Click on ‘Find A Friend’
3. ???
4. See  merchant’s permit

**Expected behavior**
I thought it gave me party hat

**Screenshots**

**Browser**
Newest chrome and iOS 15.1

**Console output**

**Are you using any scripts?**
Vanilla

**Comment by coolrox95** [comment] 2021-10-15 06:55
Duplicate of #595

**Closed by coolrox95** 2021-10-15 06:55 UTC
Labels: Duplicate
