### ISSUE TITLE
Wasted prayer points

### ISSUE THREAD

**Issue by someoneyouspite** [MelvorIdle/melvoridle.github.io#818] opened 2021-03-12 17:12 UTC
**Describe the bug**
Prayer points are consumed when toggling a prayer off.

**To Reproduce**
1. Initiate a fight with a monster.
2. Turn a prayer on.
3. Turn a prayer off.

**Expected behavior**
Prayer points should only be consumed when damage is dealt/received.
The current behavior results in accidental wasted prayer points.

**Screenshots**
N/A

**Browser**
Chrome

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by swcisel** [comment] 2021-03-12 17:15
This seems to be a duplicate of #801

**Comment by someoneyouspite** [comment] 2021-03-12 18:10
This does seem to be the case, my fault for only searching for duplicates in open issues. Ideally though an issue shouldn't be closed until a fix has been pushed to production and tested.

**Comment by MelvorIdle** [comment] 2021-03-18 02:06
Fixed in upcoming update

**Closed by MelvorIdle** 2021-03-18 02:06 UTC
Labels: bug
