### ISSUE TITLE
[Bug]: <title> cannot sign in game

### ISSUE THREAD

**Issue by Unzart** [MelvorIdle/melvoridle.github.io#4449] opened 2024-06-25 06:42 UTC
### Describe the bug

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/173767435/118ede3c-df45-43fc-93f2-a273beffcc71)

### Reproduction Steps

start game on steam, and just show this 

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/173767435/a80497f1-6f42-4487-a38d-67cc3c117e62)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

NA

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-06-28 02:05
Duplicate of #4457

**Closed by coolrox95** 2024-06-28 02:05 UTC
Labels: bug, Duplicate
