### ISSUE TITLE
[Bug]: missing "%" on main completion log page

### ISSUE THREAD

**Issue by DAFTzippo** [MelvorIdle/melvoridle.github.io#1670] opened 2021-11-12 19:55 UTC
### Describe the bug

Only "Items" has "%" behind the value in the completion log main page.

### Reproduction Steps

1. go to main completion log page
2. look at the top values

### Expected behaviour

every value has a "%" behind it

### Screenshots

![image](https://user-images.githubusercontent.com/51213847/141526444-e4c46293-4854-4be2-a6cc-1935c6e83801.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1285

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment] 2021-11-13 00:28
Duplicate of #1610

**Closed by MelvorIdle** 2021-11-13 00:28 UTC
Labels: bug
