### ISSUE TITLE
[Bug]: Eye of Fear incorrect health

### ISSUE THREAD

**Issue by Legitosity** [MelvorIdle/melvoridle.github.io#2305] opened 2022-03-07 21:13 UTC
### Describe the bug

Eye of Fear has 33,000 health instead of 3,300.

### Reproduction Steps

1. Go to Strange Caves and see Eye of Fear has 3,300 health
2. Fight Eye of Fear
3. Notice it has 33,000 health instead

### Expected behaviour

Expected health value of Eye of Fear: 3,300
Actual health value of Eye of Fear: 33,000

### Screenshots

![eyeoffear](https://user-images.githubusercontent.com/4410015/157118469-c9a897a7-cfca-495f-a16e-240c27799bc2.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1829

### Are you using any scripts or extensions?

Yes

**Comment by Legitosity** [comment] 2022-03-07 21:16
The only script/extension I'm using is visua0's combat simulator v1.6.4-1 pre-release, but I also tried removing it and the bug persisted.

**Comment by coolrox95** [comment] 2022-03-07 23:34
Duplicate of #1750

**Closed by coolrox95** 2022-03-07 23:34 UTC
Labels: bug, Duplicate
