### ISSUE TITLE
[Bug]: <title>nothing works except farming

### ISSUE THREAD

**Issue by Dire-Desire** [MelvorIdle/melvoridle.github.io#3229] opened 2023-02-24 12:48 UTC
### Describe the bug

no action does anything

seems to be posted as bug 3211

### Reproduction Steps

second time this happens . first time it was stuck on runecrafting about 1 week ago. now its stuck on fltching. I was fighting golbins when switched to another app so final actions were not recorded maybe?

### Save Link

https://melvoridle.com/save/0ZtjNQiH

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

5053

### Are you using any mods?

No

**Comment by Dire-Desire** [comment] 2023-02-26 08:52
No Idea how to reproduce it but managed to resolve the issue by: 
log in on PC, confirm nothing works, select another character, see that the game works fine, log back to broken character, still nothing works, try to cancel everything it is doing (in my case fighting, fletching and woodcutting), go back to character selection and log back in to broken character. Now it works fine on PC. Load cloud save from android and all is ok.
It seems the game somehow entered an invalid state of both fighting and fletching simultaneously.

**Comment by coolrox95** [comment] 2023-03-25 09:20
Duplicate of #2779

**Closed by coolrox95** 2023-03-25 09:20 UTC
Labels: Duplicate
