### ISSUE TITLE
Offline Fletching Bug.

### ISSUE THREAD

**Issue by andyycole** [MelvorIdle/melvoridle.github.io#1344] opened 2021-09-11 23:04 UTC
**Describe the bug**
Offline progress stopped working and did not load when I re-tabbed back into the game. Zero actions are taken when offline fletching and the error message does not reappear when minimizing / refocusing the tab.

**To Reproduce**
1. Begin Fletching willow longbow (u)
2. Alt-Tab / Minimize the browser window.
3. Re-open browser window.
4. Offline progress has stopped while minimized, despite having the "Pause actions for skills when the game is minimized or placed in the background to activate offline progression upon return" button enabled.

**Expected behavior**
I expected to alt-tab back into my game and have it load the offline progress.

**Screenshots**
https://i.imgur.com/xu2Xtap.png

**Browser**
Google Chrome - Version 93.0.4577.63 (Official Build) (64-bit)

**Console output**

**Are you using any scripts?**
No scripts are being used. Vanilla gameplay.

**Comment by coolrox95** [comment] 2021-09-13 01:10
Duplicate of #1111

**Closed by coolrox95** 2021-09-13 01:10 UTC
Labels: Duplicate
