### ISSUE TITLE
[Bug]: Buy multiplier is applied to incorrect slayer items

### ISSUE THREAD

**Issue by simondel** [MelvorIdle/melvoridle.github.io#2987] opened 2022-11-17 07:45 UTC
### Describe the bug

The buy multiplier is applied to Slayer items without their title changing. This makes it look as if the item is suddenly a lot more expensive.

### Reproduction Steps

1. To go the Shop
2. Go to the Slayer tab
3. Set the buy multiplier to something like `x1000`
4. Verify the price of Slayer items such as Magical Ring, Slayer armor and Slayer Upgrade Kits

### Expected behaviour

Multiplier should be shown in the title of the item to buy, or the multiplier should not be applied

### Screenshots

![image](https://user-images.githubusercontent.com/4221997/202385911-167f1edb-1392-47fa-8d6e-9876b4672bcf.png)
![image](https://user-images.githubusercontent.com/4221997/202386182-14550efb-ca04-40d6-8f93-836c08c05f56.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4902

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-12-21 00:27
Duplicate of #2903

**Closed by coolrox95** 2022-12-21 00:27 UTC
Labels: bug, Duplicate
