### ISSUE TITLE
[Bug]: Left menu items disseaprance

### ISSUE THREAD

**Issue by Nyman75** [MelvorIdle/melvoridle.github.io#2544] opened 2022-07-24 17:07 UTC
### Describe the bug

Hi,

I've tried to hide the 'Non combat' section from the left menu by clicking on the eye while I didn't have any skill unlocked: the 'Combat' section's items dissappeared and the whole 'Non combat' section dissapeared.

I had to restart to have them available again.

![left menu - before hiding](https://user-images.githubusercontent.com/109916704/180658290-52a1c5dc-e77f-454b-82d5-aa863901d189.jpg)

![left menu - after clicking on the 'non combat' eye](https://user-images.githubusercontent.com/109916704/180658289-e35542c8-6a31-466f-aacb-c5ff2aab17f4.jpg)

### Reproduction Steps

In the left menu, click on the 'Non combat' eye icon while no related skills are unlocked

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2077

### Are you using any scripts or extensions?

No

**Comment by adibarra** [comment] 2022-07-25 07:00
Issue is a duplicate of #2513

**Comment by Liquidasylum** [comment] 2022-08-15 11:13
Had the same happen on the Android V1.0.5 easily reproducible and happens every time you press the "hide" eye next to non combat skills. The combat skills hide works as intended though.

**Comment by MelvorIdle** [comment] 2022-10-19 05:15
Fixed as of v1.1. Please open a new report if issue persists.

**Closed by MelvorIdle** 2022-10-19 05:15 UTC
Labels: bug
