### ISSUE TITLE
[Bug]: An error occurred while rendering

### ISSUE THREAD

**Issue by jvvinicius9** [MelvorIdle/melvoridle.github.io#3258] opened 2023-03-12 22:58 UTC
### Describe the bug

It´s an message that appears every time I access my main save

That's the message:

An error occurred while rendering:
Active Action: undefined
Error Name: Error
Error Message: Tried to get active obstacle, but none is built.
Stack Trace:
Error: Tried to get active obstacle, but none is built.
    at Agility.get activeObstacle [as activeObstacle] (https://steam.melvoridle.com/assets/js/built/agility.js?5064:27:7)
    at Agility.getGPModifier (https://steam.melvoridle.com/assets/js/built/agility.js?5064:52:249)
    at Agility.getObstacleGP (https://steam.melvoridle.com/assets/js/built/agility.js?5064:59:69)
    at Agility.renderCourseRates (https://steam.melvoridle.com/assets/js/built/agility.js?5064:138:358)
    at Agility.render (https://steam.melvoridle.com/assets/js/built/agility.js?5064:136:58)
    at https://steam.melvoridle.com/assets/js/built/game.js?5064:180:63
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?5064:37:44)
    at Game.render (https://steam.melvoridle.com/assets/js/built/game.js?5064:180:39)
    at Game.loop (https://steam.melvoridle.com/assets/js/built/game.js?5064:196:35)
Current Equipment:
Helmet: melvorD:Crown_of_Rhaelyx
Platebody: melvorD:Dragon_Platebody
Platelegs: melvorD:Dragon_Platelegs
Boots: melvorF:Boots_Of_Stealth
Weapon: melvorD:Rune_Sword
Shield: melvorF:Fine_Coinpurse
Amulet: melvorD:Amulet_of_Fishing
Ring: melvorD:Aorpheats_Signet_Ring
Gloves: melvorD:Smithing_Gloves
Cape: melvorD:Smithing_Skillcape
Summon2: melvorF:Summoning_Familiar_Crow
Consumable: melvorF:Fishing_Hook

No Active Action Information

Modding Enabled. Loaded mods:
Dev

### Reproduction Steps

The error appears when I try to play in may main character's save

### Save Link

An error occurred while rendering: Active Action: undefined Error Name: Error Error Message: Tried to get active obstacle, but none is built. Stack Trace: Error: Tried to get active obstacle, but none is built.     at Agility.get activeObstacle [as activeObstacle] (https://steam.melvoridle.com/assets/js/built/agility.js?5064:27:7)     at Agility.getGPModifier (https://steam.melvoridle.com/assets/js/built/agility.js?5064:52:249)     at Agility.getObstacleGP (https://steam.melvoridle.com/assets/js/built/agility.js?5064:59:69)     at Agility.renderCourseRates (https://steam.melvoridle.com/assets/js/built/agility.js?5064:138:358)     at Agility.render (https://steam.melvoridle.com/assets/js/built/agility.js?5064:136:58)     at https://steam.melvoridle.com/assets/js/built/game.js?5064:180:63     at Map.forEach (<anonymous>)     at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?5064:37:44)     at Game.render (https://steam.melvoridle.com/assets/js/built/game.js?5064:180:39)     at Game.loop (https://steam.melvoridle.com/assets/js/built/game.js?5064:196:35) Current Equipment: Helmet: melvorD:Crown_of_Rhaelyx Platebody: melvorD:Dragon_Platebody Platelegs: melvorD:Dragon_Platelegs Boots: melvorF:Boots_Of_Stealth Weapon: melvorD:Rune_Sword Shield: melvorF:Fine_Coinpurse Amulet: melvorD:Amulet_of_Fishing Ring: melvorD:Aorpheats_Signet_Ring Gloves: melvorD:Smithing_Gloves Cape: melvorD:Smithing_Skillcape Summon2: melvorF:Summoning_Familiar_Crow Consumable: melvorF:Fishing_Hook  No Active Action Information  Modding Enabled. Loaded mods: Dev

### Screenshots

![bug](https://user-images.githubusercontent.com/81474419/224578829-7dd3299f-b009-42c4-adb9-361f0d0c6e80.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2023-03-25 06:53
Duplicate of #3190

**Closed by coolrox95** 2023-03-25 06:53 UTC
Labels: bug, Duplicate
