### ISSUE TITLE
Alching 

### ISSUE THREAD

**Issue by Stickeyickey** [MelvorIdle/melvoridle.github.io#1129] opened 2021-07-10 04:23 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. When alching only spirit and nature runes are used. Not sure if it's when the fire rune text is in a certain spot on the page or what but I don't use fire runes when alching

**Screenshots**

**Browser**
Please tell us what browser you are using and what version. Using the phone app On a Google pixel 4

**Console output**
Please open the console by pressing F12 and copy it here. It's on my phone idk how to do that

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred. No scripts 
![Screenshot_20210709-222314](https://user-images.githubusercontent.com/87218161/125151567-4ba2a080-e104-11eb-8584-4f588be94676.png)
![Screenshot_20210709-222316](https://user-images.githubusercontent.com/87218161/125151574-4fcebe00-e104-11eb-8ef8-509982f5212f.png)
![Screenshot_20210709-222314](https://user-images.githubusercontent.com/87218161/125151577-53624500-e104-11eb-8ff3-acaf5b0b5f45.png)

**Comment by Stickeyickey** [comment] 2021-07-10 04:24
Fuck I clicked on. Different screen shots as well. Idk how to post them from my phone

**Comment by Tykothorpe** [comment] 2021-07-18 14:32
Have you got a fire staff equipped? Equipment which gives a fire rune cost reduction would cause this.

**Comment by coolrox95** [comment] 2021-11-04 07:34
Closing as there has been no follow up and I cannot reproduce this issue.

**Closed by coolrox95** 2021-11-04 07:34 UTC
Labels: bug, Cant Reproduce
