### ISSUE TITLE
[Bug]: Cannot equip two summoning marks using the mini bar

### ISSUE THREAD

**Issue by ammesonb** [MelvorIdle/melvoridle.github.io#2365] opened 2022-03-29 16:56 UTC
### Describe the bug

When clicking on summoning marks in the mini bar, it is not possible to equip a second without going through the inventory screen.

### Reproduction Steps

Both ent and octopus are equipped
![image](https://user-images.githubusercontent.com/2522710/160664846-bd7a0f89-c937-41b7-b1f6-c14fccc7d10a.png)
Unequip the octopus mark
![image](https://user-images.githubusercontent.com/2522710/160664982-b6c23494-b7ca-4f07-b46c-2ffe66f7b916.png)
And re-equipping it replaces the left-hand ent slot, instead of filling the empty right-hand slot.
![image](https://user-images.githubusercontent.com/2522710/160665053-38c11391-d516-472c-ad66-5a4eadea44d5.png)

### Expected behaviour

The octopus mark should be equipped to the empty right-hand slot, not replacing the ent on the left

### Save Link

https://melvoridle.com/save/mTYBWfBU

### Screenshots

Included in the steps to reproduce

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1852

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-29 18:55
Duplicate of #2301

**Closed by coolrox95** 2022-03-29 18:55 UTC
Labels: bug, Duplicate
