### ISSUE TITLE
[Bug]: Active Prayers Still Active After Rebalance

### ISSUE THREAD

**Issue by Novalisky** [MelvorIdle/melvoridle.github.io#1745] opened 2021-11-20 04:09 UTC
### Describe the bug

Any prayers that were active before the rebalance are still active after 1.0, even if you no longer have the level to use them. All prayer XP and prayer effects are still active as well. 

### Reproduction Steps

1. Have prayers active prior to the update.
2. Update to 1.0
3. Log in

### Expected behaviour

Prayers you do not have the level for should be turned off.

### Screenshots

https://cdn.discordapp.com/attachments/625840209531240469/911464283307642940/unknown.png

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-07 19:36
Duplicate of #1721

**Closed by coolrox95** 2022-03-07 19:36 UTC
Labels: bug, Duplicate
