### ISSUE TITLE
Divine Potion Charges Being Used On Enemy Attacks

### ISSUE THREAD

**Issue by RMalhotraGit** [MelvorIdle/melvoridle.github.io#258] opened 2020-05-29 03:40 UTC
**Describe the bug**
When using a prayer that only boosts the player's offensive stats, for example, Ultimate Strength, one charge of a divine potion is used when the player attacks and another charge is used when the enemy attacks. 

**To Reproduce**
1. Equip a divine potion and go to combat with any enemy. 
2. Click on an offensive only prayer, such as Ultimate Strength.
3. Notice that a charge is used for both player and enemy attacks. (It is easier to see this if the attack speed of your weapon is different than the enemy's attack speed).

**Expected behavior**
For offensive prayers, a charge of the divine potion should only be used for player attacks, not enemy attacks.

**Screenshots**

**Browser**
Google Chrome (newest version)

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

**Comment by Lohrer** [comment] 2020-07-01 18:50
I can confirm this bug, also I believe it's a duplicate of #250

**Closed** 2020-11-15 06:29 UTC
Labels: bug
