### ISSUE TITLE
[Bug]: Goblin store multiplayer

### ISSUE THREAD

**Issue by Just-a-Cactus** [MelvorIdle/melvoridle.github.io#2926] opened 2022-11-07 03:25 UTC
### Describe the bug

When in standard store you use multiplier (x10, x1000 and any other), it affects to Goblin store, but from Goblin Store you can not change it, or disable! Tried on Steam App (Windows, macOS) and iOS versions.

### Reproduction Steps

1. Go to Store
2. Select any multiplier
3. Go to Goblin Store
4. Saw that multiplier that selected in casual store - works but you no interface to change it

### Expected behaviour

I want to see a dropdown menu with multipliers in Goblin Store

### Screenshots

<img width="1712" alt="Screenshot 2022-11-07 at 05 17 04" src="https://user-images.githubusercontent.com/43491424/200219452-6ebfa309-b138-436c-9ae7-0493a1bacb52.png">
<img width="1712" alt="Screenshot 2022-11-07 at 05 17 33" src="https://user-images.githubusercontent.com/43491424/200219462-fd0e03bf-85be-45fa-886c-bc6a9afba0cb.png">

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-12-20 23:45
Duplicate of #2903

**Closed by coolrox95** 2022-12-20 23:45 UTC
Labels: bug, Duplicate
