### ISSUE TITLE
[Bug]: Some kind of error while thieving and doing the goblin raid

### ISSUE THREAD

**Issue by coolchris366** [MelvorIdle/melvoridle.github.io#1581] opened 2021-11-07 07:41 UTC
### Describe the bug

Some kind of tick processing error

### Reproduction Steps

1. Begin thieving from Bob the Farmer
2. Start goblin raid
3. Die

### Expected behaviour

I expected to continue melvor idle without an error

### Screenshots

![36C84C4B-ABAF-4512-90AD-39755B229971](https://user-images.githubusercontent.com/91033693/140636593-a6416750-5e35-42cb-b44c-afcb4ef9e280.png)

### Console output

An error occured while processing ticks:
Active Skill: THIEVING
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'items[itemID].hasAnimation')
Stack Trace:
getItemMedia@https://ios.melvoridle.com/assets/js/game/main.js?1215:360:57
getGolbinRaidHistory@https://ios.melvoridle.com/assets/js/built/raidManager.js?1215:126:1343
loadGolbinRaidHistory@https://ios.melvoridle.com/assets/js/game/golbinraid.js?1215:2:163
changePage@https://ios.melvoridle.com/assets/js/game/main.js?1215:71:154
stopCombat@https://ios.melvoridle.com/assets/js/built/raidManager.js?1215:23:118
checkDeath@https://ios.melvoridle.com/assets/js/built/baseManager.js?1215:14:31
tick@https://ios.melvoridle.com/assets/js/built/baseManager.js?1215:8:77
tick@https://ios.melvoridle.com/assets/js/built/raidManager.js?1215:12:11
tick@https://ios.melvoridle.com/assets/js/built/game.js?1215:28:75
runTicks@https://ios.melvoridle.com/assets/js/built/game.js?1215:26:100
processTime@https://ios.melvoridle.com/assets/js/built/game.js?1215:25:14
loop@https://ios.melvoridle.com/assets/js/built/game.js?1215:39:60
loop@[native code]

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1215

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2021-11-09 23:39
Duplicate of #1450

**Closed by coolrox95** 2021-11-09 23:39 UTC
Labels: Duplicate
