### ISSUE TITLE
[Bug]: Augite Plateleg color inconsistency

### ISSUE THREAD

**Issue by Portentum-V** [MelvorIdle/melvoridle.github.io#3249] opened 2023-03-04 20:03 UTC
### Describe the bug

(P) Augite Platelegs color matches (I) Augit Platelegs rather then the other Palladium upgraded armors. 

### Expected behaviour

(P) Augite Platelegs should be a pale green like the other (P) items.

### Screenshots

![image](https://user-images.githubusercontent.com/5906393/222926434-4df54118-2fc6-4f18-9aef-e49b53894de3.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2023-03-25 22:50
Duplicate of #2942

**Closed by coolrox95** 2023-03-25 22:50 UTC
Labels: bug, Duplicate
