### ISSUE TITLE
[Bug]: <title>Monster health showing incorrectly 

### ISSUE THREAD

**Issue by ScoopyGitHub** [MelvorIdle/melvoridle.github.io#2057] opened 2022-01-13 01:44 UTC
### Describe the bug

Monster health showing ten times less than what it is in the monster list. Wasn’t happening yesterday. All I’ve done today is log on 

### Screenshots

![62F345DC-5E23-4E92-B6CF-A5D6E2802297](https://user-images.githubusercontent.com/30647286/149250811-d31ceda8-814b-4d2f-8d4d-e12ecc768272.png)
![72F3EB9D-90F5-4B50-AE16-0754D0E7A7D5](https://user-images.githubusercontent.com/30647286/149250816-7a089527-d68a-4873-add1-8e23f0003965.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment] 2022-01-13 02:52
Actually, you're on Hardcore, it's 10x higher than the list.

That's not HP level, that's actual HP.

**Comment by ScoopyGitHub** [comment] 2022-01-13 03:07
![79B54CCF-4BCF-4433-B98D-62051F21642B](https://user-images.githubusercontent.com/30647286/149258751-a6cf73d3-1e22-43dc-8d7d-e33e7f24c008.png)
![6D5C9368-98E8-4F84-AE36-27296ED6E290](https://user-images.githubusercontent.com/30647286/149258756-222799bc-38c4-4425-ac9d-8f7d21a68e95.png)

just started a new character to confirm

**Comment by coolrox95** [comment] 2022-03-09 03:25
Duplicate of  #1750

**Closed by coolrox95** 2022-03-09 03:25 UTC
Labels: bug, Duplicate
