### ISSUE TITLE
Returning from idle error

### ISSUE THREAD

**Issue by iOnyxi** [MelvorIdle/melvoridle.github.io#2283] opened 2022-03-03 15:40 UTC
### Describe the bug

Idle gains did not load.

### Reproduction Steps

1. Returned to game after being idle/away < 1 hr

### Expected behaviour

Load up gains from time idled

### Screenshots

N/A

### Console output

An error occured while processing ticks offline:
Active Skill: COOKING
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'items[itemID].hasAnimation')
Stack Trace:
getItemMedia@https://ios.melvoridle.com/assets/js/game/main.js?1821:282:57
@https://ios.melvoridle.com/assets/js/built/game.js?1821:88:1852
forEach@[native code]
createOfflineModal@https://ios.melvoridle.com/assets/js/built/game.js?1821:88:1702
@https://ios.melvoridle.com/assets/js/built/game.js?1821:70:830
Current Equipment:
Helmet: Dragon_Helmet_T_G
Platebody: Dragon_Platebody_T_G
Platelegs: Dragon_Platelegs_T_G
Boots: Dragon_Boots_T_G
Weapon: Ancient_Claw
Shield: Dragon_Shield_T_G
Amulet: Amulet_of_Torture
Ring: Gold_Sapphire_Ring
Gloves: Paladin_Gloves
Quiver: Iron_Arrows
Cape: Cooking_Skillcape
Summon2: Summoning_Familiar_Pig

Skill Information:
Is Active: true

Selected Cooking Recipes:
Fire: 11
Active Cooking Category: Fire
Passive Cooking Categories: 
Stockpile Contents:

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1821

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-05 03:53
Duplicate of #2242

**Closed by coolrox95** 2022-03-05 03:53 UTC
Labels: bug, Duplicate
