### ISSUE TITLE
[Bug]: android phone - game lag/crashing (accessibility)

### ISSUE THREAD

**Issue by LibertasGaming** [MelvorIdle/melvoridle.github.io#3015] opened 2022-11-21 16:56 UTC
### Describe the bug

Game is constantly showing an error message that game crashed unexpectedly, and I have to override it by selecting "wait" or "send feedback". This only happens in the android app, and my web browser.

Many people have resolved this issue by turning off accessibility apps, but I have to leave one of these apps in order for my phone to work. Unfortunately, i will have to try other solutions.

Is this an issue that is eventually going to be resolved? The game is almost unplayable in this state. 

### Reproduction Steps

This error occurs consistently, and constantly.

### Expected behaviour

Extreme lag, up to 6 seconds of delay between each action, and a crash error notfication

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by Mot92** [comment] 2022-11-22 18:05
#2958

**Comment by coolrox95** [comment] 2023-03-25 04:53
Duplicate of #2694

**Closed by coolrox95** 2023-03-25 04:53 UTC
Labels: bug, Duplicate
