### ISSUE TITLE
Using Plant All feature while farming when patches are full deducts money

### ISSUE THREAD

**Issue by Andronomos** [MelvorIdle/melvoridle.github.io#1081] opened 2021-06-25 05:56 UTC
**Describe the bug**
Not a big deal but when you click the plant all for 5,000 button, select a crop and then click the plant all button it will deduct the money from you even if your patches are currently full.

**To Reproduce**
1. Click on the farming tab
2. Fill up all your patches with a crop
3. Click plant all for 5,000
4. Select a crop
5. Click plant all

**Expected behavior**
It would notify you that you were unable to plant and ignore the action.

**Browser**
Firefox 89.0.2

**Console output**
Nothing is output to the console.

**Are you using any scripts?**
No

**Comment by coolrox95** [comment] 2021-09-05 01:56
Duplicate of #721

**Closed by coolrox95** 2021-09-05 01:56 UTC
Labels: Duplicate
