### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by jonathan-lin** [MelvorIdle/melvoridle.github.io#3099] opened 2022-12-17 13:24 UTC
### Describe the bug

Game locks when I load into character 

### Reproduction Steps

Load save

### Expected behaviour

Play game 

### Save Link

https://melvoridle.com/save/NCDoS92i

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

Unknown

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 07:00
Duplicate of  #3190

**Closed by coolrox95** 2023-03-25 07:00 UTC
Labels: bug, Duplicate
