### ISSUE TITLE
[Bug]: Incorrect (P) Augite Platelegs sprite

### ISSUE THREAD

**Issue by SoffixTiger** [MelvorIdle/melvoridle.github.io#3014] opened 2022-11-21 15:51 UTC
### Describe the bug

(P) Augite Platelegs has the same sprite as (I) Augite Platelegs.

(IE the plated bits are Iridium light gray instead of Palladium off-green)

### Reproduction Steps

![image](https://user-images.githubusercontent.com/90718669/203098819-24a0c3d5-23df-4693-b404-96561ea81389.png)
![image](https://user-images.githubusercontent.com/90718669/203098859-fee03499-af38-438f-8678-c07273a4934e.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 22:50
Duplicate of #2942

**Closed by coolrox95** 2023-03-25 22:50 UTC
Labels: bug, Duplicate
