### ISSUE TITLE
[Bug]: Game will not close on it's own in Steam

### ISSUE THREAD

**Issue by De3xy** [MelvorIdle/melvoridle.github.io#1627] opened 2021-11-11 11:52 UTC
### Describe the bug

The evening before 1.0 public beta patch, I purchased auto slayer, this is when it started happening.
When I close the game (I have the purchased Steam version) it will not close, Steam says the game is still running. The only way to close the game seems to by force exiting Steam and rebooting it. My progress continues to work flawlessly though.
This issue is constant now, no matter what I decide to offline idle.
I also can't reopen the game until I restart Steam.
Also not possible to close the game via keeping the game open and pressing "Stop" within Steam.
This was an issue before the patch, and is still an issue now as well.

### Reproduction Steps

Examples:

Start game
Close game

Start game
Change to different idle skill(s)
Close game

### Expected behaviour

The game to fully close itself (I can see in Steam that it is still running, I can't seem to find it Melvor within Task Manager)

### Screenshots

![image](https://user-images.githubusercontent.com/94115093/141293299-8bae3404-3855-4b13-a41d-7561905b7967.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2021-11-11 20:14
Duplicate of #489

**Closed by coolrox95** 2021-11-11 20:14 UTC
Labels: Duplicate
