### ISSUE TITLE
[Bug]: <title> unable to do anything except farm

### ISSUE THREAD

**Issue by Fatwun** [MelvorIdle/melvoridle.github.io#3211] opened 2023-02-13 23:56 UTC
### Describe the bug

Farming is the only skill that works. Can’t do anything else.

### Save Link

https://melvoridle.com/save/aGvUkD6r

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

5047

### Are you using any mods?

No

**Comment by Silverfyree** [comment] 2023-02-20 11:50
Not sure what you have done but your save is definitely borked somehow. I actually managed to get every skill except for woodcutting to work on your save, but throwing hella errors.
Will need a dev to look further into it.

![image](https://user-images.githubusercontent.com/77082862/220098656-970c3c4f-326a-461f-960f-e45595903c04.png)

**Comment by coolrox95** [comment] 2023-03-25 09:06
Here is a fixed version of your save: https://melvoridle.com/save/NfYkJRny

Regarding the console errors, those are all due to having outdated browser extensions for the game installed.

Issue appears to be a duplicate of #2779 and would be resolved by its fix.

**Closed by coolrox95** 2023-03-25 09:06 UTC
Labels: bug, Duplicate
