### ISSUE TITLE
[Bug]: at 81 astrology stops working

### ISSUE THREAD

**Issue by Odearurded** [MelvorIdle/melvoridle.github.io#3118] opened 2022-12-26 05:26 UTC
### Describe the bug

I just got 80 astrology and when I click study or explore on ANY of the constellations they don't progress or even have the "loading bar" move anymore.  Closed melvor 6 times and restarted my phone and that did not help. My melvor idle is the throne of herald version and has no available updates. 

### Reproduction Steps

Go to 'astrology'

### Expected behaviour

Not sure what this is even...

### Save Link

https://melvoridle.com/save/GGFsPRmX

### Screenshots

![Screenshot_20221225-212305_Melvor Idle](https://user-images.githubusercontent.com/121416367/209506153-1a86ea92-f7ec-4633-acdb-6e8b9fbe4d96.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 07:15
Here is a fixed version of your save: https://melvoridle.com/save/2K167Ulc

Duplicate of #2779

**Closed by coolrox95** 2023-03-25 07:15 UTC
Labels: bug, Duplicate
