### ISSUE TITLE
[Bug]: Can't quick equip capes on mobile

### ISSUE THREAD

**Issue by eliclipso** [MelvorIdle/melvoridle.github.io#3122] opened 2022-12-28 20:06 UTC
### Describe the bug

Because the cape's stats covers the quick equip menu, I can't quick equip capes.

### Reproduction Steps

iPhone 8
1. Wear a cape
2. Open the equipment menu of the combat tab
3. Tap the cape, which will result in both the stats of the cape and the quick equip menu opening on top of each other.

### Expected behaviour

I expect the stats and the quick equip menu do not open on top of each other.

### Screenshots

![504839CC-BAF5-49E5-ADBC-C7393D244DE9](https://user-images.githubusercontent.com/119818477/209866457-a1a46995-7e16-4552-a991-144476b91ba2.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4999

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 07:19
Duplicate of #2726

**Closed by coolrox95** 2023-03-25 07:19 UTC
Labels: bug, Duplicate
