### ISSUE TITLE
[Bug]: Crash from running out of runes during combat

### ISSUE THREAD

**Issue by TreeSquirrel84** [MelvorIdle/melvoridle.github.io#2031] opened 2022-01-06 07:56 UTC
### Describe the bug

I had a curse and a standard spell both try to go off when I had 2 Mind Runes left in the bank and the QTY apparently went to an unreadable value, causing a crash. The value was properly zero when I loaded back in. No other issues.

An error occurred while processing ticks:
Active Skill: COMBAT
Error Name: TypeError
Error Message: Cannot read property 'qty' of undefined
Stack Trace:
TypeError: Cannot read property 'qty' of undefined
    at BankHelper.addQuantity (https://steam.melvoridle.com/assets/js/built/utils.js?1419:46:119)
    at https://steam.melvoridle.com/assets/js/built/utils.js?1419:50:49
    at Array.forEach (<anonymous>)
    at BankHelper.consumeItems (https://steam.melvoridle.com/assets/js/built/utils.js?1419:50:27)
    at Player.consumeRunes (https://steam.melvoridle.com/assets/js/built/player.js?1419:122:98)
    at Player.attack (https://steam.melvoridle.com/assets/js/built/player.js?1419:99:68)
    at Player.act (https://steam.melvoridle.com/assets/js/built/character.js?1419:186:69)
    at Timer.tick (https://steam.melvoridle.com/assets/js/built/combatManager.js?1419:163:89)
    at Player.tick (https://steam.melvoridle.com/assets/js/built/character.js?1419:177:49)
    at Player.tick (https://steam.melvoridle.com/assets/js/built/player.js?1419:25:14)
Current Equipment:
Helmet: Mithril_Helmet
Platebody: Leather_Body
Platelegs: Leather_Chaps
Boots: Mithril_Boots
Weapon: Staff_of_Air
Amulet: Gold_Topaz_Necklace
Ring: Gold_Emerald_Ring
Gloves: Mithril_Gloves
Quiver: Ice_Arrows
Summon1: Summoning_Familiar_Pig

Skill Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: 0
Is Attacking: false
Standard Spell Selected: 3
Ancient Spell Selected -1
Aurora Selected: -1
Curse Selected: 0
Active Prayers: None
Equipped Food:
Item: Shark, Qty: 1508
Item: Swordfish, Qty: 48
Item: Cave_Fish, Qty: 2016
-- End Player Information --
-- Start of Enemy Information --
Enemy: BlackKnight
Next Action: Attack
Next Attack: 0
Is Attacking: false
Standard Spell Selected: -1
Ancient Spell Selected -1
Aurora Selected: -1
Curse Selected: -1
-- End Enemy Information --
Current Area Type: Combat
Current Area ID: 4

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-07 19:32
Duplicate of #1815

**Closed by coolrox95** 2022-03-07 19:32 UTC
Labels: bug, Duplicate
