### ISSUE TITLE
Error calculating Offline Progress

### ISSUE THREAD

**Issue by Xydin** [MelvorIdle/melvoridle.github.io#1333] opened 2021-09-08 23:56 UTC
![C4FE442E-048A-4F08-84AE-14D2277D32B3](https://user-images.githubusercontent.com/34650106/132600469-12e3e76a-a687-47dc-aa92-ab4e9e490307.png)

Encountered this error when opening the app by tapping on a notification reminding me to harvest a crop of carrots. I was fletching yew long bows at the time and Melvor was running in the background.

**Comment by Xydin** [comment] 2021-09-09 01:43
I’ve encountered this bug a few more times since, and it seems unrelated to the farming notification previously mentioned. I’ve encountered it both when opening Melvor from my Home Screen and via the App Switcher (in both cases Melvor was still loaded in background at the time, I hadn’t swiped up to close it)

**Comment by coolrox95** [comment] 2021-09-13 01:10
Duplicate of #1111

**Closed by coolrox95** 2021-09-13 01:10 UTC
Labels: Duplicate
