### ISSUE TITLE
Agility master relic effect doesn’t work properly

### ISSUE THREAD

**Issue by UmbraLord** [MelvorIdle/melvoridle.github.io#3656] opened 2023-09-15 01:20 UTC
### Describe the bug

The agility master relic isn’t properly removing debuffs from obstacles. In one of my screenshots, I’m wearing all three upgraded red d-hide which should give me 12% dr, but in the stats I’m only showing 10%. This difference is the same amount as the debuff value of the mastered mud dive obstacle. None of the debuffs show visually in the agility skill, but the debuffs are still active. However, the debuffs will get removed if I change an obstacle or increase an obstacle’s mastery level until the game gets refreshed, which will then cause the debuffs to return.

### Reproduction Steps

1. Get all agility relics
2. Check if agility debuffs are visually removed
3. Check something like damage reduction to see if it’s still being affected by an agility debuff

### Expected behaviour

After getting the master agility relic, all obstacle debuffs should be removed without any kind of return

### Screenshots

![IMG_1783](https://github.com/MelvorIdle/melvoridle.github.io/assets/144322799/f1db3d6f-9303-463e-8ac8-ff8f9269072d)
![IMG_1784](https://github.com/MelvorIdle/melvoridle.github.io/assets/144322799/b15a34dc-2d53-4189-8101-6cf5a50d270e)
![IMG_1785](https://github.com/MelvorIdle/melvoridle.github.io/assets/144322799/450a0e1a-5c2f-407f-ad31-2db73a92871c)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7810

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment] 2023-09-18 02:26
Can you please provide a copy of your save?

**Comment by MelvorIdle** [comment] 2023-09-18 02:45
Actually don't worry about the save - I found the cause of the bug

**Comment by MelvorIdle** [comment] 2023-09-18 03:11
This has now been fixed as of Game Update - v1.2 ?7841

**Closed by MelvorIdle** 2023-09-18 03:11 UTC
Labels: bug, In Progress
