### ISSUE TITLE
[Bug]: Received “You cannot do that during a dungeon” msg when not in dungeon

### ISSUE THREAD

**Issue by aibrown146** [MelvorIdle/melvoridle.github.io#2718] opened 2022-10-20 18:25 UTC
### Describe the bug

I logged in after idle thieving Bob the Farmer for about 13 hours.

I had hit 99, so while still thieving I purchased the skillcape and attempted to equip it from the quick equip screen. I received the message “You cannot do that during a dungeon” message followed by the message “Unable to equip thieving skillcape”

Attempts to fix:
- My bank was full so I bought 10 more slots and tried again, no success
- I tried to equip my cape from my inventory, received “you cannot do that during a dungeon” message
- Stopped thieving and tried to equip the cape from the quick equip menu but received same message as above.
- while doing nothing with my character, I Attempted to equip the cape from my inventory and still received the dungeon error message.

Will likely reload the app to see if that works next.

### Reproduction Steps

Login while having been thieving, buy mastery cape, attempt to equip, fail.

### Expected behaviour

Cape should have equipped at all points that I attempted to equip it as I was not in a dungeon.

### Save Link

https://melvoridle.com/save/TRGI47AL

### Screenshots

![9318A827-9063-4C4D-9877-98A0BEB8DBD0](https://user-images.githubusercontent.com/43628007/197028152-fa04625f-8c82-4b95-8224-5f1aa30be425.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-10-21 04:47
Duplicate of #2697

**Closed by coolrox95** 2022-10-21 04:47 UTC
Labels: bug, Duplicate
