### ISSUE TITLE
Closing the steam version via the X button in the top right does not end the windows process nor does it let steam know the game has stopped. Requires killing the process and steam or system runs out of memory eventually.

### ISSUE THREAD

**Issue by secretowl** [MelvorIdle/melvoridle.github.io#507] opened 2020-12-02 14:15 UTC
**Describe the bug**
Closing the steam version via the X button in the top right does not end the windows process nor does it let steam know the game has stopped. Requires killing the process and steam or system runs out of memory eventually.

**To Reproduce**
1. Start game in Steam
2. Click on the X to close the game
3. Check steam (still says game is running) check task manager, Melvor's NWJS process still runs and steals all system memory eventually.

**Expected behavior**
NWJS process should end, and steam should no longer have the [X CLOSE] button.

**Console output**
Not possible, game window is closed

**Are you using any scripts?**
No

**Comment by coolrox95** [comment] 2021-10-01 00:59
Duplicate of  #489

**Closed by coolrox95** 2021-10-01 00:59 UTC
Labels: Duplicate
