### ISSUE TITLE
[Bug]: Astrology skill missing game guide popup

### ISSUE THREAD

**Issue by Mofman1** [MelvorIdle/melvoridle.github.io#2728] opened 2022-10-21 01:08 UTC
### Describe the bug

The game guide button does not work for Astrology.

### Reproduction Steps

1. Select astrology skill from skill list
2. Click on skill icon at the top of the screen that would normally bring up the game guide popup

### Expected behaviour

![image](https://user-images.githubusercontent.com/3620597/197087564-2ab0c102-8023-4e0a-987d-5a385e4c174f.png)
The equivalent to this screen for astrology

### Screenshots

![2022-10-20_20h59_08](https://user-images.githubusercontent.com/3620597/197087352-01d9c140-9a12-4524-a5ba-ec567cc86dd0.png)

### Console output

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_game.php](https://melvoridle.com/index_game.php)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index_game.php](https://melvoridle.com/index_game.php)
Silent Sign in with JWT [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Validating Melvor Cloud token [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Storing Melvor Cloud Token [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Initializing PlayFab login. Method: customID [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Logging in with Custom ID via PlayFab [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Login with custom ID success [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Getting account info [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Account info retrieved [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Authenticated w/ Melvor Cloud: true [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Authenticated w/ PlayFab: true [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Checking for valid full version [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Checking for valid TotH purchase [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Loading Game Data... [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Registered Demo Data. [save.js:111:189](https://melvoridle.com/assets/js/built/save.js?4501)
Registered Full Version Data. [save.js:111:355](https://melvoridle.com/assets/js/built/save.js?4501)
Registered Throne of the Herald Data. [save.js:111:522](https://melvoridle.com/assets/js/built/save.js?4501)
Initializing Mod Manager... [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
PlayFab Data Stored successfully. [cloud.js:147:75](https://melvoridle.com/assets/js/built/cloud.js?4501)
Checking for Mod Updates... [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Loading Mods... [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Loading Local Saves... [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Loading Cloud Saves... [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Getting saves from playfab [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Saves retrieved [cloudManager.js:194:22](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Loading character selection [characterSelect.js:5:297](https://melvoridle.com/assets/js/built/characterSelect.js?4501)
Connected to PlayFab successfully [cloudManager.js:289:186](https://melvoridle.com/assets/js/built/cloudManager.js?4501)
Game Loaded [main.js:15:315](https://melvoridle.com/assets/js/built/main.js?4501)
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[v1.1ReleaseNotes.html](https://melvoridle.com/update/v1.1ReleaseNotes.html)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [v1.1ReleaseNotes.html](https://melvoridle.com/update/v1.1ReleaseNotes.html)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index.html](https://melvoridle.com/roadmap/index.html)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194. (Reason: CORS request did not succeed). Status code: (null).

None of the “sha512” hashes in the integrity attribute match the content of the subresource. [index.html](https://melvoridle.com/roadmap/index.html)
Synchronising with Cloud

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-10-21 04:44
Duplicate of #1605

**Closed by coolrox95** 2022-10-21 04:44 UTC
Labels: bug, Duplicate
