### ISSUE TITLE
[Bug]: <title>Unable to switch store purchase quantity

### ISSUE THREAD

**Issue by messiahkk** [MelvorIdle/melvoridle.github.io#3048] opened 2022-11-30 04:21 UTC
### Describe the bug

The amount I entered in the store was so large that it pushed the input key off the screen and prevented me from switching the amount

### Expected behaviour

1. Go to the store
2. Click toggle purchase amount
3. Enter a large enough number
4.Confirmation
5.An bug occurs

### Screenshots

![VW6Z~0W~EOX`WXBVM3)$U3T](https://user-images.githubusercontent.com/119469774/204706455-f8b164d8-b3ee-4f4a-808c-8036860e6241.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 05:28
Duplicate of #2994

**Closed by coolrox95** 2023-03-25 05:28 UTC
Labels: bug, Duplicate
