### ISSUE TITLE
Goblin Raid Bug

### ISSUE THREAD

**Issue by Baneswolfcry** [MelvorIdle/melvoridle.github.io#1495] opened 2021-10-21 22:45 UTC
**Describe the bug**
After dying in goblin raid, the following error is show:
An error occured while processing ticks:
Active Skill: OTHER
Error Name: TypeError
Error Message: items[itemID] is undefined
Stack Trace:
getItemMedia@https://melvoridle.com/assets/js/game/main.js?1202:360:44
getGolbinRaidHistory@https://melvoridle.com/assets/js/built/raidManager.js?1202:126:112
loadGolbinRaidHistory@https://melvoridle.com/assets/js/game/golbinraid.js?1202:2:143
changePage@https://melvoridle.com/assets/js/game/main.js?1202:71:133
stopCombat@https://melvoridle.com/assets/js/built/raidManager.js?1202:23:118
checkDeath@https://melvoridle.com/assets/js/built/baseManager.js?1202:14:21
tick@https://melvoridle.com/assets/js/built/baseManager.js?1202:8:67
tick@https://melvoridle.com/assets/js/built/raidManager.js?1202:12:7
tick@https://melvoridle.com/assets/js/built/game.js?1202:28:71
runTicks@https://melvoridle.com/assets/js/built/game.js?1202:26:96
processTime@https://melvoridle.com/assets/js/built/game.js?1202:25:6
loop@https://melvoridle.com/assets/js/built/game.js?1202:39:49

**To Reproduce**
Die in goblin raid

**Expected behavior**
when I die, it produces the following error. I am unable to click out of it and have to refresh the tab to get back into melvore

**Browser**
Firefox

**Are you using any scripts?**
No scripts

**Comment by coolrox95** [comment] 2021-10-22 00:54
Duplicate of #1450

**Closed by coolrox95** 2021-10-22 00:54 UTC
Labels: Duplicate
