### ISSUE TITLE
[Bug]: Lv 100 township Estate buildings worse

### ISSUE THREAD

**Issue by Curly765** [MelvorIdle/melvoridle.github.io#2870] opened 2022-10-31 17:34 UTC
### Describe the bug

Most of the lv 100&110 "estate" tier township buildings have worse production rates than their respective lower tiers.  I thought maybe they'd increased your population limit or something since they have estate in the name, but that doesnt appear to be the case.  As far as I can tell, these buildings are 100% a downgrade.

### Reproduction Steps

Default map 1

### Screenshots

![Screenshot_20221031_102333_Melvor Idle](https://user-images.githubusercontent.com/117109262/199071965-71fd2518-4b09-4dfa-8dfa-c8c0ba0ad273.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

No

**Comment by GauChoob** [comment] 2022-11-02 21:35
Duplicate of https://github.com/MelvorIdle/melvoridle.github.io/issues/2867, this issue is caused from a missing biomeModifier

**Comment by MelvorIdle** [comment] 2023-04-12 04:39
Township has now been reworked as of v1.1.2

**Closed by MelvorIdle** 2023-04-12 04:39 UTC
Labels: bug, Township
