### ISSUE TITLE
BIrthday Event Fishing

### ISSUE THREAD

**Issue by ricardoventura21** [MelvorIdle/melvoridle.github.io#3715] opened 2023-09-25 15:07 UTC
### Describe the bug

Hey Malcs, i already tagged you in discord chat but the problem is: i already win 2 times in the fishing contest and i dont get the final reward.

### Expected behaviour

I should have received the last reward of fishing contest

### Screenshots

![Captura de ecrã 2023-09-25 154140](https://github.com/MelvorIdle/melvoridle.github.io/assets/73975244/5f29ec1c-fc91-4355-bd32-d4537bec42c8)
![Captura de ecrã 2023-09-25 154211](https://github.com/MelvorIdle/melvoridle.github.io/assets/73975244/ea249bce-19df-43ec-b122-e47b5047d4f4)
![Captura de ecrã 2023-09-25 151553](https://github.com/MelvorIdle/melvoridle.github.io/assets/73975244/cf47fcaf-6b65-4ce0-ab95-94bcfc4eeb19)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7902

### Are you using any mods?

No

**Comment by MelvorIdle** [comment] 2023-09-26 01:23
Duplicate of #3706

**Closed by MelvorIdle** 2023-09-26 01:23 UTC
Labels: bug
