### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Dreadeddrgn6** [MelvorIdle/melvoridle.github.io#1528] opened 2021-10-28 00:24 UTC
So I'm not experienced with cooking after the update, but when cooking whales, I only get about 6k per 12 hours or so. Is that normal to be so slow? 
also, When I'm online the whales don't go into my bank even when it says theyve been made (I check both perfect and regular, even though I make perfect 100%

**Comment by coolrox95** [comment] 2021-11-04 08:21
Duplicate of #1416

**Closed by coolrox95** 2021-11-04 08:21 UTC
Labels: Duplicate
