### ISSUE TITLE
[Bug]: <zoom on samsung mobile>

### ISSUE THREAD

**Issue by Bvsedog** [MelvorIdle/melvoridle.github.io#2333] opened 2022-03-15 12:33 UTC
### Describe the bug

When I log in on my galaxy it is super zoomed in on portrait mode to the point where I can't even click on my account in the top right.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1849

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-15 19:31
Duplicate of #2290

**Closed by coolrox95** 2022-03-15 19:31 UTC
Labels: bug, Duplicate
