### ISSUE TITLE
No astrology skill menu [Bug]: <title>

### ISSUE THREAD

**Issue by gaza9422** [MelvorIdle/melvoridle.github.io#2859] opened 2022-10-30 10:22 UTC
### Describe the bug

All skill you click the name and it gives you a description of the skill and items etc but astrology isn't opening 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4641

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2023-03-25 22:33
Duplicate of #2922

**Closed by coolrox95** 2023-03-25 22:33 UTC
Labels: bug, Duplicate
