### ISSUE TITLE
Attack speed bugged after throwing knives ran out

### ISSUE THREAD

**Issue by NoLifeSoul** [MelvorIdle/melvoridle.github.io#954] opened 2021-05-02 01:03 UTC
**Describe the bug**
The attack speed went down to 0.1 seconds or thelike, increasing everytime I clicked on the combat menu. This did not reset on switching gear, attack style or even enemies. Due to the insanely high attack speed you could kill even god wars bosses barehand in 2 seconds despite having like 11% accuracy. On top of that you kept getting xp for a successful attack despite not even fighting enemies.

**To Reproduce**
I did try to reproduce it albeit I couldn't. It seemed to have happened with steel throwing knives while killing an enemy with sandstorm / running out of knives and coming from another menu (bank / farming menu) back to combat. Once it happened I couldn't get out of the bug anymore until i closed and reopened the game. I just noticed that I was out of throwing knives again (used up small amount of every kind due to chests I had) and saw that my attack speed was bugged and he was attacking rapidly. When I went to my bank and back to the combat window I noticed it increased in speed. When I began spamclicking the combat level I noticed it got faster and faster (not on video, the videos listed below are before spam clicking it)

**Screenshots**
The beginning when I noticed the bug:
https://streamable.com/c27g4l
I didn't change any gear, combat style or anything in this video yet, this is how I got back to the combat menu. I ran out of steel throwing knives.

After trying to get out of the bug (changing gear, attack style, enemies and fleeing, trying to fish to stop it aswell, didn't stop it):
https://streamable.com/zxanil

**Browser**
Steam, latest stable version published (Alpha v0.19.2)

**Console output**
None as it happened in the steam client and I couldn't reproduce it afterwards as I am unsure what exactly it triggered

**Are you using any scripts?**
None

EDIT: After rewatching the first clip again it seems like it's a sandstorm bug rather than throwing knives dependend. It looks like it doesn't leave the sandstorm special state and whenever clicking the combat level it started a new sandstorm special, overlapping with the old one, resulting in more and more xp per seconds and more and more damage / attacks per second

**Comment by MelvorIdle** [comment] 2021-05-25 01:45
Closing this one for now as I am unable to reproduce. Potentially fixed in next major update with all the changes that have been made.

Feel free to re-open if you experience this bug again in the next major update.

**Closed by MelvorIdle** 2021-05-25 01:45 UTC
Labels: bug
