### ISSUE TITLE
[Bug]: Error/No restriction on converting rune with Just Learning

### ISSUE THREAD

**Issue by Lokallu** [MelvorIdle/melvoridle.github.io#3960] opened 2023-12-29 08:23 UTC
### Describe the bug

One can cast Just Learning with 1 (and only 1) Nature/Air rune and set target with that same rune.
Resulting error message and the game must be restarted.

### Reproduction Steps

1. Leave 1 Nature rune and 1 Air rune in bank
2. Go Alt Magic, Just Learning
3. Set target to be Nature/Air rune
4. Press cast

### Expected behaviour

Spell should not be cast as there is not enough cost.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8284

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-01-24 18:41
Duplicate of #3992

**Closed by coolrox95** 2024-01-24 18:41 UTC
Labels: bug, Duplicate
