### ISSUE TITLE
[Bug]: Firemaking "Mastery Exp" has the wrong value

### ISSUE THREAD

**Issue by Dohtt** [MelvorIdle/melvoridle.github.io#2931] opened 2022-11-07 13:01 UTC
### Describe the bug

Firemaking displays "2060" mastery exp, but when peforming an action i gain 2595 mastery experience.

### Reproduction Steps

1. Go to firemaking
2. Check the value on "Mastery exp"
3. Perform a firemaking action
4. Check the starting value of your firemaking mastery exp of that specific log and compare it to the new value.

### Expected behaviour

The value in the UI should be pulled correctly.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-12-20 23:48
Duplicate of #2746

**Closed by coolrox95** 2022-12-20 23:48 UTC
Labels: bug, Duplicate
