### ISSUE TITLE
[Bug]: Reloading

### ISSUE THREAD

**Issue by LokiDev93** [MelvorIdle/melvoridle.github.io#3473] opened 2023-06-28 01:44 UTC
### Describe the bug

I keep being forced into a reload when I try to enter custom numbers to buy items. I can enter in the value but if you hit the ender arrow it immediately reloads the game.

### Reproduction Steps

1. Go to buy any item, in the shop window or from the crafting/farming areas. Buy leather, fertilizer, summoning shards, bank spaces to name different things I have had this happen with.
2. Change how much your looking to buy, so say 15 of the items. One you type 15 into the custom amount field hit the enter arrow on your keyboard (mobile)
3. Wait for the reboot to finish to log back into your character.

### Expected behaviour

To me it should just close the keyboard and save the value for how many your looking to buy.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6099

### Are you using any mods?

No

**Comment by maverson** [comment] 2023-07-25 03:08
Getting the same bug but on steam platform.

platform:
steam/windows 

version: 
v1.1.2

subversion:
?6126

mods:
No

**Comment by coolrox95** [comment] 2023-08-26 16:00
Duplicate of #3383

**Closed by coolrox95** 2023-08-26 16:00 UTC
Labels: bug, Duplicate
