### ISSUE TITLE
[Bug]: Game does not shut down properly sometimes

### ISSUE THREAD

**Issue by HackworthCForge** [MelvorIdle/melvoridle.github.io#4395] opened 2024-06-19 09:46 UTC
### Describe the bug

On Desktop/Windows/Steam, the game sometimes does not shut down properly. Steam views the game as still running in those cases. Sometimes the Windows Task manager will still show Melvor.exe running indefinitely, sometimes not. 

If Melvor.exe is visible, terminating the process is a work-around. If melvor.exe is not visible, shutting the game down from Steam library does not work, you have to shut down Steam entirely.

The issue has been much more common since v1.3 release.

### Reproduction Steps

Not reproducable, happens randomly. It can happen on multiple consecutive startups/shutdowns, then not happen for days.

### Expected behaviour

Game is expected to shut down all processes on closing, Steam is expected to recognize that.

### Console output

could not open console, F12 has no function.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11455

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-08-21 18:54
Duplicate of #3786

**Closed by coolrox95** 2024-08-21 18:54 UTC
Labels: bug, Duplicate
