### ISSUE TITLE
[Bug]:  Text on the bank slot in the shop being duplicated.

### ISSUE THREAD

**Issue by DuncanBauer** [MelvorIdle/melvoridle.github.io#2128] opened 2022-01-31 18:38 UTC
### Describe the bug

"Buy limit of 88 reached" text on the bank slot in the shop is being duplicated.

### Reproduction Steps

Create a hardcore character.
Purchase all 88 bank slots from the shop, without buying other General Upgrades.
Purchase a General Upgrade.
"Buy limit of 88 reached." text on the Extra Bank Slot item in the shop will be duplicated.

### Expected behaviour

For the text not to be duplicated.

### Screenshots

![Capture](https://user-images.githubusercontent.com/9126391/151852780-11b71f27-04a1-4fef-872c-11e863b411d7.PNG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-06 08:57
Duplicate of #1760

**Closed by coolrox95** 2022-03-06 08:57 UTC
Labels: bug, Duplicate
