### ISSUE TITLE
[Bug]: burning yew logs mastery value bug

### ISSUE THREAD

**Issue by lhs-source** [MelvorIdle/melvoridle.github.io#3052] opened 2022-12-01 06:49 UTC
### Describe the bug

![Screenshot_20221201_090620_Melvor Idle](https://user-images.githubusercontent.com/66777090/204983864-26213d09-6dae-4086-b867-2df91c397b12.jpg)
 this is before burning a yew log.
![Screenshot_20221201_090622_Melvor Idle](https://user-images.githubusercontent.com/66777090/204983887-eb917570-d5ae-4e54-bf1e-b2d705bba51a.jpg)
 after burning it.

the mastery had been up 311 point, but a yew log should give me 469.

### Reproduction Steps

restrt the game.
change screen...

### Expected behaviour

it gives right mastery value

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

4928

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-12-21 01:03
Duplicate of #2746

**Closed by coolrox95** 2022-12-21 01:03 UTC
Labels: bug, Duplicate
