### ISSUE TITLE
[Bug]: Township Worship Not Registering 

### ISSUE THREAD

**Issue by jmassey1991** [MelvorIdle/melvoridle.github.io#2810] opened 2022-10-26 01:22 UTC
### Describe the bug

My township worship is not registering and the bonuses are not being applied. Not sure how this happened but I noticed my township tasks were reset today.. Something to do with a new build / patch? I had Ragnar as my god.

![image](https://user-images.githubusercontent.com/31499017/197911514-1450b3dd-26f2-423b-9377-6bce783c3fb7.png)

My Arid Plains should have a bonus production but it does not.
![image](https://user-images.githubusercontent.com/31499017/197911643-d7b4cf3a-5e20-464c-a45a-5dfc36788012.png)
![image](https://user-images.githubusercontent.com/31499017/197911694-47ea9d07-a23e-4ada-bd70-936109fbc8e8.png)

### Reproduction Steps

1. Go to township tab on my account and see that worship isn't working
Username: LordMayonnaise

### Expected behaviour

Expect worship to provided correct bonuses and show in township tab

### Save Link

https://melvoridle.com/save/FATaZnjH

### Screenshots

The screenshots were from my desktop steam application but this bug happened on my iOS IPhone.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4615

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-24 22:42
Duplicate of  #2774

**Closed by coolrox95** 2023-03-24 22:42 UTC
Labels: bug, Duplicate
