### ISSUE TITLE
Aorpheat's Signet Ring and Firemaking

### ISSUE THREAD

**Issue by filupa** [MelvorIdle/melvoridle.github.io#898] opened 2021-03-29 15:44 UTC
**Describe the bug**
Considering this two facts:

1. In the description of the Aorpheat Ring said: "When equipped: +100% GP granted from **all sources except Alt. Magic and item Selling**..."
2. At 50% checkpoint in Firemaking skill: "Received GP equal to 25% of the value of the Log you are burning"

If I understand correctly, the ability to received a +100%GP from Aorpheat Ring must also affect the Received GP from firemaking Skill at 50%.

**To Reproduce**
1. take it off the Aorpheat Ring, (if you have equipped)
2. Burn some LOGs when you have 50% firemaking skill and register the GP recieved
3. equipped the Aorpheat Ring
4. Check the received GP is the same as before

**Screenshots**
Without the Ring:
![Captura de pantalla 2021-03-29 a la(s) 12 36 15](https://user-images.githubusercontent.com/4204365/112861841-8f105c00-908b-11eb-8c4d-11c41440c456.png)

With the Ring:
![Captura de pantalla 2021-03-29 a la(s) 12 36 46](https://user-images.githubusercontent.com/4204365/112861894-9b94b480-908b-11eb-9077-ad290906c159.png)

Maybe this is only an error in the value show in the pop-up image, but in the bank is added correctly, I can't validate that

**Browser**
In brave Browser and in Android App

**Comment by coolrox95** [comment] 2021-09-12 23:58
Duplicate of #868

**Closed by coolrox95** 2021-09-12 23:58 UTC
Labels: Duplicate
