### ISSUE TITLE
[Bug]: Cyclops Item Mastery unlocks delayed effect

### ISSUE THREAD

**Issue by KingDeDeDe11** [MelvorIdle/melvoridle.github.io#2162] opened 2022-02-07 09:46 UTC
### Describe the bug

Summoning crafting cost reduction for mastery of a craft did not go into effect immediately.

When leveling summoning I started making Cyclops. I was level 82, and had reached mastery level 10 on crafting it, but the cost reduction did not go into effect. I kept crafting, and reached mastery 20, and then the first cost reduction went into effect. I paused after a bit, having reached mastery 21 on Cyclops, and then at some point the second cost reduction went into effect.

### Reproduction Steps

1. Start crafting cyclops familiars with no mastery
2. Watch slayer coin cost when reaching mastery 10-19
3. Watch slayer coin cost when reaching mastery 20-12
4. Pause halfway through mastery 21

### Expected behaviour

I expected the slayer coin cost of Cyclops to immediately reduce to 950 on reaching mastery level 10, and then 900 on reaching mastery level 20, not after a delay.

### Screenshots

![image](https://user-images.githubusercontent.com/11394704/152761798-c9a172d0-3622-4e82-9c6f-d619054ad683.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

1530

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-09 18:10
Duplicate of #1891

**Closed by coolrox95** 2022-03-09 18:10 UTC
Labels: bug, Duplicate
