### ISSUE TITLE
Golbin Upgrades not showing up

### ISSUE THREAD

**Issue by singh497** [MelvorIdle/melvoridle.github.io#2394] opened 2022-04-11 21:20 UTC
### Describe the bug

When I go to the Golbin upgrade shop, I can't buy the infinite-purchasing upgrades like the food bonus upgrade and the max ammo upgrade. Once I buy it once, it disappears and I can't continue buying it.

![Golbin](https://user-images.githubusercontent.com/47434320/162835103-369cb0f9-8230-4658-8ba9-4809a2a30a4f.PNG)

### Reproduction Steps

Go to Golbin raid shop.
Buy the first level of infinitely purchasable upgrade
Realize that you can't buy it again.

### Expected behaviour

I'm pretty sure I did this back in the day and it would just show you what your current level is and it would increase with every purchase.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment] 2022-05-10 00:57
Duplicate of #2378

**Closed by MelvorIdle** 2022-05-10 00:57 UTC
Labels: bug
