### ISSUE TITLE
[Bug]: <title>T3 shard reduction cost is applied at 50% pool instead of 95%

### ISSUE THREAD

**Issue by Flurryous** [MelvorIdle/melvoridle.github.io#2409] opened 2022-04-18 04:26 UTC
### Describe the bug

As the title says, the T3 shard cost is reduced by 1 when your mastery pool is at 50%, despite that being the 95% pool's benefit. This is not just a visual bug, the reduction is actually applied. 

### Reproduction Steps

1. Get to the 50% checkpoint mastery pool
2. Refresh the summoning page (for me I go to another page then go back)
3. Look at the T3 tablet costs and see that the shard cost seems to have been reduced by 1.
4. Try to create one batch of tablets with that amount of shards, it'll work successfully, so it's not a visual bug.
5. Drop your pool below 50% and refresh the summoning page again. Shard cost has gone back up by 1. 

### Expected behaviour

At 50% mastery pool, the shard cost for all the T3 tablets should not be reduced by 1. 

### Screenshots

Thanks to Nomeru from the discord for providing screenshots of the code, they seem to have spotted why this is happening. 

https://cdn.discordapp.com/attachments/625838709744599088/965464320345538610/unknown.png
PoolTierActive(2) is associated with the 50% checkpoint, as it's supposed to provide resource preservation.

https://cdn.discordapp.com/attachments/625838709744599088/965463992699080774/unknown.png
From this screenshot it seems that PoolTierActive(2) was incorrectly assigned to give tier 3 tablets a cost reduction. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment] 2022-05-12 01:13
Level 50 Mastery also reduces shard cost by 1. I assume you levelled up your tablet to over level 50 to get this cost reduction.

I will close this for now as I cannot reproduce. When the new update arrives feel free to post another report if you reproduce the bug.

**Closed by MelvorIdle** 2022-05-12 01:13 UTC
Labels: bug
