### ISSUE TITLE
All Skill Upgrades Appearing

### ISSUE THREAD

**Issue by Jokas377** [MelvorIdle/melvoridle.github.io#2313] opened 2022-03-09 19:23 UTC
### Describe the bug

Whenever starting up Melvor Idle, automatically opening to the Combat Screen, the skill upgrades Multi-Tree, Perpetual Haste, Expanded Knowledge, Art of Control, and Master of Nature appear in the bottom right Minibar, read “Active”, and give a description of the skill. The pet icon for Beavis also appears although there is no result when tapping on its icon. Whenever I switch to a different screen and then back to the combat screen, the Minibar disappears. This happens each time I start up Melvor Idle and am idling combat. This does not occur whenever I am idling something other than combat. I have not tried to see the results of changing which screen the game starts up to. It should also be of note that while I do have the skill Multi-Tree and the pet Beavis, I have none of the skills unlocked by defeating the God Dungeons.

### Reproduction Steps

1. Leave Melvor Idle while idling Combat
2. Restart Melvor Idle

### Expected behaviour

The skills Multi-Tree, Perpetual Haste, Expanded Knowledge, Art of Control, and Master of Nature appear in the bottom right Minibar, read “Active”, and give a description of this skill. The pet icon for Beavis also appears, however there is no result when tapping on its icon.

### Save Link

https://melvoridle.com/save/QJb2Qghy

### Screenshots

![01FDD2A8-D728-4B55-9C09-6F26737FAD63](https://user-images.githubusercontent.com/96864800/157515805-3e9f8472-a3b1-4dd6-9b2d-299ddef4cdab.png)
![1E3A14C3-CA7F-4776-A980-C3F9A1ED9A92](https://user-images.githubusercontent.com/96864800/157515812-e09f275b-1c7e-4cae-aa3e-edf6e08a74fe.png)
![EC1E7C79-6786-4EE3-B735-9AB904656287](https://user-images.githubusercontent.com/96864800/157515815-6540ecaa-bd9d-46b6-9100-09652f358128.png)
![F9FBFFAA-DF48-417D-9D2D-2735B9178D51](https://user-images.githubusercontent.com/96864800/157515820-fd334e8b-b927-4776-b100-2f40cd6d467b.png)
![B9875EA1-43E0-40EA-97AB-5AB193676032](https://user-images.githubusercontent.com/96864800/157515824-a7d364a2-724f-471c-99b0-b1e3485c9da4.png)
![9F9EFEB1-522D-403C-BF16-DA252F02DC74](https://user-images.githubusercontent.com/96864800/157515830-b496fa8d-53e3-4a51-8f7b-2fccd3895cad.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1843

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-09 20:32
Duplicate of #2243

**Closed by coolrox95** 2022-03-09 20:32 UTC
Labels: bug, Duplicate
