### ISSUE TITLE
[Bug]: Game does not format properly on galaxy note 10 Lite

### ISSUE THREAD

**Issue by Schmitty675** [MelvorIdle/melvoridle.github.io#2309] opened 2022-03-08 15:22 UTC
### Describe the bug

The game is zoomed in and doesn't fit the screen right.

### Reproduction Steps

1. Open game

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1834

### Are you using any scripts or extensions?

No

**Comment by xedlix** [comment] 2022-03-08 23:41
Same at the galaxy fold 3
![Screenshot_20220309-003540_Video Player](https://user-images.githubusercontent.com/57345481/157344061-bb7ce9ca-080b-47f5-9f37-a9f9902125a8.jpg)
First picture is the old and better arangement and scale

![Screenshot_20220309-003657_Melvor Idle](https://user-images.githubusercontent.com/57345481/157344170-360e2c5e-d21f-44bf-8b16-8b577151d9e5.jpg)
Now it locks like this and is almost unplayable. It is to big for this ratio of screen.
The old one was perfect.

**Comment by coolrox95** [comment] 2022-03-09 02:46
Duplicate of  #2290

**Closed by coolrox95** 2022-03-09 02:46 UTC
Labels: bug, Duplicate
