### ISSUE TITLE
[Bug]: During tutorial the Farming skill is highlighted incorrectly 

### ISSUE THREAD

**Issue by MBijen** [MelvorIdle/melvoridle.github.io#3442] opened 2023-06-04 07:24 UTC
### Describe the bug

During the tutorial the highlight of ‘Farming’ is done incorrectly. The old place is still highlighted instead of the new place of the Farming on iOS

### Reproduction Steps

Follow tutorial up to step ‘Farming’

### Expected behaviour

Highlight correct skill in menu. 

### Screenshots

![IMG_4004](https://github.com/MelvorIdle/melvoridle.github.io/assets/35292193/72ef281d-ee45-4436-b99f-5c394c3e62c8)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-08-26 16:25
Duplicate of #3396

**Closed by coolrox95** 2023-08-26 16:25 UTC
Labels: bug
