### ISSUE TITLE
[Bug]: < Blacksmith's pickaxe upgrade is delayed>

### ISSUE THREAD

**Issue by SatmanDaedra** [MelvorIdle/melvoridle.github.io#3198] opened 2023-01-31 11:00 UTC
### Describe the bug

I bought the augite pick and it counted as if I had bought the coridonite pick.

Now he asks me to buy the meteorite pickaxe so he can use it as if it were the augite pickaxe.

I don't have a backup game.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

V1.1.1 (?5047)

### Are you using any mods?

No

**Comment by AdamRiot** [comment] 2023-02-06 22:03
Having the same problem with the woodcutting axe, it is displaying the bonus of the last tier's axe.  Not sure if it is just a display bug of not.
![bug](https://user-images.githubusercontent.com/69919061/217097800-2fbffd13-ce9b-4287-8324-09ab4a2b6afd.jpg)

**Comment by coolrox95** [comment] 2023-03-25 08:48
Duplicate of #3034

**Closed by coolrox95** 2023-03-25 08:48 UTC
Labels: bug, Duplicate
