### ISSUE TITLE
Cooking offline progress error

### ISSUE THREAD

**Issue by Rosethecute** [MelvorIdle/melvoridle.github.io#1376] opened 2021-09-25 08:39 UTC
**Describe the bug**
The bug does noes allow cooking to update, and showed a code that had to be shown to the dev. (this is all in the first screenshot)

**To Reproduce**

**Expected behavior**
I expected to see a normal offline report as of what i had cooked
**Screenshots**
![billede](https://user-images.githubusercontent.com/91367773/134765181-009a82a2-9d8a-4ea5-ab03-3ba6286fecc3.png)

**Browser**
Used on Firefox 92

**Console output**
![billede](https://user-images.githubusercontent.com/91367773/134765273-a5fb9fc0-3e0e-4329-b731-0ee541aea5c3.png) screenshot added, as it wouldn't allow me to copy it

**Are you using any scripts?**
no scripts are used

**Comment by MelvorIdle** [comment] 2021-10-01 00:25
Do you play multiple characters in more than one window at a time?

**Comment by Rosethecute** [comment] 2021-10-01 08:18
I do, all be it sometimes it happens, sometimes it does not which is sometimes a little odd to me to see

**Comment by coolrox95** [comment] 2021-11-04 08:03
Duplicate of #1562

**Closed by coolrox95** 2021-11-04 08:03 UTC
Labels: Duplicate
