### ISSUE TITLE
[Bug]: <Unable to switch store purchase quantity>

### ISSUE THREAD

**Issue by snakekwok** [MelvorIdle/melvoridle.github.io#3075] opened 2022-12-07 13:07 UTC
### Describe the bug

The amount my cat entered in the store was so large that it pushed the input key off the screen and prevented me from switching the amount

### Reproduction Steps

1.Click toggle purchase amount
2.Enter a large enough number
3.Confirmation
4.An bug occurs

### Screenshots

![QQ图片20221207205804](https://user-images.githubusercontent.com/33418527/206186710-cb8f569a-6a9f-4d56-9a83-01bce2dd3e16.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-12-21 01:21
Duplicate of #2994

**Closed by coolrox95** 2022-12-21 01:21 UTC
Labels: bug, Duplicate
