### ISSUE TITLE
[Bug]: Ran into an error calculating offline progress in Cooking

### ISSUE THREAD

**Issue by zants** [MelvorIdle/melvoridle.github.io#1549] opened 2021-11-02 15:52 UTC
### Describe the bug

Here's another cooking error; I see two other bug reports that look very similar on the front page here but thought I'd report it as well just in case there was a minor difference that helps.  Screenshot attached, I was cooking Crab at the time.

I'm also not sure if this is relevant, but I'm not seeing this behavior with other skills: when I return to the game each time, and after it calculates my offline progress, the amount of raw Crab I have banked doesn't update until after I cook a new Crab; for example, it'll show 50 raw Crab in my bank (even though the offline progress showed I cooked 20 of them, so I should have 30 left), and then it will cook one and update the number to 29 raw Crab.

This is the full text copy from the error:

> Welcome back!
> 
> We ran into an error while calculating your Offline Progress! >:( Your Skill was also stopped in the process.
> 
> Please let the dev know of this error:
> 
> Skill: 3 Action: 28
> 
> Timestamp: 1635860017692
> 
> @https://ios.melvoridle.com/assets/js/game/main.js?1209:164:37
> 
> Continue to game

### Reproduction Steps

1. Have 1,300-1,400 raw Crab in your bank
2. Go to Cooking page
3. Select to active cook Crab
4. Leave game running in the background while using another app (in my case, YouTube) while a countdown timer (iOS' Clock app) also runs in the background
5. Return to game when the Clock's alarm goes off, receive error
6. Close and load game, about 1,000 Crab cooked meaning it lost progress with about 300-400 left (the time given for the alarm would have been ample to cook all, however)

### Expected behaviour

All 1,300-1,400 Crab would be cooked

### Screenshots

![AC8D4814-AD97-4CCD-BE1A-9E26B1C3C1EB](https://user-images.githubusercontent.com/822329/139880052-129f0341-e73c-48ef-8c44-e9cb2400b4f8.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2021-11-04 08:13
Duplicate of #1478

**Closed by coolrox95** 2021-11-04 08:13 UTC
Labels: Duplicate
