### ISSUE TITLE
[Translation Error]: <title>

### ISSUE THREAD

**Issue by Fose99** [MelvorIdle/melvoridle.github.io#3235] opened 2023-02-27 20:13 UTC
### Which text in the game has a translation error?

Frostspark 1H Sword
![42C959AE-24C0-4C93-B634-4CB6244674F1](https://user-images.githubusercontent.com/126517461/221673330-6dc652f1-1993-44d3-819a-b3f7e6c49f1a.png)

**Comment by coolrox95** [comment] 2023-03-24 23:42
Duplicate of #3072

**Closed by coolrox95** 2023-03-24 23:42 UTC
Labels: Duplicate, Localisation Bug
