### ISSUE TITLE
Compost count UI on farming screen not updating after purchase

### ISSUE THREAD

**Issue by richard-braindropsoftware** [MelvorIdle/melvoridle.github.io#1299] opened 2021-08-30 01:21 UTC
Purchasing 10 compost successfully added then to my bank and usable compost, but the UI on the farming screen did not update (I had 21, but UI still said 11)

![Screenshot_20210829-205107](https://user-images.githubusercontent.com/66473861/131272644-b03801ff-6b78-4cb9-944c-d5075e6dea91.png)

**Comment by coolrox95** [comment] 2021-11-02 21:43
Duplicate of #1257

**Closed by coolrox95** 2021-11-02 21:43 UTC
Labels: Duplicate
