### ISSUE TITLE
[Bug]: Bank Slots

### ISSUE THREAD

**Issue by jarob323** [MelvorIdle/melvoridle.github.io#2498] opened 2022-06-20 21:47 UTC
### Describe the bug

I used to want the full version of the game, if it were available directly, now I no longer do.  I cannot imagine having to create enough bank slots to support ranged, magic, thievery, etc.  The skills look interesting, but no.  I will have enough problems being able to keep event items and new equips (like godswords).

I first got into trouble in the tutorial.  If it said cut 2 logs, I cut 10.  Why not?  It didn't say not to.  Well when I got to making arrows, I bought feathers and made headless arrows.  But when I tried to attach the points, I ended up with no arrows and no headless arrows.  Once I realized it was a bank space problem, I found I didn't have enough gp to buy more feathers.  Had to get more stuff and sell it, just to progress.

If you look at online comparisons of runescape-like idlers, this bank slot issue is mentioned.  This isn't supposed to be a game of "who can get the most bank slots".  There's no rl financial gain for the game in doing this, it's just being gnarly.

In OSRS, there are many spaces other than in the bank :
- storage for all seeds and saplings in the farmer's guild
- storage for lots of equip and event-special items in the costume room (house)
- tools in the workshop (house)
- kitchen shelves etc (house)
- tool leprechaun
- fossil storage
- and more ....
And they're all free.  Jagex knew we needed more space.

Here, the cost of getting more spaces escalates so fast, we have no chance.

Fix : There should be 2 slots for every existing slot, both initial and purchased.  Then more storage capabilities added later as skills develop.  

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1983

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment] 2022-06-21 00:33
It's quite easy to acquire bank spaces in this game. They also cap out at a maximum GP cost once you reach 100-ish slots so they never get more expensive after that.

You can get millions of GP per hour in this. Even in the very early game you can get hundreds of thousands of gp per hour.

Closing as this is not a bug

**Closed by MelvorIdle** 2022-06-21 00:33 UTC
Labels: notabug
