### ISSUE TITLE
[Bug]: Switching to higher tier potion when hitting that tier offline

### ISSUE THREAD

**Issue by BrianMahocker** [MelvorIdle/melvoridle.github.io#2084] opened 2022-01-20 14:29 UTC
### Describe the bug

When the available tier of potion changes offline due to the mastry level going high enough, it will not give that higher tier when calculating offline gains

### Reproduction Steps

1. Start crafting potions
2. Go offline long enough to change tier from I to II, or II to III or III to IV due to potion mastery level
3. Come back online and see that only potions of the lower tier were created

### Expected behaviour

I'd expect for some of the old tier potions to be created before the mastery was high enough, and then some of the new tier potions to be created after the mastery was high enough, all in the same offline calculation.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by ekuland** [comment] 2022-01-20 14:48
Same as #2040 - still currently intended.

**Comment by coolrox95** [comment] 2022-01-29 01:31
Duplicate of #2040

**Closed by coolrox95** 2022-01-29 01:31 UTC
Labels: Duplicate
