### ISSUE TITLE
[Bug]: Tutorial Island early completion of Bow fletching quest locks shop

### ISSUE THREAD

**Issue by AcidaliaP** [MelvorIdle/melvoridle.github.io#1742] opened 2021-11-19 22:12 UTC
### Describe the bug

A typical issue with questing - I accidentally completed the quest asking for a strung bow _before_ accepting the rewards for the bowstring quest, and now the bow quest isn't recognized and the shop says that buying another bow string is locked. I don't want to skip the rest of the tutorial, but nothing else seems an option.

### Reproduction Steps

1. Complete the bowstring quest but DO NOT accept the rewards
2. Go to Fletching and make both unstrung and strung bow (as is the logical next step)
3. Accept bowstring quest reward
4. Realize the strung bow quest is not completing
5. Attempt to buy another bowstring
6. Window stating 'this item is locked' appears

### Expected behaviour

1. Not allowing the bow to be made until after the bowstring quest is accepted
2. Accepting the presence of the made bow instead of requiring the process of making the bow.
3. Allowing the purchase of another bowstring.

### Screenshots

![image](https://user-images.githubusercontent.com/44490359/142697645-7c42bccb-8376-46b5-9fd7-20d33bc41f5e.png)

![image](https://user-images.githubusercontent.com/44490359/142697664-b58326d6-87d9-4ca1-adff-5f7470ab8bf2.png)

![image](https://user-images.githubusercontent.com/44490359/142697701-8ac877ab-2023-49ad-be63-09d78f7034b9.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (Android)
- [ ] Mobile App (iOS)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1342

### Are you using any scripts or extensions?

No

**Comment by ShyCakePrime** [comment] 2021-11-21 20:15
Same for me
Same info

**Comment by coolrox95** [comment] 2022-03-06 08:51
Duplicate of #1949

**Closed by coolrox95** 2022-03-06 08:51 UTC
Labels: bug, Duplicate
