### ISSUE TITLE
Offline Woodcutting mastery exp is still bugged in 0.18

### ISSUE THREAD

**Issue by Platmo** [MelvorIdle/melvoridle.github.io#557] opened 2020-12-20 07:28 UTC
**Describe the bug**
Using Multi-Tree with woodcutting and then going offline will only level mastery exp of one tree and not both. 

**To Reproduce**
With Multi-Tree select 2 trees to cut and then go offline. When going back online only one of them gets mastery exp. 
I used bird nest potions and the skillcape.

**Expected behavior**
Both trees should gain mastery exp and not just one. 

**Platform**
iOS

**Are you using any scripts?**
No.

**Comment by Charles445** [comment] 2020-12-21 16:52
Can confirm, this happened to me. It appears to be inconsistent - sometimes the mastery XP is gained for both, sometimes it isn't.
I have a save file where this bug is present.

Yew mastery's at 8057807 xp, Magic mastery's at 14854300 (I checked the json to get these exact values)

Upon importing, roughly 5500 of both logs are cut, but only Magic gains any significant mastery.
Yew gets roughly 2k, Magic gets around 2.7 mil...

Here's the save file if you would like to try it out. I hope this helps track down the cause.
[melvoridlesave_Charan_aah-prewc.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/5725461/melvoridlesave_Charan_aah-prewc.txt)

**Comment by Charles445** [comment] 2020-12-21 21:20
Hello, I believe I have solved it.

I believe this issue occurs when mastery tokens are found via the first tree, because when the tokens are found, they push themselves into slot 1 in the 'actions' array, preventing the second tree from being there.

Here's a picture me loading the same save file two different times. As you can see, the presence of tokens is probably the culprit.
![melvor_nomasterytokens](https://user-images.githubusercontent.com/1569981/102822700-2b490980-439f-11eb-90a6-6f7cf777da69.png)

**Comment by Delurielle** [comment] 2021-01-07 04:03
Still seems bugged in 0.18.2: 
![image](https://user-images.githubusercontent.com/9995464/103849578-15139c80-5073-11eb-95f6-e9dcbb1e9ace.png)

I should get 1194*2.8/0.6 = 5572 normal logs or so, but I got 3568. The mastery token is present, in line with the above report.

**Comment by MelvorIdle** [comment] 2021-02-17 03:07
I believe this was hotfixed. If not, it is confirmed fixed in v0.19

**Closed by MelvorIdle** 2021-02-17 03:07 UTC
Labels: bug
