### ISSUE TITLE
[Bug]: App Not Responding Continuously

### ISSUE THREAD

**Issue by devzspy** [MelvorIdle/melvoridle.github.io#3010] opened 2022-11-21 07:01 UTC
### Describe the bug

After opening the Android App and waiting a few short moments, the game presents an error "Melvor Idle isn't responding". This has been an issue with my Google Pixel 4 and Google Pixel 7.

Presented with the options:

1. Close app
2. Wait
3. Send Feedback

Selecting option 1 or 3 immediately closes the game. Option 2 (wait) will have the error temporarily go away before popping up again.

This can be done whether I am training a skill or sitting idly.

Despite clearing the cache, clearing storage, uninstalling/reinstalling the game, and logging out and back in this error still appears.

        Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.
        In the event this issue is still occurring, please open a new issue so we can address it.
        Originally posted by @MelvorIdle in https://github.com/MelvorIdle/melvoridle.github.io/issues/2594#issuecomment-1296569863_
      
https://github.com/MelvorIdle/melvoridle.github.io/issues/2594

Per Discord, the fix is to disable accessibility apps. This defeats the purpose of said apps and a user should not be forced to disable such apps in order to enjoy the game.

### Reproduction Steps

1. Open Melvor Idle
2. Begin training, or open a character with training in progress.
3. Navigate the app (look at bank tab, check another skill, check the shop, etc)
4. Pages typically take 3-5 seconds to accept user input (scrolling, tapping, etc)
5. Melvor Idle has stopped responding error pops up after a few minutes
6. Observe app still functioning (exp and drop notifications are still popping up, combat bars are still moving)
7. Select "wait"
8. Interact with app briefly
9. Error pops up again. Steps 7-9 can be repeated continuously and the app technically functions as usual.
10. Close app

### Expected behaviour

Close the app if it actually stopped working or if I select Wait in should in theory resolve itself if everything is working as expected.

### Save Link

https://melvoridle.com/save/NV8ZCBub

### Screenshots

![Screenshot_20221120-235317](https://user-images.githubusercontent.com/7217419/202984877-bbfb2e94-c66f-4a26-84e3-3362693ca641.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

Yes

**Comment by Mot92** [comment] 2022-11-22 18:06
#2958

**Comment by Mot92** [comment] 2022-11-22 18:06
#3015

**Comment by awdavis** [comment] 2022-12-01 12:55
See the developer response in https://github.com/MelvorIdle/melvoridle.github.io/issues/2671#issuecomment-1296619613.

Related issues / duplicates:
#2594
#2609
#2671
#2694
#2729
#2741
#2958
#3015

**Comment by coolrox95** [comment] 2023-03-25 22:41
Duplicate of #2694

**Closed by coolrox95** 2023-03-25 22:41 UTC
Labels: bug, Duplicate
