### ISSUE TITLE
[Bug]: Issue with save & " View Details " expansion button on the selection screen.

### ISSUE THREAD

**Issue by AAdlen** [MelvorIdle/melvoridle.github.io#4433] opened 2024-06-23 04:53 UTC
### Describe the bug

After clicking my local save, and confirm on the overwrite cloud save warning, i pressed " View Details " (Multiple times as it wouldn't open) on the Into the Abyss expansion while my save was loading up. When i arrived on the actual game, i saw on the offline progression that i earned 3 egg nests, i closed the offline progression menu too fast and thought maybe i saw wrong, because both my cloud save and local save were doing mining with gem glove offline. I also saw that i was doing woodcutting on a normal tree instead of mining. I thought maybe it was a bug that happened when i loaded the save, and i was only doing that for a few seconds but when i went to check my bank i had almost no gems. I am 100% certain that both my saves were doing " Mining since 22 minutes " as i saw it on the selection menu and i manually saved before closing the game to make sure i was doing that while offline and not something else. When i tried to do the bug again, i stumbled upon another bug instead, which made me unnable to interact with the game at all and i had to close and restart (This time the details window opened, and when i got into the game there was a " grey " filter on my game so i believe it's just the window not closing as the game loads)

### Reproduction Steps

1. Mining with gem glove
2. Manually save to cloud
3. Close the game
4. Open the game (~20 minutes later)
5. Click " Load local save " and confirm
6. While the game loads, click " view details " multiple times on the Into the Abyss expansion on the left

(I couldn't get it to work again but those are the steps i did when it happened)

### Expected behaviour

I believe the result would be to turn whatever action you were doing offline to " woodcutting normal tree ", including in the offline progress calculations. Perhaps because it's the default action or something like that

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/1ij6nJ3y

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/108336416/6d5af3c0-3efb-40c3-8072-0f57743e5e5b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11485

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-06-24 20:28
Duplicate of #4410

**Closed by coolrox95** 2024-06-24 20:28 UTC
Labels: bug, Duplicate
