### ISSUE TITLE
[Bug]: Upgrades showing that I don't have when starting the game. 

### ISSUE THREAD

**Issue by MikeG-BE** [MelvorIdle/melvoridle.github.io#2312] opened 2022-03-09 10:26 UTC
### Describe the bug

I have 4 upgrades showing in the sidebar that I don't have when I open the game.

Perpetual Haste
Expanded knowledge
Master of Nature
Art of Control

When I switch tabs and reopen the sidebar they are gone.

### Reproduction Steps

Close the app.
Restart the app

### Screenshots

![Screenshot_20220309-110851__01__01](https://user-images.githubusercontent.com/101254779/157421415-114e1fdd-4ee8-4176-9ec6-ec85117ac01c.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1843

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-09 17:14
Duplicate of #2243

**Closed by coolrox95** 2022-03-09 17:14 UTC
Labels: bug, Duplicate
