### ISSUE TITLE
[Spelling/Grammar]: Mastery Token Astrology not following naming convention

### ISSUE THREAD

**Issue by AevitasDragonkin** [MelvorIdle/melvoridle.github.io#2011] opened 2022-01-02 17:00 UTC
### What text is wrong?

Mastery Token Astrology doesn't seem to follow the same naming as the other token, which have their skill listed in between brackets.

![image](https://user-images.githubusercontent.com/77356760/147883299-3395ae79-83e4-4a8b-af7f-0d5fd248115a.png)

### What is the correct spelling or grammar?

Mastery Token (Astrology)

**Comment by mturchik** [comment] 2022-02-09 01:01
Still existing as of 2/8/22. Item name is missing the parenthesis around the skill, and does not have a similar item description to other mastery tokens
![image](https://user-images.githubusercontent.com/46897798/153101586-5b40f074-67ae-4613-a0d8-00a74aba6ba0.png)
![image](https://user-images.githubusercontent.com/46897798/153101745-5f6dfe98-ae18-4216-95bd-aaaf282f010f.png)

This was also logged with issue #1967

**Comment by coolrox95** [comment] 2022-03-09 18:03
Duplicate of #1967

**Closed by coolrox95** 2022-03-09 18:03 UTC
Labels: Duplicate, spelling/grammar
