### ISSUE TITLE
Game not loading, flashing red M

### ISSUE THREAD

**Issue by scriptsforweirdos** [MelvorIdle/melvoridle.github.io#613] opened 2021-01-06 12:41 UTC
**Describe the bug**
The game isn't loading today. Getting a flashing red M and no account selection options.

**To Reproduce**
1. Go to melvoridle.com in Chrome.
2. Wait.

**Expected behavior**
Login screen appears

**Browser**
Chrome 87.0.4280.88. Tried with ublock on and off, still same problem.

**Console output**
```
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
(index):10731 GET https://cdn.melvor.net/core/v018/assets/media/shop/assets/media/shop/perpetual_haste.svg 403 (Forbidden)
main.js?632:242 null
main.js?632:247 Uncaught TypeError: Cannot read property 'skill' of null
    at createCharacterSelectionBox (main.js?632:247)
    at processLocalCharacters (main.js?632:257)
    at loadCharacterSelection (main.js?632:240)
    at onloadEvent (save.js?632:59)
    at window.onload (save.js?632:61)
```

**Are you using any scripts?**
SEMI, tried turning that off too, no difference.

**Comment by ByteDigital123** [comment] 2021-01-06 15:07
Describe the bug
This is the same on the IOS version

To Reproduce
Steps to reproduce the behavior:

1. Open App
2. See screen which tells me that the game is in alpha
3. click on the "'m fine with this" button;
4. Game loads into the last task I was doing, and then reloads back to the login screen

I am not logged into the game, I am using a guest account.

**Comment by scriptsforweirdos** [comment] 2021-01-06 17:27
I don't even get to the screen that tells me the game is in alpha.

**Comment by Whitepawn016** [comment] 2021-01-06 23:18
**Describe the bug**
I'm having the same issue but on desktop. Still after multiple reinstalls.

**To Reproduce**
Steps to reproduce the behavior:

1. Open App

**Comment by MelvorIdle** [comment] 2021-01-07 04:46
Please confirm if you can get into the game now. Thanks

**Comment by scriptsforweirdos** [comment] 2021-01-07 13:44
Worked for me, not sure about the rest. Thank you.

**Comment by Whitepawn016** [comment] 2021-01-07 14:34
Still stuck on the steam version.

**Comment by Wolrek** [comment] 2021-01-13 17:09
**Describe the bug**
Also stuck on the Steam version as well since yesterday: I lost my hardcore character, clicked to create another one in its place in the character screen, and closed the game before finishing creating it. After this, every time I try to start the game, I get the flashing red M and nothing happens. There's nothing else on the screen.

The game loads properly in Firefox, Chrome, and Android. My cloud save files still exist. This issue only happens with Steam.

I tried to reinstall the game, but the issue is still there. Verifying the integrity of the game files didn't help either. I also tried the "fix my saves" button when playing in a browser, but the game still won't start properly in Steam.

I guess my Steam local saves are corrupted or something, but I have no clue how to delete them, I don't know where they are.

Also, not sure this is related, but I noticed Steam keeps thinking I'm running the game after I closed it. I can't see any running process related to Melvor, and I have to stop and restart Steam so it finally understands I quit the game. Clicking the "Stop" button on the game page doesn't do anything.

**Comment by Wolrek** [comment] 2021-01-15 23:43
Alright, finally found a way to fix this: I renamed the Melvor Idle folder in AppData/Local so the game wouldn't find it, then started the game in Steam, and it worked.
I had to manually export the cloud saves using a web browser though, because Steam somehow kept showing old versions of my cloud files, but that's a different issue.

**Comment by MelvorIdle** [comment] 2021-02-17 02:09
I believe the new upcoming update eliminates this issue entirely

**Closed by MelvorIdle** 2021-02-17 02:09 UTC
Labels: bug
