### ISSUE TITLE
[Bug]:  apple pie needs an "upgrade" button for the hard task

### ISSUE THREAD

**Issue by l3vines** [MelvorIdle/melvoridle.github.io#2734] opened 2022-10-21 05:30 UTC
### Describe the bug

apple pie needs an "upgrade" button for the hard task

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4501

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2023-03-24 20:49
Duplicate of  #2684

**Closed by coolrox95** 2023-03-24 20:49 UTC
Labels: bug, Duplicate
