### ISSUE TITLE
[Bug]: <title> township legacy time bug

### ISSUE THREAD

**Issue by kaladinstorms** [MelvorIdle/melvoridle.github.io#3503] opened 2023-07-20 01:08 UTC
### Describe the bug

When legacy time isn’t an even hour, the township can no longer be used. No time is accrued, and it can no longer be used for gathering 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

6124

### Are you using any mods?

No

**Comment by DavidDeArmon** [comment] 2023-08-19 17:25
I have the same issue on Android and Steam. I have 30m of Legacy Time Remaining but because it is lower than 1h, I cant update to remove the remaining time.
![MelvorTownshipTimeBug](https://github.com/MelvorIdle/melvoridle.github.io/assets/42128109/1aa9ba16-8bec-4e95-8f61-8c61778f44f6)

**Comment by coolrox95** [comment] 2023-08-26 16:02
Duplicate of #3388

**Closed by coolrox95** 2023-08-26 16:02 UTC
Labels: bug, Duplicate
