### ISSUE TITLE
[Bug]: Stuck in stunned state

### ISSUE THREAD

**Issue by bdpt** [MelvorIdle/melvoridle.github.io#3000] opened 2022-11-18 12:45 UTC
### Describe the bug

Character is permanently stunned, cannot stop thieving or start any other task, cannot recover from stunned state

### Reproduction Steps

Using the Desktop client and thieving, thieving tab open:
- Receive an error message for Android (clear app cache; not sure if error was related to misbehaviour) 
- Close error message
- see Bug

### Expected behaviour

Thieving ticks continue, character recovers from stun with next thieving tick. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

? 4908

### Are you using any mods?

Yes

**Comment by bdpt** [comment] 2022-11-18 12:46
![IMG_20221118_134603](https://user-images.githubusercontent.com/31648431/202708192-1389c2f0-ba32-4639-ac32-efef97f17924.jpg)

**Comment by bdpt** [comment] 2022-11-18 12:47
![IMG_20221118_134713](https://user-images.githubusercontent.com/31648431/202708427-e2cbe7bf-54bf-4734-8301-6a2413d591bb.jpg)

**Comment by coolrox95** [comment] 2023-03-25 22:56
Duplicate of #2912

**Closed by coolrox95** 2023-03-25 22:56 UTC
Labels: bug, Duplicate
