### ISSUE TITLE
[Bug]: Duplication of Elite Pillar in Agility

### ISSUE THREAD

**Issue by Razorflamekun** [MelvorIdle/melvoridle.github.io#3146] opened 2023-01-06 15:47 UTC
### Describe the bug

When I rebuilt my skilling agility course from my skilling blueprint, after going down to the bottom of the page, I noticed that my Elite Pillar didn't update, so I went ahead and bought it again.

Later on, I went back to the Agility skill to change some obstacles around and noticed that the Elite Pillar had replaced my Standard Pillar in the Agility Course layout.

![image](https://user-images.githubusercontent.com/53189811/211046518-6c9edf75-2d24-4172-99ea-93a0817eee85.png)

I have no idea how this happened.

### Reproduction Steps

1. Open Melvor Idle and go to Agility.
2. Open the "Load Blueprint" box in the Agility Course overlay.
3. Click on the desired Agility Course Blueprint.
4. Check to see that the Elite Pillar duplicated over the Standard Pillar.

### Expected behaviour

The expected behavior for this problem is that both the Standard Pillar and Elite Pillar will be built instead of the Elite Pillar overwriting the Standard Pillar.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5023

### Are you using any mods?

No

**Comment by Razorflamekun** [comment] 2023-01-06 15:48
Please let me know if you would like my save file.  I didn't want to include it because I would like to keep it private, if possible.

**Comment by Razorflamekun** [comment] 2023-01-06 16:18
https://github.com/MelvorIdle/melvoridle.github.io/issues/3081 .  This also happened to this user.

**Comment by coolrox95** [comment] 2023-03-25 06:34
Duplicate of #3081

**Closed by coolrox95** 2023-03-25 06:34 UTC
Labels: Duplicate
