### ISSUE TITLE
Crash on Initializing Save

### ISSUE THREAD

**Issue by Legitosity** [MelvorIdle/melvoridle.github.io#1403] opened 2021-09-30 15:19 UTC
**Describe the bug**
I opened my steam client and when I clicked on my save the game hung in the main menu screen with the circle spinning. I closed my client after about 3 minutes and when I opened the client again I received the error down below.

The fix save button worked for me so I'm back in game. Currently I'm on Alpha V0.22 (?1176) and I don't think I updated in between crashes.

**To Reproduce**

**Expected behavior**
Open steam client, click adventure save, game works normally.

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at l.e.init (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:211412)
    at new l (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:210695)
    at updateWindow (https://steam.melvoridle.com/assets/js/game/main.js?1176:1:14197)
    at finaliseLoad (https://steam.melvoridle.com/assets/js/game/main.js?1176:341:1)
    at selectCharacter (https://steam.melvoridle.com/assets/js/game/main.js?1176:331:223)
    at onloadEvent (https://steam.melvoridle.com/assets/js/game/save.js?1176:60:267)
    at https://steam.melvoridle.com/assets/js/game/save.js?1176:64:121

**Are you using any scripts?**
None

**Comment by coolrox95** [comment] 2021-10-03 08:09
Duplicate of #1392

**Closed by coolrox95** 2021-10-03 08:09 UTC
Labels: Duplicate
