### ISSUE TITLE
[Bug]: Clicking "Show All" button in Item Completion Log does not show all items

### ISSUE THREAD

**Issue by samlawix** [MelvorIdle/melvoridle.github.io#2103] opened 2022-01-26 09:01 UTC
### Describe the bug

Clicking the "Show All" button in item completion log will hide those items which does not count towards completion from the list

### Reproduction Steps

1. Go to "Completion Log"
2. Go to "Items"
3. Click "Show All"

### Expected behaviour

The list should show all items, but instead items that does not count towards completion will be hidden

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-09 04:02
Duplicate of #2148

**Closed by coolrox95** 2022-03-09 04:02 UTC
Labels: bug, Duplicate
