### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by SosukeAizen** [MelvorIdle/melvoridle.github.io#547] opened 2020-12-17 13:18 UTC
**Describe the bug**
Left the steam version open all night doing fetching, and I came back to the game using 18gb of memory.

**To Reproduce**
Probably just leave the game open for a while.

**Expected behavior**
Game should be using a lot more memory than usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/15948761/102492660-ebfe7e00-4069-11eb-86a3-fdcf37dd2dee.png)

**Browser**
Steam Alpha v0.18

**Console output**
F12 doesn't seem to work for steam version. 

**Are you using any scripts?**
No Scripts.

**Comment by MelvorIdle** [comment] 2020-12-18 02:22
Going to need more information on this one.

What skill were you training?
Is it in Combat? What were you fighting?
When is the last time the game was closed/restarted?

Also, verify the game files through Steam to make sure nothing has been missed.

All this will help find the source :)

**Comment by SosukeAizen** [comment] 2020-12-19 16:14
I was training fletching doing dragon javelins, unsure when the last time i closed the game was a week maybe two. 
Verifying the game game up all good.

**Comment by Teraphina** [comment] 2020-12-27 15:40
woke up this morning with 39 gigs of ram being used by melvor steam edition. i wana say i was cooking lobster but that should have only taken a few hours so was actually not doing anything when i woke up

**Comment by jttheghost** [comment] 2021-02-24 21:40
I've encountered this too, over the course of several days of leaving the game open while playing will continue to eat memory until it crashes. Standard play for me currently is 1 normal 2 hc characters swapping, normal char is in combat, fishing or cooking while woodcutting on 1 hardcore and mining on the other. There is no clear indication where the leak is coming from, as watching for several minutes will see no ram creep.

I'll try to pay more attention to increase the detail around the leak

**Comment by jttheghost** [comment] 2021-02-25 04:36
> I've encountered this too, over the course of several days of leaving the game open while playing will continue to eat memory until it crashes. Standard play for me currently is 1 normal 2 hc characters swapping, normal char is in combat, fishing or cooking while woodcutting on 1 hardcore and mining on the other. There is no clear indication where the leak is coming from, as watching for several minutes will see no ram creep.
> 
> I'll try to pay more attention to increase the detail around the leak

Note this is in the steam version as well.

After about 7 hours (since my last comment) the game is up about 500 MB in ram usage 90% of this was combat on my normal account with only 3 total account switches, and then moving into mining. I was also farming occasionally during this time.

![image](https://user-images.githubusercontent.com/28493765/109103588-2aaf5500-76f9-11eb-9069-a2fe76a14ff7.png)

**Comment by MelvorIdle** [comment] 2021-02-25 06:06
> > I've encountered this too, over the course of several days of leaving the game open while playing will continue to eat memory until it crashes. Standard play for me currently is 1 normal 2 hc characters swapping, normal char is in combat, fishing or cooking while woodcutting on 1 hardcore and mining on the other. There is no clear indication where the leak is coming from, as watching for several minutes will see no ram creep.
> > I'll try to pay more attention to increase the detail around the leak
> 
> Note this is in the steam version as well.
> 
> After about 7 hours (since my last comment) the game is up about 500 MB in ram usage 90% of this was combat on my normal account with only 3 total account switches, and then moving into mining. I was also farming occasionally during this time.
> 
> ![image](https://user-images.githubusercontent.com/28493765/109103588-2aaf5500-76f9-11eb-9069-a2fe76a14ff7.png)

I have reason to believe that this may be caused by the Steam Achievements API call that is made every 10 seconds.

In the next update, I will be adding an option to disable this call which players can test to see if memory leaks stop occurring.

**Comment by tristo7** [comment] 2021-03-05 20:11
Didn't experience this before v0.19, but I am experiencing it now.

**Comment by MelvorIdle** [comment] 2021-08-13 07:42
Fixed in Alpha v0.21

**Closed by MelvorIdle** 2021-08-13 07:42 UTC
Labels: bug
