### ISSUE TITLE
[Bug]: Golbin "Raid History" displays incorrect amount of coins

### ISSUE THREAD

**Issue by xanderput** [MelvorIdle/melvoridle.github.io#2100] opened 2022-01-24 15:26 UTC
### Describe the bug

In the "Raid History" it displays an incorrect amount of coins. It's off by about a factor of 1000.

### Reproduction Steps

1. Do golbin raid
2. Die 
3. Check how many raid coins you got
4. Check amount of raid coins in raid history
5. Notice theyre not the same

### Screenshots

As you can see in this screenshot it says I only earned 758 raid coins for 241 waves. In reality I earned about 758,000 raid coins.

![image](https://user-images.githubusercontent.com/39944140/150811519-b9e6472a-54f6-4899-a0fe-2b3fc96ab5a7.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-01-30 05:31
Duplicate of #2071

**Closed by coolrox95** 2022-01-30 05:31 UTC
Labels: bug, Duplicate
