### ISSUE TITLE
[Bug]: Cannot purchase bank slots. All "amounts" say 0.

### ISSUE THREAD

**Issue by DerkDirkDerkinson** [MelvorIdle/melvoridle.github.io#2407] opened 2022-04-17 09:23 UTC
### Describe the bug

All purchase amounts say "0". This still works okay when buying any quantity of items, but for the blank slots it says "Buy limit of 88 reached", meaning I cannot buy anymore. This bug has been here for about a week now.

### Save Link

https://melvoridle.com/save/7dPmy2U2

### Screenshots

![image](https://user-images.githubusercontent.com/103879667/163708507-cbfedfab-626c-4352-bdb5-546160750c32.png)

![image](https://user-images.githubusercontent.com/103879667/163708527-8b9514ec-46e9-4aba-875e-3cd41c89c548.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by TerraSleet** [comment] 2022-04-17 12:16
Are you using a Hardcore character? If so this is not a bug. Also, duplicate of https://github.com/MelvorIdle/melvoridle.github.io/issues/2403

**Closed** 2022-05-25 01:42 UTC
Labels: bug
