### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by DorkyPanda** [MelvorIdle/melvoridle.github.io#3551] opened 2023-08-28 16:58 UTC
### Describe the bug

Game won’t load, says it’s broken now

### Reproduction Steps

addNonShardCosts@https://ios.melvoridle.com/assets/js/built/summoning.js:68:113
getAltRecipeCosts@https://ios.melvoridle.com/assets/js/built/summoning.js:73:22
renderSelectedRecipe@https://ios.melvoridle.com/assets/js/built/artisanSkill.js:33:187
renderSelectedRecipe@https://ios.melvoridle.com/assets/js/built/summoning.js:81:27
render@https://ios.melvoridle.com/assets/js/built/artisanSkill.js:21:35
render@https://ios.melvoridle.com/assets/js/built/summoning.js:71:22
onLoad@https://ios.melvoridle.com/assets/js/built/artisanSkill.js:14:12
onLoad@https://ios.melvoridle.com/assets/js/built/summoning.js:69:22
@https://ios.melvoridle.com/assets/js/built/game.js:172:71
forEach@[native code]
forEach@https://ios.melvoridle.com/assets/js/built/namespaceRegistry.js:38:51
onLoad@https://ios.melvoridle.com/assets/js/built/game.js:172:48
@https://ios.melvoridle.com/assets/js/built/main.js:9:195
@https://ios.melvoridle.com/assets/js/built/language.js:5:62
Promise@[native code]
@https://ios.melvoridle.com/assets/js/built/language.js:2:27
@https://ios.melvoridle.com/assets/js/built/main.js:75:93
@https://ios.melvoridle.com/assets/js/built/language.js:5:62
Promise@[native code]
@https://ios.melvoridle.com/assets/js/built/language.js:2:27
@https://ios.melvoridle.com/assets/js/built/save.js:137:15
fulfilled@https://ios.melvoridle.com/assets/js/built/language.js:2:102

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/D1kR5Xqr

### Screenshots

![IMG_6592](https://github.com/MelvorIdle/melvoridle.github.io/assets/143420383/5d3b6513-15af-4b1f-9e94-21466b16caba)
![IMG_6591](https://github.com/MelvorIdle/melvoridle.github.io/assets/143420383/bfc48620-bc75-475f-aaec-7a71070b92cb)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?

### Are you using any mods?

Yes

**Comment by 04Slash** [comment] 2023-08-29 10:01
This is caused by having summoning recipes from the mod "Expansion Summoning Recipes" selected and uninstalling said mod.

You should be able to fix this by installing the mod, making sure all summoning recipes are base-game recipes and not modded recipes, then you can uninstall the mod afterwards.

**Comment by coolrox95** [comment] 2023-09-04 16:26
Issue has been fixed as of v1.2,

**Closed by coolrox95** 2023-09-04 16:26 UTC
Labels: bug
