### ISSUE TITLE
[Bug]: Skilling Minibar hover tooltip clips off screen on Steam

### ISSUE THREAD

**Issue by AntiTcb** [MelvorIdle/melvoridle.github.io#1683] opened 2021-11-13 22:40 UTC
### Describe the bug

When mousing over the icons on the Skilling Minibar on the Steam App, the hover tooltip appears to the right of the cursor, causing a horizontal scroll bar to appear and the tooltip is unable to be seen. The page however cannot be scrolled as any other action will cause the tooltip to disappear again, removing the extra horizontal space and the scroll bar as a result.

### Reproduction Steps

1. Have the Skilling Minibar enabled
2. Open the game on Steam
3. Mouse over any icon.

### Expected behaviour

This probably should have the tooltip appear on the left of the cursor, using the bottom right of the tooltip container as the origin, so that it takes up the existing screen space instead of causing more horizontal space to be necessary.

### Screenshots

![vQDz3HUAFb](https://user-images.githubusercontent.com/4700391/141661042-1812cf20-c9f3-4cb4-b683-545f0ae92501.gif)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1262

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2021-11-14 00:07
Duplicate of #1681

**Closed by coolrox95** 2021-11-14 00:07 UTC
Labels: Duplicate
