### ISSUE TITLE
[Bug]: I can read the main storyline books in portuguese since the v1 update

### ISSUE THREAD

**Issue by VictordeQuadros** [MelvorIdle/melvoridle.github.io#2997] opened 2022-11-18 03:19 UTC
### Describe the bug

I try o read the book: The First Hero and an Unknown Evil when I deafead Ragnar, then i try to read the first one to see if it was a bug of not and I can't too.

### Reproduction Steps

1. Click to read the book

### Expected behaviour

Open the book

### Screenshots

![image](https://user-images.githubusercontent.com/59742454/202609046-9b40e8a7-f9da-456a-87cf-cf6cd55d7060.png)

### Console output

Nothing

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-12-21 00:36
Duplicate of #2783

**Closed by coolrox95** 2022-12-21 00:36 UTC
Labels: bug, Duplicate
