### ISSUE TITLE
[Bug]: Unable to grow herbs and trees

### ISSUE THREAD

**Issue by moker888** [MelvorIdle/melvoridle.github.io#2708] opened 2022-10-20 13:30 UTC
### Describe the bug

After the update, I can't grow herbs and trees, I don't know how this exception happened, please help me to fix the exception, thanks.

### Reproduction Steps

no real steps to get the bug to happen

### Expected behaviour

I expect to be able to harvest  herbs  trees ,and plant again.

### Save Link

https://melvoridle.com/save/ydBX4xP6

### Screenshots

![image](https://user-images.githubusercontent.com/116283332/196960585-945e20ae-cf03-4d04-a75b-11da94067481.png)
![image](https://user-images.githubusercontent.com/116283332/196960659-40b14de6-2963-4d1d-85d7-679676620038.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4481

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-10-21 04:51
Duplicate of #2693

**Closed by coolrox95** 2022-10-21 04:51 UTC
Labels: bug, Duplicate
