### ISSUE TITLE
[Bug]: Tutorial Task -Magic Preparation 4

### ISSUE THREAD

**Issue by SustainableBlueDuck** [MelvorIdle/melvoridle.github.io#1620] opened 2021-11-11 09:03 UTC
### Describe the bug

The task is: Kill 1 <golblin> using **magic**, however the task is also completed when killing a golblin with range (probably also with melee?).

### Reproduction Steps

1. be at Task -Magic Preparation 4
2. kill **not** using magic
3. task completed

### Expected behaviour

Only compleet task when using magic.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1272

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment] 2021-11-12 01:03
Fix has been applied to the game

**Closed by MelvorIdle** 2021-11-12 01:03 UTC
Labels: bug, In Progress

**Comment by Hellscaretaker** [comment] 2021-11-12 13:43
This bug still not fixed. Still using ranged

**Comment by MelvorIdle** [comment] 2021-11-12 13:57
I just ran through the tutorial again and confirmed it is working as intended. What are you seeing at the moment for it to not be working?

**Comment by Hellscaretaker** [comment] 2021-11-12 14:13
On ios, i had my wand in my hand.... i killed the goblin a few times but it did not register untill i changed to ranged wepon and as soon as i did that..it then register i killed the goblin. On the steam save it worked the oppsite way and needed the wand to kill the goblin.
