### ISSUE TITLE
Using spells unlocked in golbin raid in normal combat. 

### ISSUE THREAD

**Issue by Gorannilssen** [MelvorIdle/melvoridle.github.io#1099] opened 2021-06-29 20:57 UTC
**Describe the bug**
Able to use the last magic spell used in golbin raid in regular combat afterwards. 

**To Reproduce**
Happend 2/2 times when i left golbin raid using magic and able to use the spell last used, can use fire strike at lvl one, can also use anchient spell frostbite at lvl 8 but dont have the runes. 

**Expected behavior**
Not being able to use spells i havent got the level for or unlocked. 

**Screenshots**

**Browser**
Google chrome v.20 949

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Works without any scripts.

**Comment by coolrox95** [comment] 2021-08-15 07:30
Duplicate of #494

**Closed by coolrox95** 2021-08-15 07:30 UTC
Labels: Duplicate
