### ISSUE TITLE
[Bug]: <title> Potato's in my tree farming patch

### ISSUE THREAD

**Issue by Inferxan** [MelvorIdle/melvoridle.github.io#3088] opened 2022-12-12 21:30 UTC
### Describe the bug

When I tried starting Melvor on my mobile earlier today. it had trouble loading the DLC. It unequiped alot of my dlc items and some not. I just rebooted and it was fixed but now in my tree farming patch the last 2 patches grown potato's instead of tree and I cannot plant in any of the other patches.

### Reproduction Steps

no idea how I just always used harvest all, apply gloop to all and plant all selected which was set to apple trees and suddenly I saw this.

### Expected behaviour

to be able to grow in all my tree patches and have it be actual trees.

### Save Link

https://melvoridle.com/save/2zNMpFeb

### Screenshots

![index](https://user-images.githubusercontent.com/120422548/207158125-e52318ab-ecf3-46a6-9d6b-0b74173988b3.jpg)

### Console output

didnt allow me to copy

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 06:19
Duplicate of #2809

**Closed by coolrox95** 2023-03-25 06:19 UTC
Labels: bug, Duplicate
