### ISSUE TITLE
[Bug]: Cyclops/Spider synergy doesn't work

### ISSUE THREAD

**Issue by Rackius** [MelvorIdle/melvoridle.github.io#3184] opened 2023-01-24 15:48 UTC
### Describe the bug

Same as title

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2023-03-25 08:45
Duplicate of #3123

**Closed by coolrox95** 2023-03-25 08:45 UTC
Labels: bug, Duplicate
