### ISSUE TITLE
[Bug]: Switching equipment when using Big ol Ron will invalidate the gain value

### ISSUE THREAD

**Issue by Yukino-Stuki** [MelvorIdle/melvoridle.github.io#3457] opened 2023-06-15 12:57 UTC
### Describe the bug

The Big ol Ron will give us a Damage Reduction based on the enemy's health. When I enter the battle, I will receive this gain value, but if I switch any equipment during the battle, it will cause the gain value to become invalid. And when exiting the battle, the gain value will still be subtracted from the existing damage reduction value based on the previous gain value.

### Reproduction Steps

1. Take the Big ol Ron. Due to factors Agility and Pets, I have a 3% DR.
2. Fight monsters over 2000 hp.(For example, Venomous Snake in Toxic Swamps),
3. Because of the gain value of Big ol Ron, I have a 4% DR at this time.
4. At this time I equip any item or switch any equipment(like use Mark of the Ent or other equipment).
5. The gain value will be invalidated.(4% -> 3%)
6. When exiting the battle, the gain obtained from Big ol Ron will be deducted again.(3% -> 2%)
7. The gain value that was incorrectly deducted will continue to exist until I switch equipment outside the battle.(always 2%)

### Expected behaviour

Unloading items during normal combat should not deduct the gain value of Big ol Ron, and the gain value should not be deducted again when exiting the battle.

### Screenshots

1.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/85859920/7542f45d-7037-42be-a3fd-e38ec81559de)
2.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/85859920/9e3417d9-18ff-4184-a4c7-8da9f06002d4)
3.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/85859920/26aa583f-7c24-42d7-9a9e-8d98a334c36d)
4.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/85859920/9ca9b42c-0da7-48ec-85f9-7db1b241c71e)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

6062

### Are you using any mods?

No

**Comment by Hemerocalle** [comment] 2023-06-15 14:14
There is another way to reproduce it.
1. At first, I have 3% DR because of agility and pets. And I'm not using any equipment.
2. Then combat with Venomous Snake. At this time, I've 3% DR(of course).
3. Pick the BigRon up. At this time, I've also 3% DR(should be 4%).
4. Leave the combat. At this time, I've only 2% DR now(should be 3%).
5. Combat with plant(or do anything). Then I will see I did lost 1% DR forever, until I put on any equipment(or repick BigRon) outside of combat.
I think maybe if I swap the equipment in the combat, this modifier will be lost. I'm not sure if other modifiers of BigRon have the same bug because they are difficult to test.

**Comment by coolrox95** [comment] 2023-08-26 16:31
Duplicate of #3254

**Closed by coolrox95** 2023-08-26 16:31 UTC
Labels: bug, Duplicate
