### ISSUE TITLE
Rags to Riches 2 don't get unlocked at Alt Magic LvL 70

### ISSUE THREAD

**Issue by alimgiray** [MelvorIdle/melvoridle.github.io#1281] opened 2021-08-27 03:59 UTC
Left Alt-Magic to offline training. It went from 65~to 70 in the night, but Rags To Riches didn't get unlocked. 

I don't know if it is relevant or not but it was training with Blessed Offering.

But it did get unlocked after restarting the game.

**Comment by coolrox95** [comment] 2021-09-13 00:24
Duplicate of #1312

**Closed by coolrox95** 2021-09-13 00:24 UTC
Labels: Duplicate
