### ISSUE TITLE
[Bug]: abyssal herblore 95% mastery checkpoint not applying

### ISSUE THREAD

**Issue by professorcft** [MelvorIdle/melvoridle.github.io#4560] opened 2024-08-05 23:18 UTC
### Describe the bug

The 95% checkpoint for Herblore in Abyssal mastery doesn't apply to any options.
![Screenshot_20240806-091151](https://github.com/user-attachments/assets/ad422a0d-2b38-45f2-b8b2-a6e6ec7762be)
![Screenshot_20240806-091126](https://github.com/user-attachments/assets/9e496b41-d721-4c96-89f7-3e544ade77ab)

### Reproduction Steps

1. Get 95% abyssal herblore
2. Turn on an abyssal potion
3. Charges are not increased by 4

### Expected behaviour

Charges are expected to be 4 higher

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

11585

### Are you using any mods?

No

**Comment by MelvorIdle** [comment] 2024-08-09 04:17
Duplicate of #4510

**Closed by MelvorIdle** 2024-08-09 04:17 UTC
Labels: bug
