### ISSUE TITLE
[Bug]: Permanently stunned Thieving the Sage

### ISSUE THREAD

**Issue by Jenesaar** [MelvorIdle/melvoridle.github.io#2723] opened 2022-10-20 22:56 UTC
### Describe the bug

In the Thieving skill my character thinks it is permanently stunned thieving the Sage.  I have clicked the "stop thieving" only to get the "you cant do that while stunned" message.  I can train any other skill no problem, however, I cannot thieve any of the NPC's, again because it thinks I am currently stunned thieving the Sage. 

I was Thieving the Sage before switching over to combat for a while to farm some new herb seeds.  When I tried to go back to Thieving is when I immediately could see the bug.   I am now currently training Astrology since I cannot Thieve.

### Reproduction Steps

1. Thieve Sage
2. Switch to combat
3. Try to switch back to thieving

### Expected behaviour

I expected to go from training thieving, to combat and back to training thieving again.  

### Screenshots

![Screenshot 2022-10-20 155222](https://user-images.githubusercontent.com/116317238/197074052-8f4e27e0-9441-428e-a8a0-2490e54dd666.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by ValentinNYC** [comment] 2022-10-21 00:03
Same as I reported yesterday.
Hope it will be fixed

**Comment by monarsan** [comment] 2022-10-21 00:50
I also face it, but I haven't unlocked sage yet. 
Maybe Thiving Necromancer also cause it.

**Comment by coolrox95** [comment] 2022-10-21 04:49
Duplicate of #2682

**Closed by coolrox95** 2022-10-21 04:49 UTC
Labels: bug, Duplicate

**Comment by coolrox95** [comment] 2022-10-23 00:19
Hello, if you are able to could you generate a save link and respond with it? Would greatly assist in trying to source this issue.
Instructions for generating a save link can be found [here.](https://github.com/MelvorIdle/melvoridle.github.io/wiki/How-to-Create-a-Save-Link )

**Comment by ValentinNYC** [comment] 2022-10-23 00:22
Here you go
https://melvoridle.com/save/fzxsoRye
