### ISSUE TITLE
[Bug]: Offline combat paused during goblin raid

### ISSUE THREAD

**Issue by IsaacGraham** [MelvorIdle/melvoridle.github.io#1551] opened 2021-11-02 18:09 UTC
### Describe the bug

I read that the raid lets you continue making progress while you play it, but I found that after 5 hours in the raid I had made no progress outside of it.

I had my character set to kill regular goblins, and this continued once the raid ended.
I have offline combat enabled on this character.

Note this is on v0.22.1?1209, which isn't selectable below.

### Reproduction Steps

1. Enable offline combat
2. Begin a combat session that you expect to survive long-term
3. Play through a raid

### Expected behaviour

Expected to see the results of offline progress i.e combat exp gained, bones in loot window, 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2021-11-02 20:32
Duplicate of  #1427

**Closed by coolrox95** 2021-11-02 20:32 UTC
Labels: Duplicate
