### ISSUE TITLE
[Bug]: <title> error occurred while rendering

### ISSUE THREAD

**Issue by Slippy95** [MelvorIdle/melvoridle.github.io#3207] opened 2023-02-08 16:53 UTC
### Describe the bug

I deleted the cargo net obstacle and it gave me this error. It will not go away even after deleting and re installing the app, loading the game on browser and deleting local save data and re-downloading from cloud saves. 

### Expected behaviour

I expected to be able to delete the cargo net and replace it with another obstacle.

### Save Link

https://melvoridle.com/save/z8dOeogP

### Screenshots

![9A36BA6C-0CE4-44DB-AF18-1F4AF3228D75](https://user-images.githubusercontent.com/124804620/217583736-3a8f9333-b03a-40af-8522-023e150589fb.png)

### Console output

An error occurred while rendering:
Active Action: undefined
Error Name: Error
Error Message: Tried to get active obstacle, but none is built.
Stack Trace:
activeObstacle@https://ios.melvoridle.com/assets/js/built/agility.js?5047:27:16
getGPModifier@https://ios.melvoridle.com/assets/js/built/agility.js?5047:52:248
getObstacleGP@https://ios.melvoridle.com/assets/js/built/agility.js?5047:59:82
renderCourseRates@https://ios.melvoridle.com/assets/js/built/agility.js?5047:138:371
render@https://ios.melvoridle.com/assets/js/built/agility.js?5047:136:75
@https://ios.melvoridle.com/assets/js/built/game.js?5047:180:69
forEach@[native code]
forEach@https://ios.melvoridle.com/assets/js/built/namespaceRegistry.js?5047:37:51
render@https://ios.melvoridle.com/assets/js/built/game.js?5047:180:46
loop@https://ios.melvoridle.com/assets/js/built/game.js?5047:196:41
loop@[native code]
Current Equipment:
Helmet: melvorD:Crown_of_Rhaelyx
Platebody: melvorF:Ancient_Dhide_Body_U
Platelegs: melvorF:Aeris_God_Platelegs
Boots: melvorF:Aeris_God_Boots
Weapon: melvorF:Ancient_Crossbow
Shield: melvorF:Scaled_Shield
Amulet: melvorD:Elite_Amulet_of_Ranged
Ring: melvorF:Silver_Diamond_Ring
Gloves: melvorF:Aeris_God_Gloves
Cape: melvorF:Infernal_Cape

No Active Action Information

Modding Enabled. Loaded mods:
Dev

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5047

### Are you using any mods?

Yes

**Comment by Slippy95** [comment] 2023-02-08 17:07
I was fletching diamond bolts when i deleted the obstacle.

**Comment by coolrox95** [comment] 2023-03-25 06:46
Duplicate of #3190

**Closed by coolrox95** 2023-03-25 06:46 UTC
Labels: bug, Duplicate
