### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by kuratowakiru** [MelvorIdle/melvoridle.github.io#2702] opened 2022-10-20 05:18 UTC
### Describe the bug

putting a bow in the off hand quick equip make it only equip the bow in the off hand slow, main slot still empty and it not possible to take off with the X button. attempted to equip a shield to unequip the bow just make the shield disappear from the bank, but not equip, both item disappear from offhand and bank after relog.

### Reproduction Steps

1: equip bow
2: set bow as quick equip in the offhand slot
3: click the offhand bow quick equip
4: try to unequip bow in offhand with [x]
5: equip shield
6: relog

### Expected behaviour

unable to unequip the bow
both the shield and bow disappeared from offhand and bank

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

4462

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-10-20 05:49
Duplicate of #2662

**Closed by coolrox95** 2022-10-20 05:49 UTC
Labels: bug, Duplicate
