### ISSUE TITLE
[Bug]: Unable to buy bowstring and craft normal shortbow during tutorial island

### ISSUE THREAD

**Issue by D0minc** [MelvorIdle/melvoridle.github.io#2093] opened 2022-01-23 12:15 UTC
### Describe the bug

For Task - Ranged Preparation 6, the requirement is to take a bowstring bought in the previous quest and craft it into a bow. However, if you crafted the bow on the previous step, then this quest doesn't account for that, and since you've finished the previous step you can no longer buy bow strings from the shop. 

![image](https://user-images.githubusercontent.com/98263060/150677826-c60b8711-9fbb-40b3-92ab-1cace66efb3b.png)

### Reproduction Steps

1. During task 5, buy bow string
2. Craft the bow a step early
3. Finish the task 5 quest
4. Start the task 6 quest with no bowstring
5. Try to craft bow, cannot due to no bowstring, cannot buy bowstring from shop. 

### Expected behaviour

Being able to buy another bow string

### Screenshots

![image](https://user-images.githubusercontent.com/98263060/150677863-e36f7e03-7c28-441c-93c1-f9a6fc596e99.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1419

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-06 08:51
Duplicate of #1949

**Closed by coolrox95** 2022-03-06 08:51 UTC
Labels: bug, Duplicate
