### ISSUE TITLE
Android App Size Issue

### ISSUE THREAD

**Issue by Kurtsliva** [MelvorIdle/melvoridle.github.io#2314] opened 2022-03-09 22:41 UTC
### Describe the bug

The font size for the Android App is 3x the size it used to be with this last update. All text in the game is larger. Some icons are hidden off the screen as well. 

### Reproduction Steps

Open app on Android.

### Expected behaviour

To remain constant to the size before the update.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

I can't access this on mobile while I fill out the ticket.

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-09 23:20
Duplicate of #2290

**Closed by coolrox95** 2022-03-09 23:20 UTC
Labels: bug, Duplicate
