### ISSUE TITLE
[Bug]: The mine stop refresh after use some mod

### ISSUE THREAD

**Issue by xuancang** [MelvorIdle/melvoridle.github.io#2763] opened 2022-10-22 17:03 UTC
### Describe the bug

I used 2 mods to speed up mining, use "Gotta Go Fast" to speed up 10 times the game, everything is ok now , while I used  "Ore Respawn Times" and set the respawn time to 11ms, the game breaked and noticed follow:

An error occurred while processing ticks:
Active Action: melvorD:Mining
Error Name: Error
Error Message: Tried to start timer: Skill with invalid tick amount: 0
Stack Trace:
Error: Tried to start timer: Skill with invalid tick amount: 0
    at Timer.start (https://steam.melvoridle.com/assets/js/built/combatManager.js?4526:255:7)
    at Mining.<anonymous> (blob:https://steam.melvoridle.com/77dd7ceb-68f1-4dc5-ae06-0a9473288f96:142:17)
    at Mining.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?4526:736:113)
    at Mining.postAction (https://steam.melvoridle.com/assets/js/built/rockTicking.js?4526:135:138)
    at Mining.action (https://steam.melvoridle.com/assets/js/built/skill.js?4526:282:76)
    at Timer.action (https://steam.melvoridle.com/assets/js/built/skill.js?4526:262:125)
    at Timer.tick (https://steam.melvoridle.com/assets/js/built/combatManager.js?4526:252:89)
    at Mining.activeTick (https://steam.melvoridle.com/assets/js/built/skill.js?4526:271:31)
    at Game.tick (https://steam.melvoridle.com/assets/js/built/game.js?4526:164:123)
    at Game.runTicks (https://steam.melvoridle.com/assets/js/built/game.js?4526:161:96)
Current Equipment:
Helmet: melvorD:Iron_Helmet
Platebody: melvorD:Iron_Platebody
Platelegs: melvorD:Iron_Platelegs
Boots: melvorD:Iron_Boots
Weapon: melvorD:Normal_Shortbow
Ring: melvorD:Gold_Topaz_Ring
Gloves: melvorD:Iron_Gloves
Quiver: melvorD:Bronze_Arrows

Action Information:
Is Active: true

Selected Rock ID: melvorD:Adamantite_Ore
Active Rock Data:
id: melvorD:Rune_Essence; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorD:Copper_Ore; isRespawning: false; currentHP: 84; maxHP: 84;
id: melvorD:Tin_Ore; isRespawning: false; currentHP: 78; maxHP: 78;
id: melvorD:Iron_Ore; isRespawning: false; currentHP: 17; maxHP: 17;
id: melvorD:Coal_Ore; isRespawning: false; currentHP: 34; maxHP: 34;
id: melvorD:Silver_Ore; isRespawning: false; currentHP: 58; maxHP: 58;
id: melvorD:Gold_Ore; isRespawning: false; currentHP: 54; maxHP: 54;
id: melvorD:Mithril_Ore; isRespawning: false; currentHP: 80; maxHP: 80;
id: melvorD:Adamantite_Ore; isRespawning: true; currentHP: 0; maxHP: 74;
id: melvorD:Runite_Ore; isRespawning: true; currentHP: 0; maxHP: 92;
id: melvorD:Dragonite_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Corundumite_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Pure_Essence; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Onyx; isRespawning: false; currentHP: 0; maxHP: 69696969;
id: melvorTotH:Iridium_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Palladium_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Augite_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Oricha; isRespawning: false; currentHP: 0; maxHP: 69696969;
id: melvorTotH:Meteorite_Ore; isRespawning: false; currentHP: 4445; maxHP: 69696969;
id: melvorTotH:Divinite_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Cerulean; isRespawning: false; currentHP: 0; maxHP: 69696969;
Modding Enabled. Loaded mods:
Dev
Gotta Go Fast
Ore Respawn Times
SEMI Core
SEMI Auto Farming
SEMI Drop Chances
SEMI XP Per Hour
SEMI Auto Master
SEMI Auto Eat
SEMI Auto Loot
SEMI Auto Runecrafting
SEMI Auto Run
SEMI Auto Bonfire
SEMI Auto Sell
SEMI Auto Open
SEMI Auto Collect Stockpiles
SEMI Save on Close
SEMI Auto Bury
SEMI Auto Gear Swap
SEMI Auto Smith Bars

and after restartd the game, the mine just farming stop respawn, I'm sure it is caused by the mod "Ore Respawn Times" becaused I successfully recurrent  the bug again and now I have 2 brake mine (LOL). It is useless to try the approach in #issue 1647. I ask for help is there any way to fix up my saves by console command or other way?
![image](https://user-images.githubusercontent.com/33287136/197352788-38952b14-b8e4-4e25-8ecb-3a49a847aef0.png)

Here is my save:

eJy9PAl4VEXS1ZM7GAIoN2gMKLoQCOFGhZ4cJBwhIQmiixpeZh7JmMnMMAchuireLPJ7r4rHisp6H3itFwIeeON6Ix4rnuuxKt7upX9X1Xv93rwkuLvf//2PL9PV1dVd1dXV1d31+tFhhldG4wADtgNAhvrL6SBMpQLvUH+5jUkjEjTiQcCnz8JovMMINy+ItiZAKERBeTwaOcFsrjRaW804+LDGHNNItpnxBDWX6w/FmxtSERMyVS6vNhQJcjYLeVVEO2LRRBKyMVMZMjqikSDkEFsjFmsLxU3IVbnMhlRLF+QpKN/iV27EIR/p6qNJIxk1E9BH5bKaojHjBNgHW6vqMONGOAgFKHZtKNkWD4Wb61SDhQrR1x80OoxIMpQ0CdcPm66IxmJmnPL9sek6o507uq/K9as1WkOB5iVKGYp5IhSA/bCO6ordxkDk2hSKUGYQdrY8FA82LzRV/wajEEtC4XC0k5scguVNps1hKLZVa8TCJueHqXxhjWkEw2Yi0eyPx6OdCRhOmojGTDgAm2swOpsb1cCElDKLsPPl0YjSw4HYVLURT3U0N5pmEIoxv8RImtYwjHLrA9U4WiH2s9RaEY8mEi1KSOQNB1EnFOtkPBRphYMx25g0Ta53COqoImqwVg9FY1Cjqwibq8PRlUqSXyHBXNUwEYzFLnHt+rASpyUa7IJxHmTYVJ0vUch9GZkuz3jdIPKfQHU7VE9cPEuRBDVTbprLYSIOyQI2R5iE427VTibDprHKhCmoDMI1toVMZS1Tbc1WtIUC7WYEpinEgMZQa8RMNjcgoxojvLzZD9NRrY2h8ErLYmYg4+poOEi5mSq3D6q7uSqRMCMBEw5DLdcaCTUOXc1NUdV0M2sLDic7wsFUQ9IRgyPQ2qzxoJFPhmIJmIWCsbHzuErsW53iV2Mkwc/8WlqUNJWpQHsXlJMFq+LyaDQJFUjcaBqdWBOndjZPZJiDNqWmeAtU02QNBFJxNQ5QgwZFJg9ztY5qzHCHmYR5qPiqjliyq7lqRSoU6zAjSZivteuM7oJ0HA1uLfaWR0EJloCF2JjlVRrbovGkGm2oQyQpkyY0KR7qtRzWWC9y+R9rijSQsSsf06hMtt2ERiTh8Q2ElKkos2nC3luqXozk3JM50WgQjiSfZI38EktnralwGI6iCaxoAqlkEqU5GqvOUQ6qw2jH/K+Rek4ogcYIS9m3RankGGRojfWx5Nosm4XjMNekDG8l5pqpBSPegZllONfmhM1kgCgNmmtxYznxbrGtK2BjAlheY8ZbwlFlfeirc/ytoXAo2QUmzdpUh3KtSLkcs341o6PhaGsXtJII0c6IEjwGbSrna+qC42mEVyXjhporkfbmxrCyoXbkyqOpFISzJ6zno1/lOlDX1ly2CCI0QmEj0K5RUWzadj82MoZIyyVr5Ao9h2xM3HFAyDBBTjMVToaam+KmCUmVH1aZirSaSiJtmc2NnWopwa6nVPlA7pWrVM3rubCSBEipuVVlJJubQmoazYVOnIge5FxYhVjqtDXazQ3KcrrQ1CvjRqtLPSeQ+8S1ollNXDiRsqQMlP43bj+MiJPQ7VkzwbKdZjQwOBkpbe0g5SkK0d8r2FxYjWhWj1u0UxV6ULrn0RZ4uiobml7mNvIzcAiqw4Zag8qj6DPhbPQLjW2mmhJrsD8NqYSaPPPNLvgtOkrSS7rTXos11PxXPuIcnAlqWreEIrAO0TTV4H+QS62yUMOeeucqTEaFcgTnYQ1/MqmUBufT3EnGzUhrsg0uQBuvNJeTc70QRakJJWPRUET5lIuwVoOhDCEIFyNcHze61ArwO5r6YYIvQRZqhYdLEclLM1yG3hBXZVjP/k8tyHA52XWbgRTooZTnuYJRcSMWMcMNIbUGwJVYlYbrKixkU7C3Br/HHvLIWOvMTQ7G8qo3owX5FZMk2mW9SifCLd1wZXBrN9wkuK0bbjLc3g03hTZ06bipsKkbbhrc2Q03He7qhpsBd9O0SZO5FO7pjpwI93ZHlsEfadiU1+Le3gd654JIuN9dXAYPuLOT4EF3djI85M5Ogc3u7FR42J2dBlvc2emw1Z2dAdswix6FxXrEnS2DR93ZSfCYOzsZHkczWKg2YvAh9mZxxOyIhaNdyhD/CnpvjYsu+vAMf6IN+qJX0v5Z2Yfa0jVXqwYjMACNhFY2RC9Xlj3CXhhxEqvVLKimH4zkiWHl9kcSz3YOxuh1UKPKcDz1ljTSirjJ6EE8i3HzYpiNLi+dVGGrcIrQSgIhdDFOH+YYHWrtMeLNVWrSn6bKBqe7GGddO7N7obM2nQU9bIJ3dF/0n+9pC/EncJ89XoC0s8eLqHwU7iUcrtqomuUvsz8xg7iSvII+YW48FDQi8Cq5IHWYCBnwGna5yYzHDdhJvqQrrPoJrxNJ3FB9gl24hM6PwhuIa1J+MpWAN7FaTZcaNHgLGR5pKIZvI8NFalMSUEz+jC4enWR7c63RrtzJ+zQX4srzKmQwAR/QfkB5dVN1MwIfYbHtqRX5X7B+Y1LZHe4qFeJjpFeux8p+AnS+UQri/KeYp7UogUsBfIbC0P5CFX6OqqumTbPKfUEdMUJqZwFfYueq62EPOTvcMX2FEAoCX9PKgCLAN+Rbld/7FkuRLXyHKNy1f0+6UHMtAT+Ad5P8I7j263/DjFo4Q9FIAv5ObhwVlIB/oHwVarqRCf0T1x13K1YX/0WTJ6aozIARD6mZ8ZOtNGVlNakk/Izt4IYLVYyHWbWhTyr/3hZNJUyBiAGOihK8aHYJHw18oC0aDYsMMkZa4XFNVMoTmawutSRERBYJairvrsxb0BlXuTfFPiHwjJuvlqVkAvfvCYGn3Ow5uLgkRR5NNz24ieYKoyMm8LS7b4URjyn/icgl0Xh7oi0aE3jwza40E2Y8KfDkm0WHPVFA49GJVdHF9PErc8Z9eEhxL6TpEE1FkpSl0y9pLaE2L0mBp99sZaRhs0sMIP+mNoh48AkLPApnz1N7rLAp8ABcYNtJAlUq8AxcUJOKWGKrhV7QSbgxEu0kQxaDaQoZifZSMcQGJ4qhNlgmhtngJDHcBieLETY4RYy0wakCfV12lZHomjhNHGCjp4kiG5wuDrTBGaKYR0axKxWjNDxRjNZwmThIw5MEHnfz2WE3RZN4IMKuFFZE46lIMNVhr+1Xo53Vp+KOFW9Aq6+LdK2Ca4COLKFgSK1pSHwt6qdeKdLQqOuQjT/Vare3EUWoi4cCbQb8AclrlflE43bx9ciuMqRODDbmBrayeEodaSNwI3RbaCfB9u7IyfBEd+QUeBKl0UtyKTyVlp8IT6fly+AZ9/I3BZ51Z6fCc2xIcbXlgXcQrjHMjlAcdqPIDdGEEQl1GfAuuc9EG57O3lMwDl/uqpQRUZ4Rzyf9rIjUTDsUJS7wP376mNRqVVa+Sub3/TlGaaEPt4hT+3bHWY+7UXxwthyOYaysMo5cYcQqo4AiVVUUoGqkyFQmhaRWYyhKfIphKPEGBp+G3kFBp3xsJ+tsCjT9SMu5D2NMWe9iVGnA6xhLWjGS1vJKjCSp2YgTR2C86Kx1aFPTL6H4UD4GhXxjMRaUU0cRoCwK+ZTgqn9BBJd58QUu75kJCgBlkaLqKOAzmsI8goI7mRTR6UfRGx8FbXJo/RcUsSmlSM2rFJwRFJTxURRGUNhFUIxFcGyFgimCgiiFtF0QFEPJpW2CoNiJoICJoChJMcVEBEZChB8jIAPrOOpBEQ4B/90zSdU8QulmlhqbEao3s1Wbmarv2SBVv3LVaPRR+i9QEvdVfR6gNDxQyT1Y6XKo0uFIpS+/0lY5VCjtFyldFSsdjVa6GaO0MV71bZIa6WkkOT4RxY0lneNIjF3HztJp5Kl/vyMCqgXUCAqg8OMjVQqKoGA7GTAf/6m1ZkE6xicoUOLCZAgKlbgwmYLiJC4MWqwNZ7vgHEHBExdlrqDoiQuTJzB4MmWtg8l3tdDHBe/jggtccF8XLCjyYj+FkFbk6qYLznDBqmtNnq7ZltZzB11wrgvOc8H/d93hAvzD+NFIihoB//5sPQjv35Mt4fTCCUUu+T+wJVDjv8SGD+cky0Yp+8H4FElPruqXnv32Whq0BBdacHe3nvrPBO8+CbDuf24RLrhXM3fB/z9WwFrqNvKFuhCs/gDQokJrCi0pPEwkJYlHcpFAJAmJ0NfFp5fxcHP9N58M2Fut/9ZN9/r0p0gpUHwUKDAKFBEFioUKtQ4dR2mpZSHN9LuMfg36baHfAP3yWyiTfpfTL6/lbRY3nzqKYvByMEUrz6MIpaDIpKBgpKD4o6CAo6AIo6CooqBgoqAQoqBAoaCYoKAgoKCgn6Agn6CwnqBonqAgnqDInaAwnaDYnKBQnKDIm5BHa134cEW94WNcex+rd2sabcMnt6zQCHldqQ0Kf8v5925jOEOO1iRkSjIgdRuyVcMZ/gnn6PqywhFADtEw2p7bV+TKXCcjJ2pQuOBMOcLV1jM3aVlm79H4DLlvmowZcsFqp10HzpYN23Rbfl+dXSBkmSbPpr5AwzJd/1/523SdG944vdRu67JNjozXn+DIrpulaZYrt8S1bHK7szWUD2xxZAmPKrLgHPn0RLuBDHnWj067a3TdbHnNOIf3kbpPPT10IHTpOUNuLtIZlw77uMZZuPDEj/h/fdEyLfvHBY6Mn2y24Sx592tOnwLH/VPLuGmNuz3yS1KbG/hccKYLFvId6e2Pzyufy77sJ4faNHfb+Qy5yhaRbdhF57Tj2JmQ7w624TxXO0dZPhGp7/6Qcbi1JWcrT9rj1D/SkVdeYNU/Qte1rXCxruvYaI48XNfNlWtiDA3SlK/M26a5rHvd4XKlBffXlO+WOpTnrHIor7DgfC3Pw59aZWDP8SItQ5ZcqOE86azihS6bytbwLN3m06MYk+FgsriTIzTGtqLhDs0MxuBLNVqz5LOHrNbcQ1qsLHnJBzacL9t2O1JVuqSydy8H6/YPtjCzbYy2pDq77y7bypNt23ri2DOXwzSXcgtDPpYwi6UjrW3fWbrUmcH5WvP79SBPtm4FZXPsPkvO13Chps/W8tijhtXZNpyxK0jzAbZvyNF1AxYmV2NWW4zzNOYUq0tjdfvLdZtCLtKwT6asHuC2g/vueJ2+Gt5Ht3zJaktKjVnRjzETNGauRdNXY+wWZ2h5NurJLeQ1lzvyfLZ6A0EzNeXmJxzKq95yUf7EzeqDpayx+Bbqui/PlLruiy7vXpbJbrze7rVL55lyXQ1D/XQ7z+jhFHLbO047Y8pY2gFahqWWDKdpjO2t9gWvxgZqzO4XuVppj/I0Wp04HbyzZrDG2CM1RGNOXcaYoRpzleXIhoHXDs8A7+w7U9NYwtIbBsbcZsmzv8Y8NorlP0tjbB+F7woz0mRGHTqwT3tmP3SfC8IF+6R9QD+gm/xrdF1Nruo6sLOelf8il9Buhio0ZZGLsshFWW9BlZqyn4uyn4vSFuW3/7acyIf72LiNMQdqjO3NisE7aqPAO2qjNcZu+SCNsXs9pls7h2gau4+/6kaD0Yrutvrb3Qxh5CLT21MXpU9O6aHW2m5cFu6Vy7hu9CXdMOO7YRb9omy/6oHXvL1KgqGK7quVY+dZ8tfbbDjbReOsDlPt9l1SZcpfW7myHrjn6RGcaPdRjrcwU3qUZ7JLHrNIy+PiWKjhSbpNm7AKvJqc3A0zTdfyW5jp3WhwNcOjCUqfmzZnnJ1Nlmtnk502Px04J+204pwYMnUflmgu5bo0Wx6ny4U8b7fDsXG1w8Wv6XNktYuL22ptyddpLvu5arnlL9KwcO2Nslw7a3BJlSmLNdrpL96QwB1ErluPuk66VQk5S8Puc5lPw3i7IsfTmpCTeqwF8iwtaKac5uLu7IydPmKAlLVR5Cr1r3ZaM7TU6WeL32zT3F30Oa4diU9r9SjNxREzO22NqXe15pwkctynEz1b3Dbj1pIV4ytfNeuLYIh3/v4db98TXm3x2D1kmUWHe/ccf+Y7NtNc/+hD79eyXGkfvBTPat2zPtLYrfm4QwTyPH3KzErTsX36wH3pOWnHrEyi/am/PgL7/5j1bZtdL67ROfLOYzVMddYVab7+u+55do/Tb3fbjvy1Wn4hn9zuyPbj8S4qIYTQAIL0qyHPA1Z8COxXOj0cIUmQlRPH24GIIXQXKE8uew6fHYIuA+Vp/nwdyMleRMS/++itQ757dI2gG0F58rQ6CoFxYLJYTllPT3r4Ky1O9rv0Ri8B17ZfUCcWy79dd/UHd57ciK1kwRz/0FdOvWbA/a/BpfLxSz85ZnP/QrhMfnj00hVDvnwO1vsLT/043Pl6J1wu5cynxYeJW/056yZOqtuFL/3Ic1p+CGNmlfKivijfpdi0D46QO275xH/r6UOgSL5w+Jcjzrz7Srl1wPsPL/2OZgFukuqorg+uUEfdK2lLwTG46dKYbsmMf0L2vbjx0Kqyi2Z/wSkW4eYUNwZ4z0mcT4OnSDFqN0PGN7hqL5ZnDAuXvz/lOxnk1NbPIUxzFZ2q+VGmJ070N20sWJI/eThWz4dB/tLBywYFj9kP+vuPmP/Q2svqT4PD5NzK6htPW7QAxsrL/WN/vLklATP8vrmBXX2e2wgz/aNm/TTnxupcKPRPbt210rwiFw6VT76Q+C5421vQz39w65YLPvn2Yhjor/vhjrHll97qr3pkTfnQ+eQ6cMe8P/cPj4fkUbPpjE5LeBMd7GnXsZBOT1TUn4IKtN8qpjMMHU9m0i+dsOdyuHcR/fWzDWgeDLTBY+j6l8Xtagfc4IDXEGHmmJOepjfEFvY6B9zogH9waPFdcP9jCbzBIbjRIeDHem2FcdZv5Z7EJ8qOLhCkhnx/w5IdZzWMexN8svGKaz9+cPw5MMt/4Pq3P725qRAmyAefX/XC9cGtMFqeNn/MCxtnnA8HyermCXvGn70HDpFPfWE+8+zO+2CBnFC1dcW8YTugVs5uurB686waWKtxCzU0VVafXtweuu9iGCcnNA569oOcNVCiofEauklDN2tokZwdMPcfbzwK8+QEC2rS0BQ5IbZ51VMLT/bL3XL/j0voqDiK7BDfU2JMucS2w16muCcmvkzNnePs8wkbex95+GevnPtwzWdyBKeAG/NbcGpk7yc4eE/PrVzHQdzmRdzuRdzhRWzyIu70Iu7yIu72Iu7xIu71Iv7oRdzHiPs14gEv4kEv4iEvYrMX8bAXscWL2OpFbPMiHmGEE1p+1It4zIt43IvY7u3tE17Ek17EU145nvYinvEinvWyfc6LsB98vbFafrR2GRPg8jLCX3rNaQc8+Xku7PDnvHJ1qDKnFp7357e8+Fl+/zdgtiz4y4DTnzjpQviThsbIIXJrmfhkEJRpqEpDk23IX7SxzXf8Iytt3jgx+ESAr1eKbHSv6x++fplqx0p5EXpB+r+8uOO6r86AF2Xjg5vfEaMq5eF3nT3w5RF604BcXqSXNr/MAV/qnPILVJ5XVnTIyaL7+041d97nyWd48pmePL1TminPpA4U8rR/Sc754fiZBy6slQdzimXoS/E16UtgM3qpH7ws8G2USPmP2X7TNrCH9BV/nw3njfspfgO8KjO2vDb8c2MrvOafdmLmzIJ4Gez0j7znhtiMz56C1+Xbizq/ueSUw2CXv+z7wSuu910Lb/gXVGz7asHGo+BNv2nu6Ju36SV4y7/YnF2e11jvb3jlr/mXHE0vjTAIhTdZyPEV0v3FjAzn3SPeYczI1Sqge4wZWfxOFS+07aRyfmeaqbT6NuhdICWvUwHnMdnlKX/Dk3+TCTPt/Fue8j978u948rs9+Xc9+fc8eXzUhjf3EfnYjQ+o5e1Ksh8B7wu6OPkQfCiAPdX7eHVSdApKTE6u5eRxSnzDBN6mFOdycgYnf+VkFyeVXKGQk82UwD85tw+R4MtGzM1i5DBOtjKHDM7dwsnNXL2VK9wp8OqmGMHJOk6AkyM5+ZqTnVyvmeu9yo0t4uRoTrZx8h5VgM+5glrTsPoELmvh5CVO/sVJFSencnIF16tjRk8w8hROyjk5j5MUJ+dysoHrKTnx9ul8rp7PyL8wSRcnYznZzslMTo7hZD0nDTr5VCVqOHH1/RNrYisneVovmNzLFeanySk5OYuTak7u5+QiLQve1J4KdoLivshlh/DYPslWUMC5Jzg3jZN2Ts7k5CUm2cO54Zwcwck4Tm7npvtzbi0n/RnZj5MtnKxym5s4O83qApyMZ+TXnBvJyW84OYOTek4OYsodwjUq4g5GPsS52zgZ6s7Bz6ye0WAnWBZlkhwmuY9z2WmGYs24LCbZxblGTu5mpMVhC3M4EFwmBX/n5Hm3lYM1A15j5CbOfcwJtyksWY5yJ/A4cxjJHIqFK4E7OXkgLflc9x0pL+Tqw9k03nTnbBNu4mQllw3jsnmMHMTJDG7zPc490pNFMhKu4eRLRs7h5Ha30cKNnMtNQ77MucPSbKkfizSAhWcHAd9xwk4AjwofsV9Cyv5MeRXNOJEQdDt8JyXiaoH31MUNAi+J4/xDkmVcbx+wc2r2izIigU2cWBWGUHX4lls5lqs3cdN9uewbzq1nkmPYlVzMrTzJZRt4ypysp/aXKplKCVzA7uL3LEQ9J7O4D39mOdUahcgTud7l3OZ1nBzIyFW4eBTAHvnlwbzUfCW//mjpER9mrIGv5aMDje1rxz8I38gNhefP/n7Mh+qMlXfmewMKazfAd3LlzvarA8Ux+F6mLmuJr4Bv4Qd5Qme/i9fDetBxHvibPLlwXfbEmRvomjs//5AVssaMVh0F/5TJI0/66Fx/wCopILlJvWoHhINzIXmZgeTl9yEVZdMNfx/pKYuuwgNf66dL8EC6zSIV4RqdT6tkH7oQ34eWzjwK4WTTZXdB19wF3WzPojvtgu6yC8EvJr8k2H4liZLgZn0KXWPPpmvrGdRmluB9I3LJpFvrVsvoWdEccBrRDXarKb5AJQoszBCLxifsi1G3W38ZdKFdCLsiBgiXEGU/+qX77MQXpcdbOSupp7hryiD8UKrbV9gv6jDYg7eGptIl9wy61y7oKrtP2K/qcV+P54ORwr6f8JX1Z+9/FVUGhkROKF8l83aevQ1xhcrsh6oNwXC1xo8U+4sDRJGys2IxSoxWThkNLAdGb8IXqmOXLi2uNiP4FXvxOAW3RkuWG4lkSQd+8RgLh8x48bjiiaXFx6oHmUbwO9XRz5ytZLzQUxU/jyiyrqeXxM1EzOiMlCRDHWbxuImlpaXHjltazB+/ewqnWIVNoUgvJfhNUQ8tWk0a4d7K+Mtpb6ndKn7h1FuZ9cmkp7jMbtj5sN9DMcmm4E/2PaVT7VL94Z6Xf5nTLf0BgJdG88DvAXpTuCbCTwS8haxT+mDAWzRZN25/P9CTilgJ9DmBt1j3kb8u6Im1/tagp0L7qwNv2XStGesjhG6V3RZa3IJT/wxllY1VtXOLlDZNstGE2REqCVAO6bA9/O6rJBJNhpaHAgZ9B1Q8LhlPmVgWNFtSrSXhaGtrKNJaPG65EU6Yis04q1l/OFxUnkoW1UW4daWykpZUsiSKeWojbdbkK5clMpbi4NJ/SEF1Agyrel0O31TCLAnYRG5kpxmKB0taw9FoTHOgoUhGi/AT5CL9zTELpPAlCYUvMW18SdBMBOKhGPbUUQLRLDGNGCK5mza2wdV1G8ffxnuxFUbM7IZT+kx1GC1h01Gfa5jClypHMt7jSGiQSPQO+mivxIxwA06H6814UWN7SOm/SQ1OGGXBiogp4Q85giWdzjfGjhLTSZbzF8y9F9tf3vdGEeBPqHsr7qAP8nsrTVgfSPdWnrQ+2u9VPP6Mv9di+wPIXoW3PuzvrTzu+vi/N5o2678D6K3c4P8goFcV2J9z9lrf/lCzhwlVfHxMwwCH0mSKLA+ptk4sVh6kI1E8c+mx44rZeoLFM8n+TlINFF++SJndFFWh3FB2pIcBTQgzFvdkVIFB2x+1GHGXkF6yDu3T9k5nsNPcO1FM+9690wVci8TeKUOWt++VKlgS1GvSXojiqV+iMJylcS9Urbj27qW8w1p/90KS4MV9bxT45fveCEK4r9hLeQt9AeyicFuf892eKvlfcRHDRg==

### Reproduction Steps

1.go to mod "Gotta Go Fast" set up the speed 10times
2.go to mod "Ore Respawn Times" set up all mine respawn time to 11ms
3.click a mine  to farm and wait it to zero
4,the game break and reload
5, mine can't refresh

### Save Link

Ore Respawn Times

### Console output

An error occurred while processing ticks:
Active Action: melvorD:Mining
Error Name: Error
Error Message: Tried to start timer: Skill with invalid tick amount: 0
Stack Trace:
Error: Tried to start timer: Skill with invalid tick amount: 0
    at Timer.start (https://steam.melvoridle.com/assets/js/built/combatManager.js?4526:255:7)
    at Mining.<anonymous> (blob:https://steam.melvoridle.com/77dd7ceb-68f1-4dc5-ae06-0a9473288f96:142:17)
    at Mining.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?4526:736:113)
    at Mining.postAction (https://steam.melvoridle.com/assets/js/built/rockTicking.js?4526:135:138)
    at Mining.action (https://steam.melvoridle.com/assets/js/built/skill.js?4526:282:76)
    at Timer.action (https://steam.melvoridle.com/assets/js/built/skill.js?4526:262:125)
    at Timer.tick (https://steam.melvoridle.com/assets/js/built/combatManager.js?4526:252:89)
    at Mining.activeTick (https://steam.melvoridle.com/assets/js/built/skill.js?4526:271:31)
    at Game.tick (https://steam.melvoridle.com/assets/js/built/game.js?4526:164:123)
    at Game.runTicks (https://steam.melvoridle.com/assets/js/built/game.js?4526:161:96)
Current Equipment:
Helmet: melvorD:Iron_Helmet
Platebody: melvorD:Iron_Platebody
Platelegs: melvorD:Iron_Platelegs
Boots: melvorD:Iron_Boots
Weapon: melvorD:Normal_Shortbow
Ring: melvorD:Gold_Topaz_Ring
Gloves: melvorD:Iron_Gloves
Quiver: melvorD:Bronze_Arrows

Action Information:
Is Active: true

Selected Rock ID: melvorD:Adamantite_Ore
Active Rock Data:
id: melvorD:Rune_Essence; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorD:Copper_Ore; isRespawning: false; currentHP: 84; maxHP: 84;
id: melvorD:Tin_Ore; isRespawning: false; currentHP: 78; maxHP: 78;
id: melvorD:Iron_Ore; isRespawning: false; currentHP: 17; maxHP: 17;
id: melvorD:Coal_Ore; isRespawning: false; currentHP: 34; maxHP: 34;
id: melvorD:Silver_Ore; isRespawning: false; currentHP: 58; maxHP: 58;
id: melvorD:Gold_Ore; isRespawning: false; currentHP: 54; maxHP: 54;
id: melvorD:Mithril_Ore; isRespawning: false; currentHP: 80; maxHP: 80;
id: melvorD:Adamantite_Ore; isRespawning: true; currentHP: 0; maxHP: 74;
id: melvorD:Runite_Ore; isRespawning: true; currentHP: 0; maxHP: 92;
id: melvorD:Dragonite_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Corundumite_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Pure_Essence; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Onyx; isRespawning: false; currentHP: 0; maxHP: 69696969;
id: melvorTotH:Iridium_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Palladium_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Augite_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Oricha; isRespawning: false; currentHP: 0; maxHP: 69696969;
id: melvorTotH:Meteorite_Ore; isRespawning: false; currentHP: 4445; maxHP: 69696969;
id: melvorTotH:Divinite_Ore; isRespawning: false; currentHP: 6; maxHP: 6;
id: melvorTotH:Cerulean; isRespawning: false; currentHP: 0; maxHP: 69696969;
Modding Enabled. Loaded mods:
Dev
Gotta Go Fast
Ore Respawn Times
SEMI Core
SEMI Auto Farming
SEMI Drop Chances
SEMI XP Per Hour
SEMI Auto Master
SEMI Auto Eat
SEMI Auto Loot
SEMI Auto Runecrafting
SEMI Auto Run
SEMI Auto Bonfire
SEMI Auto Sell
SEMI Auto Open
SEMI Auto Collect Stockpiles
SEMI Save on Close
SEMI Auto Bury
SEMI Auto Gear Swap
SEMI Auto Smith Bars

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4526

### Are you using any mods?

Yes

**Comment by ekuland** [comment] 2022-10-22 17:05
`game.mining.actions.forEach(e => game.mining.respawnRock(e))`

**Comment by xuancang** [comment] 2022-10-22 17:11
> `game.mining.actions.forEach(e => game.mining.respawnRock(e))`

It workd! Great thanks to you!!! 👍

**Comment by coolrox95** [comment] 2022-10-23 00:10
Closing as this issue is caused by a mod. Please do not report mod issues to this tracker, and remember to back up your save files when using them.

**Closed by coolrox95** 2022-10-23 00:10 UTC
Labels: bug
