### ISSUE TITLE
[Bug]: Logged out when hitting enter to buy feathers. (100K) 

### ISSUE THREAD

**Issue by AlecJDesrosiers** [MelvorIdle/melvoridle.github.io#3400] opened 2023-05-07 14:52 UTC
### Describe the bug

When you choose 100k of an item, (feathers for me) you get logged out when you hit enter to buy the feathers. 

### Reproduction Steps

1. Go on fletching 
2. Click on headless arrows
3. Click on Feathers
4. Choose 100k feathers 
5. Hit Enter
6. You will be logged out. 

### Expected behaviour

You should be able to get the feathers without being logged out. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by aquelle-cp** [comment] 2023-05-22 17:24
I'm also seeing this issue. I'm also on Steam, and it's happening on both my normal and my adventure saves. When I go to set the number of things to buy, if I hit enter after inputting the number it logs me out.

**Comment by Sammehbrah** [comment] 2023-05-25 02:05
+1 to this on Android Mobile.
No mods.
Hitting enter when using the "Custom amount" box, sends to Character selection.

**Comment by PatDoubleYou** [comment] 2023-06-28 00:58
Also experiencing this problem on Android.

**Comment by coolrox95** [comment] 2023-08-26 12:30
Duplicate of #3383

**Closed by coolrox95** 2023-08-26 12:30 UTC
Labels: bug, Duplicate
