### ISSUE TITLE
[Bug]: action buttons don't work

### ISSUE THREAD

**Issue by Tsty123** [MelvorIdle/melvoridle.github.io#3170] opened 2023-01-19 03:34 UTC
### Describe the bug

I can't activate the action buttons on skills like "create" or "fight". They just don't initiate the action. Farming is still OK, but all the rest, the action buttons aren't working

### Reproduction Steps

I click on a skill
There's the green button to start the action
It doesn't work

### Expected behaviour

It should initiate the action

### Screenshots

Doesn't make sense to add a photo, the button is not simply starting the action

### Console output

On the phone and on the PC, maybe a problem on my account?

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

1.1.1 (?5027)

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2023-03-25 22:47
Duplicate of #2779

**Closed by coolrox95** 2023-03-25 22:47 UTC
Labels: bug, Duplicate
