### ISSUE TITLE
[Bug]: Stuck at Herblore

### ISSUE THREAD

**Issue by mibanez** [MelvorIdle/melvoridle.github.io#3251] opened 2023-03-05 23:16 UTC
### Describe the bug

I'm stuck at Herbloring, even after i got out of materials. Any attempt of beginning another activity has no effect.

### Reproduction Steps

1. Logging into my account
2. Select my main character
3. Screen of Herblore appears

### Expected behaviour

Activity should change whenever I command to do so.

### Save Link

https://melvoridle.com/save/K7mtQRfU

### Screenshots

![image](https://user-images.githubusercontent.com/7943643/222991193-c2ecb289-dc54-4da9-bab1-ba5753bf42cc.png)

### Console output

```
Silent Sign in with JWT
cloudManager.js?5053:201 Validating Melvor Cloud token
cloudManager.js?5053:201 Storing Melvor Cloud Token
cloudManager.js?5053:201 Initializing PlayFab login. Method: customID
cloudManager.js?5053:201 Logging in with Custom ID via PlayFab
cloudManager.js?5053:201 Login with custom ID success
cloudManager.js?5053:201 Getting account info
cloudManager.js?5053:201 Account info retrieved
cloudManager.js?5053:201 Authenticated w/ Melvor Cloud: true
cloudManager.js?5053:201 Authenticated w/ PlayFab: true
cloudManager.js?5053:201 Checking for valid full version
cloudManager.js?5053:201 Checking for valid TotH purchase
cloudManager.js?5053:201 Loading Game Data...
save.js?5053:110 Registered Demo Data.
save.js?5053:110 Registered Full Version Data.
save.js?5053:110 Registered Throne of the Herald Data.
cloudManager.js?5053:201 Initializing Mod Manager...
cloudManager.js?5053:201 Loading Local Saves...
cloudManager.js?5053:201 Loading Cloud Saves...
cloudManager.js?5053:201 Getting saves from playfab
cloudManager.js?5053:201 Saves retrieved
characterSelect.js?5053:5 Loading character selection
cloudManager.js?5053:295 Connected to PlayFab successfully
save.js?5053:39 Copied to clipboard successfully.
main.js?5053:15 Game Loaded
widget-v2.js:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
insert @ widget-v2.js:1
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
[Violation] 'setInterval' handler took 218ms
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.js?5053:31 [Violation] 'setTimeout' handler took 60ms
cloud.js?5053:29 Synchronising with Cloud
cloud.js?5053:28 [Violation] 'setTimeout' handler took 105ms
```

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

Yes

**Comment by ekuland** [comment] 2023-03-06 04:13
I'm unsure how people keep having a similar issue, but the easiest way to fix it is to start what the game thinks you're doing and immediately stop it.
Went ahead and did that for you, just in case, but I don't have your modlist, so if you had any content mods, stuff in them may be nuked: https://melvoridle.com/save/3yZPPSTt

**Comment by mibanez** [comment] 2023-03-06 13:03
it worked! thanks @ekuland 🙌🏼

**Comment by coolrox95** [comment] 2023-03-25 09:47
Duplicate of #2779

**Closed by coolrox95** 2023-03-25 09:47 UTC
Labels: bug, Duplicate
