### ISSUE TITLE
[Bug]: Typo on Herblore mastery list

### ISSUE THREAD

**Issue by BrianMahocker** [MelvorIdle/melvoridle.github.io#2744] opened 2022-10-21 12:55 UTC
### Describe the bug

underscore in Multicooker Potion name

### Reproduction Steps

open the list

### Expected behaviour

no underscore

### Screenshots

![image](https://user-images.githubusercontent.com/54864836/197200555-da377c75-dcfa-4825-9c57-4f9d98d1ea31.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-10-23 16:21
Duplicate of #2730

**Closed by coolrox95** 2022-10-23 16:21 UTC
Labels: bug, Duplicate
