### ISSUE TITLE
[Bug]: <Automatically equip food after it's cooked isn't working>

### ISSUE THREAD

**Issue by TwinPurple** [MelvorIdle/melvoridle.github.io#4301] opened 2024-06-11 14:25 UTC
### Describe the bug

I'm cooking shark and have the perfect shark equipped. The "Automatically Equip" option is selected, however the perfect shark is only going to the bank. 

### Screenshots

![Screenshot_20240611-092146](https://github.com/MelvorIdle/melvoridle.github.io/assets/166849284/54afc331-b0d1-4a40-be1c-52e9e226f6ef)
![Screenshot_20240611-092202](https://github.com/MelvorIdle/melvoridle.github.io/assets/166849284/487709d2-20cb-4a2b-b311-1da2e974b9eb)
![Screenshot_20240611-092214](https://github.com/MelvorIdle/melvoridle.github.io/assets/166849284/e0f041db-164d-4cec-92d3-0beef3f735e7)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11212

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-06-11 20:55
Duplicate of #4298

**Closed by coolrox95** 2024-06-11 20:55 UTC
Labels: bug, Duplicate
