### ISSUE TITLE
[Bug]: Impending Darkness & Combat

### ISSUE THREAD

**Issue by NotRGB** [MelvorIdle/melvoridle.github.io#1876] opened 2021-12-05 05:04 UTC
### Describe the bug

I stumbled upon a bug earlier where my character starts Impending Darkness without requirements met when starting a golbin raid while idling combat. I was idling spider dungeon, started golbin raid, passed 1 round and left, ID was in progress after. I stopped the event and tried again to make sure that's what it was.

There's also another user who ran into this same issue on Discord, except the variable is that he was doing general slayer tasks when starting a raid. So it appears to be all combat in general it's happening with.

### Reproduction Steps

> Start training combat (spider dungeon is what I was in)
> Start golbin raid
> End golbin raid

Impending Darkness will be activated when you return to combat screen.

### Screenshots

https://ibb.co/jVnBnRX

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1361

### Are you using any scripts or extensions?

No

**Comment by AaronLoew** [comment] 2021-12-08 21:28
I ran into this same bug except I was in crafting. I did however notice that I had the "Browse Combat Area" tab open in the combat area when I started the raid. The tab was also showing in the raid and I was able to click through each region/monster/drop. I think it has more to do with this window being open rather than training combat specifically.

I just tested with the other two tabs being open when entering the golbin raid event and each had the same result. The tab was visible on the raid page, leave raid, go back to combat window and the darkness event says it has started even though I do not meet the requirements.

**Comment by NotRGB** [comment] 2021-12-08 21:40
> 

I agree with you there. Same issue happened yesterday while I was doing fletching w/ combat screen open.

I'm not code savvy, but it almost seems like bc golbin raid uses a fixed level system, maybe the game interprets this as having max stats, or it breaks the original EXP based system we normally use. So then when you leave the raid, the game either clings to the fixed level system (having done multiple levels or "rounds" in the regular game could assume max stats since you level up every round), or something similar to that nature. I'm probably way off and sound like a fool. Definitely curious though!

**Comment by setters-choss** [comment] 2022-01-07 06:51
Sorry if I'm overstepping here: I debugged this and found where this is happening in the code. 

It's happening in `RaidManager#toggleUIOn()`. In this method, the code is un-hiding all the normal combat elements once the golbin raid is no longer running with:
```
this.toggleOffSelectors.forEach((selector)=>{
    $(selector).removeClass('d-none');
}
```
The problem is that `this.toggleOffSelectors` includes the impending darkness event UI selector, `#combat-event-menu`.  There should be logic to check `combatManager.isEventActive` before showing the `#combat-event-menu` element.

**Comment by coolrox95** [comment] 2022-01-30 05:24
Duplicate of #1763

**Closed by coolrox95** 2022-01-30 05:24 UTC
Labels: Duplicate
