### ISSUE TITLE
Numbers misformatted above 1,000

### ISSUE THREAD

**Issue by BinarySpike** [MelvorIdle/melvoridle.github.io#1060] opened 2021-06-18 22:31 UTC
**Describe the bug**
When you select an item to craft, such as a nature rune, and your current supply is 11,234.  It will display 11,234. (Note the locale specific comma).  If you then begin crafting nature runes, it will then display a number like 11241 (note, no comma).

**To Reproduce**

- Select nature rune.
- Look at amount owned.
- Begin crafting
- Look at amount owned.

**Expected behavior**
Numbers remain consistently formatted

**Browser**
Steam client

**Comment by Lanny** [comment] 2021-06-21 15:19
Also reproducible on web, same issue as #1048

**Comment by coolrox95** [comment] 2021-09-05 01:50
Duplicate of #1048

**Closed by coolrox95** 2021-09-05 01:50 UTC
Labels: Duplicate
