### ISSUE TITLE
[Bug]: Township Task available for completion notification not going away

### ISSUE THREAD

**Issue by Perrin3088** [MelvorIdle/melvoridle.github.io#4293] opened 2024-06-11 11:09 UTC
### Describe the bug

The ! under tasks indicating you have a task available for completion persisted after I turned in a task.

### Reproduction Steps

Township, accomplish a task, turn in the task (I had done the task for collecting arrows, because I was thieving the bandits last night)
! indicator persists.

### Expected behaviour

! Indicator is expected to go away immediately upon turning in task.
I left the township and came back, and waited for the tick to tick and left and came back.
Task Indicator went away on closing/reopening the game.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/131163250/77cf2357-48c7-4731-9b23-d67689912055)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11207

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-06-11 21:01
Duplicate of #4292

**Closed by coolrox95** 2024-06-11 21:01 UTC
Labels: bug, Duplicate
