### ISSUE TITLE
[Bug]: App fails to reopen after switching

### ISSUE THREAD

**Issue by danljungstrom** [MelvorIdle/melvoridle.github.io#4523] opened 2024-07-19 10:12 UTC
### Describe the bug

After switching app and returning, the app fails to reload and just shows a white screen. Has to be closed out and restarted.

The non beta version doesn't have this issue.

Samsung S22+ on Android 14

### Reproduction Steps

1. Play the game
2. Switch to another app
3. Switch back to Melvor
4. The app never loads up
5. Close the app completely
6. Start Melvor

### Expected behaviour

1-3 without 4-6

### Screenshots

![Screenshot_20240719_120757_Melvor Idle](https://github.com/user-attachments/assets/9af840ca-9fae-40e5-b36a-66e7e2804b16)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11585

### Are you using any mods?

Yes

**Comment by MelvorIdle** [comment] 2024-08-12 09:36
Duplicate of #4322 (Closing this one to clean issues)

**Closed by MelvorIdle** 2024-08-12 09:36 UTC
Labels: bug, Native Bug - Android
