### ISSUE TITLE
[Bug]: Can't read Impending Darkness book

### ISSUE THREAD

**Issue by mac-chaffee** [MelvorIdle/melvoridle.github.io#3105] opened 2022-12-19 23:17 UTC
### Describe the bug

After completing Impending Darkness, when I click "Read Item" on the book, nothing happens for me.

I tested on both iOS and Firefox Desktop. On Firefox, no errors appeared in the console when I clicked the "Read Item" button.

### Reproduction Steps

1. Complete Impending Darkness
2. Go to bank
3. Select the "Impending Darkness" book
4. Click "Read Item"

### Expected behaviour

Modal opens with the text of the book

### Save Link

https://melvoridle.com/save/SGRzy5bZ

### Console output

None

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4970

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-12-21 01:11
Duplicate of #2783

**Closed by coolrox95** 2022-12-21 01:11 UTC
Labels: bug, Duplicate
