### ISSUE TITLE
[Bug]: Farming levels lost when purchasing red charms

### ISSUE THREAD

**Issue by carlborrett** [MelvorIdle/melvoridle.github.io#3434] opened 2023-05-31 12:11 UTC
### Describe the bug

I signed in today after >1 year on the Opera web browser. I played normally and then decided to try some summoning, making some goblin thieves after I found the tablet. After purchasing some red charms in the shop I ran out and needed to purchase more, I clicked the button in the summoning skill panel to purchase more red charms, typed in "60" as the custom amount and hit enter on my keyboard. This lead to the page being refreshed and once I loaded back my farming had dropped from 99 to 48. I realised this as I went to plant some herbs after mine grew and was unable to plant my high level herbs.

I have attached some screenshots to show that I:
1. Have a farming skillcape
2. Have snape grass seeds planted (61 farming needed)
3. Have lost a significant amount of xp and now sit at the amount of xp corresponding to my level
![image_2023-05-31_130717586](https://github.com/MelvorIdle/melvoridle.github.io/assets/78092291/cdf301b8-7ad1-49bc-a21a-7ffe7b339e0e)
![image_2023-05-31_130743660](https://github.com/MelvorIdle/melvoridle.github.io/assets/78092291/0d223e48-613a-4de2-9730-3bd49688b100)

### Reproduction Steps

1. Go to summoning
2. Click to buy red charms on the goblin thief
3. Purchase the custom amount of "60"
4. Click enter on the keyboard to refresh web page

I have tried this again and it no longer affects my levels when done. This could have also been caused by me levelling a new skill that I did not have access to before (summoning).

### Expected behaviour

Screen will refresh. I do not think this is easily replicated without an old account.

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/TnCxvN9t

### Screenshots

Screenshots attached above

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [X] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-08-26 16:15
Duplicate of #3383

**Closed by coolrox95** 2023-08-26 16:15 UTC
Labels: bug, Duplicate
