### ISSUE TITLE
Inventory item menu freeze

### ISSUE THREAD

**Issue by NotArcanus** [MelvorIdle/melvoridle.github.io#48] opened 2019-11-19 22:04 UTC
**Describe the bug**
When the inventory shifts while an item's menu is open the menu freezes and can't close and interacting with it causes other bugs.

**To Reproduce**
1. Get 2 and only 2 of some type of fish
2. Click on Quick Sort Bank
3. Go to Cooking
4. Choose the fish with 2
5. Cook All
6. Quickly open bank and pull up an item menu (on some gloves for example)
7. When the inventory moves strange things start to occur

**Screenshots**
![https://photos.app.goo.gl/GgPZ3WqvEKYXD45x6](https://lh3.googleusercontent.com/rccwLAGZ24V53Rg79jBsNULmqLzyiwqKT99mmY-zDN-Nr1DmutS-9h2CoEpbpnudoibKoChuCgQS39BqSU15sKEMM-tCCrE6tp-3iTSN1QYSJyz9aPkyXD8XaapqvR_zKR0E7eo8=w2400)

**Comment by PegasusEpsilon** [comment] 2019-12-09 06:36
I experienced something like this a little while ago. I just deleted the popup dialog in the DOM tree, but i think most players would not have that option.

Tracking it down and stomping it out might be tricky, but it probably should be done.

**Comment by mrDLSable** [comment] 2019-12-09 06:41
Wasn't this fixed in 0.10 or 0.9 @TheMalcs @MelvorIdle ?

**Comment by PegasusEpsilon** [comment] 2019-12-09 06:42
If it was, then the fact that the issue is still open is the new bug 😂

**Closed** 2020-11-15 06:24 UTC
Labels: bug
