### ISSUE TITLE
[Bug]: <title>Deity reset, Township tasks reset, cannot plant Herbs

### ISSUE THREAD

**Issue by LegendrebornMelvor** [MelvorIdle/melvoridle.github.io#2731] opened 2022-10-21 03:16 UTC
### Describe the bug

I play on mobile and while trying to open the app I encountered an error where the game initially thought I didn't buy the DLC. I logged out, logged back in, and had all of my DLC progress restored but equipped items in inventory were unequipped, causing bank to be overflowing immediately. I then noticed that my Town in Township had its deity switched from Glacia to None, causing a lot of my production to take a dip because no bonuses were active. I also noticed that all of my task progress had reset. Prior to the wipe I was almost completely finished with the Easy tasks, did several tasks in the other remaining categories, and completely finished the Township tutorial. Despite my level being in the high 50's the game now recognizes me as a player who has never played Township before and is making me do the tutorial. The third thing I've noticed is that I cannot plant herbs anymore in Farming. I get the notification within the Farming tab that herbs are ready to harvest but 1: there is nothing to harvest and 2: I cannot plant any seeds. I have effectively stopped playing the game entirely and will not be making any more progress since I don't want to further bug my save.

### Reproduction Steps

Unsure...?

### Expected behaviour

Unsure...?

### Save Link

https://melvoridle.com/save/4oKDBzIV

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-10-21 04:54
Duplicate of #2731 and #2693

**Closed by coolrox95** 2022-10-21 04:54 UTC
Labels: bug, Duplicate
