### ISSUE TITLE
Hid skills by accident and now can't access them. Mobile

### ISSUE THREAD

**Issue by Hubbyy96** [MelvorIdle/melvoridle.github.io#2536] opened 2022-07-19 15:54 UTC
### Describe the bug

Clicked on the little eye icon on the skills tab by accident and now the title has gone and I can't access them. I can click the eye one the combat and they go away but the title stays so I can enable them again

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2076

### Are you using any scripts or extensions?

No

**Comment by adibarra** [comment] 2022-07-19 20:13
Issue is a duplicate of #2513

**Comment by MelvorIdle** [comment] 2022-10-19 05:15
Fixed as of v1.1. Please open a new report if issue persists.

**Closed by MelvorIdle** 2022-10-19 05:15 UTC
Labels: bug
