### ISSUE TITLE
[Bug]: <Disable non combat skills>

### ISSUE THREAD

**Issue by Remwulf** [MelvorIdle/melvoridle.github.io#2538] opened 2022-07-20 20:55 UTC
### Describe the bug

Hiya,

Whenever i disable non combat skills, i cant reenable them without relogging.

### Reproduction Steps

Go to left side panel
Click the hide button for "Non Combat"
It does not appear like combat skills does if you hide them, have to relog to re enable them.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

?2076

### Are you using any scripts or extensions?

No

**Comment by adibarra** [comment] 2022-07-21 17:52
Issue is a duplicate of #2513

**Comment by MelvorIdle** [comment] 2022-10-19 05:15
Fixed as of v1.1. Please open a new report if issue persists.

**Closed by MelvorIdle** 2022-10-19 05:15 UTC
Labels: bug
