### ISSUE TITLE
Cooking Offline Doesn't Work (active cooking)

### ISSUE THREAD

**Issue by Krydax** [MelvorIdle/melvoridle.github.io#1512] opened 2021-10-25 21:13 UTC
**Describe the bug**
I literally come back after hours offline to discover that 0 cooking experience has been gained, and no cooking has been done (active cooking)

**To Reproduce**
0. I'm on mobile, but I've seen this bug between mobile & web version, as well as on mobile only
1. Start cooking Manta Rays
2. Cloud save, wait a few secs after it says "cloud save successful", and then exit the app.
3. Load cloud save on web version OR phone, and either way I have 0 cooking experience, 0 manta rays cooked.
4. Go to fire and see that the manta recipe isn't even selected. It's like it somehow un-selects the recipe and then cooks nothing for the whole offline time.

**Expected behavior**
The manta rays getting cooked while offline, of course

**Screenshots**
Nothing interesting here. I have a magic cooking fire, no furnace, and the basic pot.

**Browser**
Irrelevant because it happens on mobile alone, but chrome (newest version since it bugged me to update it)

**Console output**
again, happens on mobile, but heres the console after the bug happening loading the cloud save from chrome: 

style.css:1 Failed to load resource: the server responded with a status of 404 ()
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1209:65 Connected to PlayFab successfully
cloud.js?1209:66 PlayFab Connected: Krydax
save.js?1209:10 Removed old local storage keys.
save.js?1209:54 set force reload to 0
combatManager.js?1209:1 Combat Manager Built...
raidManager.js?1209:1 Golbin Raid Manager Built...
save.js?1209:10 Removed old local storage keys.
save.js?1209:14 Loading Save Game...
save.js?1209:14 Save Game Loaded...
main.js?1209:5 Game Loaded
cloud.js?1209:65 Connected to PlayFab successfully
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1209:66 PlayFab Connected: Krydax
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cloud.js?1209:7 Synchronising with Cloud

**Are you using any scripts?**
no

**Comment by coolrox95** [comment] 2021-10-30 06:52
Duplicate of #1471

**Closed by coolrox95** 2021-10-30 06:52 UTC
Labels: Duplicate
