### ISSUE TITLE
[Bug]: Missing image in offline progress notification

### ISSUE THREAD

**Issue by bob8372** [MelvorIdle/melvoridle.github.io#2129] opened 2022-01-31 21:28 UTC
### Describe the bug

Progress update when returning from offline missing image at the top showing skill icon. 

### Screenshots

![41FDE300-6F32-4359-B899-915FDF6826D2](https://user-images.githubusercontent.com/36902041/151875830-2a805ac6-9bf8-4059-a954-4f89536fed27.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-09 18:08
Duplicate of #2180

**Closed by coolrox95** 2022-03-09 18:08 UTC
Labels: bug, Duplicate
