### ISSUE TITLE
[Bug]: tooltip forbid moving in bank.

### ISSUE THREAD

**Issue by Polyphonus** [MelvorIdle/melvoridle.github.io#4610] opened 2024-08-30 06:54 UTC
### Describe the bug

On the mobile app, any touch on an item launch a tooltip that stick and forbid moving items between tabs. 

### Reproduction Steps

1. Go to bank
2. Touch an item
3. Try to move your finger 

### Expected behaviour

Disappearance of the tooltip and item able to move

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11753

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-09-03 20:01
Duplicate of #4593

**Closed by coolrox95** 2024-09-03 20:01 UTC
Labels: bug, Duplicate
