### ISSUE TITLE
Magic Bones show wrong amout of prayerpoints gained by burying for eacht bone

### ISSUE THREAD

**Issue by DmitriyVdE** [MelvorIdle/melvoridle.github.io#1347] opened 2021-09-12 23:22 UTC
**Describe the bug**
Magic Bones show wrong amount of prayer points (0) that will be gained by burying each Magic Bone.

**To Reproduce**
1. Click on 'Magic Bones' in inventory

**Expected behavior**
Magic Bones give 10 prayer points in stead of 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/43698501/133005805-aad4db01-ba4d-44ac-81e4-2bff65f26de2.png)

**Browser**
Google Chrome Version 93.0.4577.63

**Console output**
/

**Are you using any scripts?**
No

**Comment by coolrox95** [comment] 2021-09-12 23:26
Duplicate of #1327

**Closed by coolrox95** 2021-09-12 23:26 UTC
Labels: Duplicate
