### ISSUE TITLE
[Bug]: Mining not mining

### ISSUE THREAD

**Issue by tea-sheep** [MelvorIdle/melvoridle.github.io#1647] opened 2021-11-11 23:35 UTC
### Describe the bug

Whenever I click on any ore the little grey bar fills up, then just sits filled. The ore still has health, I'm just not getting anything.

Won't work even when I reload the page or switch between tasks

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by Nomad7** [comment] 2021-11-12 12:46
I am also having this issue. It first occurred at some point during my rotation between mining, smithing, and the occasional fishing or summoning - but I'm not sure if there was any specific triggering behavior since I'd been doing that sort of thing for most of the day.

The expected results are that rocks should be mined successfully. The observed results are that the mining bar fills up, then nothing happens (rock health is not depleted, mining bar does not reset, etc). This occurs regardless of which rock I attempt to mine, and refreshing the page does not change the behavior.

I am also using chrome, and am currentinly on v1.0?1285, with no scripts or extensions for the game. 

Screenshot of the full-bar-and-nothing-happens state (all other rocks have full hp):
![image](https://user-images.githubusercontent.com/3387240/141469319-bcfe8eaa-c0a2-47a5-a7cb-e766050ba791.png)

**Comment by MelvorIdle** [comment] 2021-11-13 01:08
Can you pleae confirm this is still occuring with the recent updates? Game is now on version ?1285 with more hotfixes applied.

**Comment by Ventron** [comment] 2021-11-13 03:16
I'm having the same issue (can't mine). I went into firemaking and noticed that the bonfire is automatically resetting without user input. I have controlled heat potion II in my inventory, but it's not active, although the bonfire is still not using logs. I also can't switch to different logs, or burn logs.

**Comment by Nomad7** [comment] 2021-11-13 12:41
> Can you pleae confirm this is still occuring with the recent updates? Game is now on version ?1285 with more hotfixes applied.

I was observing this issue in ?1285 (as mentioned in my post above), but now on v1.0?1290 my mining appears to be working correctly again. thanks!

**Comment by ARHunter** [comment] 2021-11-13 12:48
Confirming that bug still exists in version ?1290. Mining bar fills and and unfills, then stays unfilled. No items received, and action is not repeated. Same for all mining nodes.

**Comment by fuzzybrownie** [comment] 2021-11-14 02:42
I can also confirm that this happened right after I installed the v1.0. I am playing on Android phone.

**Comment by DexxyAU** [comment] 2021-11-14 05:28
Ok so I think Ive found a way to replicate the bug. It seems if you load from a cloud save this bug happens but if you load from a local save it doesn't. Not sure if it's the same for anyone else but this 100% of the time recreates this bug for me.
Playing v1.0 on steam and on a s20. Bug persists on both and is replicatable in the same way on both.

**Comment by MelvorIdle** [comment] 2021-11-14 05:58
> Ok so I think Ive found a way to replicate the bug. It seems if you load from a cloud save this bug happens but if you load from a local save it doesn't. Not sure if it's the same for anyone else but this 100% of the time recreates this bug for me.
> Playing v1.0 on steam and on a s20. Bug persists on both and is replicatable in the same way on both.

This doesn’t replicate it for me unfortunately.

Can you please export your save and send me the text file to investigate?

**Comment by EricBucheit** [comment] 2021-11-14 06:05
Same happened to me right after i got the gem gloves. It was working fine, i put the app in the background, and when i opened it a couple minutes later it had this issue. Tried completely closing and loading local save and had no luck in fixing. Running beta 1.0 on iphone 11.

**Comment by EricBucheit** [comment] 2021-11-14 06:11
Okay so i fixed mine. What i did was loaded the cloud save which happened to still be stuck mining. Stopped the mining, so no tasks were active and manually saved to the cloud. Then i closed and reopened the app, loaded the cloud save, and it worked afterwords. Hope this helps.

**Comment by MelvorIdle** [comment] 2021-11-15 02:22
Still looking for someone's save to attempt to fix this. Only send the save if you are experiencing the bug. Thanks!

**Comment by Jerabi-Menna** [comment] 2021-11-15 21:37
[mining bug save.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/7541794/mining.bug.save.txt)
Using my current save i currently cant mine anything.

**Comment by MelvorIdle** [comment] 2021-11-16 01:04
I have received a save that apparently had the bug, but was unable to reproduce said bug with that save. I am confident the bug that caused this to occur has been fixed, but old saves that ran into the bug are still experiencing it.

Here is how you can potentially solve it:
1) Export your local character and reimport it over the existing save to "refresh" it.
2) Force sync your save to the cloud, delete the local save then load the cloud save.

I will leave this open for another 24 hours

**Comment by corpandrew** [comment] 2021-11-16 05:11
Just had this issue happen.

**Comment by MelvorIdle** [comment] 2021-11-16 05:27
> Just had this issue happen on 1319. Let me know if you need more info, I don't think it's anything within the save, as it worked when exporting/importing the existing file. There must be some local state issue messing up the logic

Please send me your save

**Comment by Sprayer115** [comment] 2021-11-18 20:18
[save.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/7565729/save.txt)
Having the same Issue

**Comment by MelvorIdle** [comment] 2021-11-22 01:27
We have now applied some new hotfixes to the game. I believe this issue is now fixed.

**Closed** 2021-11-24 02:14 UTC
Labels: bug
