### ISSUE TITLE
Bank Tab Icons sometimes don't update

### ISSUE THREAD

**Issue by Barragek0** [MelvorIdle/melvoridle.github.io#734] opened 2021-03-05 15:59 UTC
Selling everything in a tab or moving them to new tabs will reset the bank tab icon, if you have an item registered to be added to that tab when received, the tab icon doesn't seem to update (was tested using gem gloves, might update correctly via other methods).

**Comment by coolrox95** [comment] 2021-09-05 01:08
Duplicate of #502

**Closed by coolrox95** 2021-09-05 01:08 UTC
Labels: Duplicate
