### ISSUE TITLE
Not able to harvest or plant herbs

### ISSUE THREAD

**Issue by huntersusername** [MelvorIdle/melvoridle.github.io#2733] opened 2022-10-21 04:49 UTC
### Describe the bug

Right after the update and I switched over to the new SEMI Auto Farming mod and I'm not able to harvest or plant. My Allotments and Trees work fine, it's just the Herbs that are bugged. I was able to buy more Herb plots and they are working fine. My other character's farming is working fine.

### Save Link

https://melvoridle.com/save/2z2BLGdx

### Screenshots

![image](https://user-images.githubusercontent.com/17463557/197114357-15dbbce4-0ca2-4308-9807-0a8c5f86757c.png)

![image](https://user-images.githubusercontent.com/17463557/197114273-b1f421c1-597f-4734-9cec-a341290437e7.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-10-21 04:52
Duplicate of #2693

**Closed by coolrox95** 2022-10-21 04:52 UTC
Labels: bug, Duplicate
