### ISSUE TITLE
[Bug]: <title> Astrology info tab not displaying

### ISSUE THREAD

**Issue by Glumored** [MelvorIdle/melvoridle.github.io#3057] opened 2022-12-02 17:29 UTC
### Describe the bug

When i tap the icon in Astrology tab, no info/tips panel shows up. (Like the other skills do)

### Reproduction Steps

1. Touch to Astrology tab
2. Touch on icon in upper left corner 
3. No popup shows

### Expected behaviour

similar as the other skills a list with information and tips about the astrology skill

### Screenshots

![1B962981-023D-4FF5-842C-A9B4EC75C98F](https://user-images.githubusercontent.com/119694130/205350688-b56fe14f-c424-4e61-906f-4e7ec2e33a2d.jpeg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2022-12-21 01:07
Duplicate of #2859

**Closed by coolrox95** 2022-12-21 01:07 UTC
Labels: bug, Duplicate
