### ISSUE TITLE
[Bug]: Game process not shutting down 

### ISSUE THREAD

**Issue by Trummel123** [MelvorIdle/melvoridle.github.io#1814] opened 2021-11-27 19:14 UTC
### Describe the bug

The game process stays active after closing the game on the steam version. I've had numerous occasions  where I have 2 or 3 processes of the game still running in my task manager while the steam client says that the game isn't open.

### Reproduction Steps

Run steam version, close the game and check task manager.

Doesn't happen every time I close the game oddly enough

### Expected behaviour

The process should end every time I close the game.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment] 2021-11-29 01:12
Duplicate of #1712

**Closed by MelvorIdle** 2021-11-29 01:12 UTC
Labels: bug
