### ISSUE TITLE
[Bug]: <An error occured while processing ticks offline: Active Skill: COOKING>

### ISSUE THREAD

**Issue by salva3s** [MelvorIdle/melvoridle.github.io#2247] opened 2022-02-28 12:43 UTC
### Describe the bug

Erro at login after 4h offline

### Console output

An error occured while processing ticks offline:
Active Skill: COOKING
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'hasAnimation')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'hasAnimation')
    at getItemMedia (https://melvoridle.com/assets/js/game/main.js?1804:282:58)
    at https://melvoridle.com/assets/js/built/game.js?1804:88:1840
    at Map.forEach (<anonymous>)
    at Game.createOfflineModal (https://melvoridle.com/assets/js/built/game.js?1804:88:1695)
    at https://melvoridle.com/assets/js/built/game.js?1804:70:812
Current Equipment:
Helmet: Chefs_Hat
Platebody: Cooking_Apron
Platelegs: Adamant_Platelegs
Boots: Adamant_Boots
Weapon: Chefs_Spoon
Shield: Ice_Shield
Amulet: Amulet_of_Fishing
Ring: Aorpheats_Signet_Ring
Gloves: Cooking_Gloves
Quiver: Fishing_Hook
Cape: Obsidian_Cape
Summon2: Summoning_Familiar_Mole

Skill Information:
Is Active: true

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1804

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-01 23:07
Duplicate of  #2242

**Closed by coolrox95** 2022-03-01 23:07 UTC
Labels: bug, Duplicate
