### ISSUE TITLE
[Bug]: All firemaking xp and mastery xp is off

### ISSUE THREAD

**Issue by LordHutch** [MelvorIdle/melvoridle.github.io#2924] opened 2022-11-06 22:43 UTC
### Describe the bug

The firemaking xp and mastery xp displayed for every log is higher than the actual firemaking xp and mastery xp that is being given on the account.  This is with or without any jewelry on and across all log types.

### Reproduction Steps

Pick any log.
Burn the log.
See that the firemaking xp and mastery xp awarded is less than displayed

### Expected behaviour

The xp displayed to be awarded.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by nzewiski** [comment] 2022-11-29 19:09
+1
Seeing the same for v1.1.1 (?4928) on iOS and in the browser client(s).

**Comment by coolrox95** [comment] 2022-12-20 23:44
Duplicate of #2746

**Closed by coolrox95** 2022-12-20 23:44 UTC
Labels: bug, Duplicate, Visual Bug
