### ISSUE TITLE
Pet system

### ISSUE THREAD

**Issue by Eusmusia** [MelvorIdle/melvoridle.github.io#64] opened 2019-11-27 09:37 UTC
Adding a simple pet system would give options for more content and unique drops.

Some pets could just be for show (in the equip screen), others could help with combat such as increasing Melee Str or adding more to double catch rate. Some of these pets could be obtained from the skill itself, Skilling Pets, others could be boss pets.

Combat Pets would have a chance to attack during combat, adding their damage to yours. Example is your max hit is 4, and Combat Pet A has a max hit of 3, your possible max hit with Pet Proc would be 7. Other pets could increase Range or Melee accuracy, defensive stats, increase HP regen. Boss pets would be considered combat pets, given their way to acquire.

Skilling pets would help with their respective skill. Fishing pet could increase chances for casket, further increase chances for a double catch, decrease fishing time like the rods or increase your catch rate, Woodcutting pet would increase nest chance or double logs.

These are just a few examples on how pets could work.

**Comment by mrDLSable** [comment] 2019-11-27 10:15
Duplicate of #40. Please post your suggestions as a comment on that issue :)

**Closed by mrDLSable** 2019-11-27 10:15 UTC
Labels: Suggestion
