### ISSUE TITLE
[Bug]: Passive Offline Cooking

### ISSUE THREAD

**Issue by Divinusproelia** [MelvorIdle/melvoridle.github.io#1587] opened 2021-11-08 23:29 UTC
### Describe the bug

During Offline Progression, passive cooking produces items in stockpile even when out of ingredients

### Reproduction Steps

Get enough ingredients to perform one passive cook, this locks the production into that item.
Exit game while actively cooking something else, which you have plenty of ingredients for.
Upon return, you will have gained the normal amount of passive cooking items as if you had ingredients for them.

### Expected behaviour

I do not expect to receive cooking items once I run out of ingredients.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

?1217

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment] 2021-11-09 01:27
Duplicate of #1393

Closing this one to clean up :)

**Closed by MelvorIdle** 2021-11-09 01:27 UTC
Labels: bug
