### ISSUE TITLE
When draggings things in the bank it get's all messed up

### ISSUE THREAD

**Issue by Yosho1** [MelvorIdle/melvoridle.github.io#1379] opened 2021-09-26 12:49 UTC
**Describe the bug**
When you attempt to drag an item in the bank interface to a new slot or a new tab. It will take a completely different item then the item you wanted to drag. Usually the item that is at the beginning of the row or the last item in the row. I'm running the steam version

**To Reproduce**
To reproduce this, simply attempt to drag a item to a new tab and it will drag the wrong item.

**Expected behavior**
It should drag the item I have selected not any other item

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No scripts are being used

**Comment by teknogeek** [comment] 2021-09-27 15:17
I noticed this same behavior with the following scenario:

- I am currently combat idle fighting Master Farmer's and collecting items with an Amulet of Looting
- Eventually, a new item that is not already categorized appears in `Tab 0`
- When I drag the new item to a different tab (i.e. `Tab 3`), the game will move the item from `Tab 1, Slot 0` to `Tab 3` instead of the item I dragged from `Tab 0`

**Comment by MelvorIdle** [comment] 2021-10-01 00:23
> I noticed this same behavior with the following scenario:
> 
> * I am currently combat idle fighting Master Farmer's and collecting items with an Amulet of Looting
> * Eventually, a new item that is not already categorized appears in `Tab 0`
> * When I drag the new item to a different tab (i.e. `Tab 4`), the game will move whatever item is in `Tab 1, Slot 0` to `Tab 4` instead of the item I dragged from `Tab 0`

Hmm, I can't seem to reproduce this bug following these steps. There must be another element I'm missing somewhere causing this to occur

**Comment by jshepler** [comment] 2021-10-02 12:45
For me, it works some times and other times it does the above. Makes it appear to be random. If so, good luck troubleshooting. (steam version for me too)

**Comment by MartijnCBV** [comment] 2021-10-02 22:15
> I noticed this same behavior with the following scenario:
> 
> * I am currently combat idle fighting Master Farmer's and collecting items with an Amulet of Looting
> * Eventually, a new item that is not already categorized appears in `Tab 0`
> * When I drag the new item to a different tab (i.e. `Tab 4`), the game will move whatever item is in `Tab 1, Slot 0` to `Tab 4` instead of the item I dragged from `Tab 0`

I have exactly the same problem but it only seems to happen the first time I move an item after I load the game.

**Comment by coolrox95** [comment] 2021-10-03 08:02
Duplicate of #1213

**Closed by coolrox95** 2021-10-03 08:02 UTC
Labels: Duplicate
