### ISSUE TITLE
[Bug]: battle progress windows are not aligned in Galaxy Fold5

### ISSUE THREAD

**Issue by bart123kr** [MelvorIdle/melvoridle.github.io#4333] opened 2024-06-13 00:00 UTC
### Describe the bug

A windows for battle progress and buttons are not aligned in external screen of Galaxy Fold 5. Please refer to attachment.
![Screenshot_20240611_121257_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/55540641/8e63d711-76dd-44d5-b0ae-f69642c44ae0)

### Expected behaviour

Size and location of the object should be aligned.

### Screenshots

![Screenshot_20240611_121257_Melvor Idle](https://github.com/MelvorIdle/melvoridle.github.io/assets/55540641/556a92c8-e6a9-4d2d-a357-70edc1e77173)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [ ] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11271

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2024-06-13 02:12
Duplicate of #4269

**Closed by coolrox95** 2024-06-13 02:12 UTC
Labels: bug, Duplicate, Visual Bug
