### ISSUE TITLE
HP regeneration doesn't work while offline

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1498] opened 2021-10-22 20:51 UTC
I was ~50% health in adventure mode and logged off while mining, came back hours later and was still half health but regen started to kick in since I was online.

**Expected behavior**
I don't see why HP regen should be excluded while offline.

**Browser**
Steam

**Comment by coolrox95** [comment] 2021-11-04 06:19
Duplicate of #1469

**Closed by coolrox95** 2021-11-04 06:19 UTC
Labels: Duplicate
