### ISSUE TITLE
[Bug]: Cannot drag 'bury' bar in Steam client

### ISSUE THREAD

**Issue by 10hpboii** [MelvorIdle/melvoridle.github.io#1617] opened 2021-11-11 08:50 UTC
### Describe the bug

As above, I have to individually click bury for each holy dust or I can log in to melvor on my phone and select all and bury.

### Screenshots

![image](https://user-images.githubusercontent.com/94106920/141267349-6ff4b908-b20c-4f53-93ed-8872067367bd.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1272

### Are you using any scripts or extensions?

No

**Comment by deathmettle** [comment] 2021-11-11 10:23
+1 for this bug. The slider bar works fine on android, however.

Which platforms are you experiencing this bug on?

Steam

Which version of the game are you experiencing this bug on?
Beta v1.0

Game Subversion
?1274

Are you using any scripts or extensions?
No

**Comment by 10hpboii** [comment] 2021-11-11 12:19
In Zoom 100% this drag bar works fine but at higher zoom eg. 120 or lower zooms (80) it doesn't work.

**Comment by deathmettle** [comment] 2021-11-11 12:28
> 
> 
> In Zoom 100% this drag bar works fine but at higher zoom eg. 120 or lower zooms (80) it doesn't work.

Are you specifically talking about monitor scale or a different type of zoom?

**Comment by coolrox95** [comment] 2021-11-11 20:08
Duplicate of #1625

**Closed by coolrox95** 2021-11-11 20:08 UTC
Labels: Duplicate
