### ISSUE TITLE
[Bug]: Offline Cooking Progress Bug

### ISSUE THREAD

**Issue by ekokind** [MelvorIdle/melvoridle.github.io#2278] opened 2022-03-02 13:45 UTC
### Describe the bug

Offline cooking progress bug while active and passive cooking. 

Only thought is that it possibly occurred because I ran out of flour while passive cooking offline? 

### Reproduction Steps

1. Set active cook for whales, passive cook for apple pie and hearty soup
2. Logged off 
3. 10 hours later
4.  Open game to error

### Console output

An error occured while processing ticks offline:
Active Skill: COOKING
Error Name: TypeError
Error Message: Cannot read property 'hasAnimation' of undefined
Stack Trace:
TypeError: Cannot read property 'hasAnimation' of undefined
    at getItemMedia (https://steam.melvoridle.com/assets/js/game/main.js?1819:282:58)
    at https://steam.melvoridle.com/assets/js/built/game.js?1819:88:1840
    at Map.forEach (<anonymous>)
    at Game.createOfflineModal (https://steam.melvoridle.com/assets/js/built/game.js?1819:88:1695)
    at https://steam.melvoridle.com/assets/js/built/game.js?1819:70:812
Current Equipment:
Helmet: Dragon_Helmet_T_G
Platebody: Dragon_Platebody_T_G
Platelegs: Dragon_Platelegs_T_G
Boots: Dragon_Boots_T_G
Weapon: Dragon_2H_Sword
Amulet: Amulet_of_Looting
Ring: Ancient_Ring_Of_Skills
Gloves: Dragon_Gloves
Quiver: Mithril_Arrows
Cape: Woodcutting_Skillcape

Skill Information:
Is Active: true

Selected Cooking Recipes:
Fire: 11
Furnace: 27
Pot: 24
Active Cooking Category: Fire
Passive Cooking Categories: Pot
Stockpile Contents:
Furnace: item: Apple_Pie qty: 865
Pot: item: Hearty_Soup qty: 4528

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1819

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-02 20:56
Duplicate of #2242

**Closed by coolrox95** 2022-03-02 20:56 UTC
Labels: bug, Duplicate
