### ISSUE TITLE
[Bug]: Astrology Reroll All Modifiers doesn't apply 30 stardust cost.

### ISSUE THREAD

**Issue by travis-struckhoff** [MelvorIdle/melvoridle.github.io#1641] opened 2021-11-11 17:59 UTC
### Describe the bug

When the user clicks Reroll All Standard Modifiers 1 stardust is deducted from the pool and the user receives the new modifiers in  the View All Active Modifiers dialog.

### Reproduction Steps

1. Open Astrology
2. Click Explore
3. Click Reroll All Standard Modifiers
4. 1 stardust is removed from the pool

### Expected behaviour

If one standard modifier is available, 31 stardust should be deducted from the pool.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1274

### Are you using any scripts or extensions?

No

**Comment by NototoHoshi** [comment] 2021-11-11 22:22
I think this is intended... why the hell would anyone pay 30*x + 1 to reroll everything (potentially messing up already existing good  rolls) if they could pay 30 for single reroll? I think the idea is that the "reroll all" is cheap (1 stardust) because it it unlikely you will get three good rolls, basically youll just get all random. So you should spam the full reroll for 1 until one of the modifiers :"hits" something you want (preferably max roll) and then you can use the 30 stardust rolls for the remaining two stars. Or if you feeling lucky, you can spam the full reroll until two of the stars "hit" and the use single rerolls for the last one. This pricing structure makes logical sense, hence I believe this is not a bug.

**Comment by travis-struckhoff** [comment] 2021-11-11 23:43
Yes that makes sense too. I thought it behaved like Farming Plant All.

**Comment by MelvorIdle** [comment] 2021-11-12 00:56
This is the intended mechanic - not a bug. Closing this report

**Closed by MelvorIdle** 2021-11-12 00:56 UTC
Labels: bug
