### ISSUE TITLE
Accuracy Rating set to NaN after death (Because I lost my weapon on death?)

### ISSUE THREAD

**Issue by indiglow** [MelvorIdle/melvoridle.github.io#952] opened 2021-04-28 19:36 UTC
**Describe the bug**
Only a visual glitch, but when I died during the final boss in the Fire God Dungeon, my Accuracy Rating in my stats section became "NaN".

**To Reproduce**
I'm not sure if it's a one-off and I don't really want to try it again haha.  Don't know if it's gear-specific, so just in case:
- Aeris God Helmet
- Aeris God Platebody
- Aeris God Platelegs
- Aeris God Gloves
- Aeris God Boots
- Infernal Cape
- Fury of Elemental Zodiac
- Aorpheat's Signet Ring
- Ancient Crossbow
- Ruby Bolts

EDIT: I lost my weapon on death

**Screenshots**
![NaN](https://user-images.githubusercontent.com/25508029/116462083-0f66e000-a837-11eb-9857-f22a75eb7ba3.PNG)

**Browser**
Steam version

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment] 2021-05-25 01:48
This may be fixed in the next update, as I am unable to reproduce on my test branch.

Feel free to reopen if you experience this bug again in the next major update.

**Closed by MelvorIdle** 2021-05-25 01:48 UTC
Labels: bug
