### ISSUE TITLE
"Cannot read properties of undefined..."

### ISSUE THREAD

**Issue by daBoogalue** [MelvorIdle/melvoridle.github.io#1511] opened 2021-10-25 19:45 UTC
**Describe the bug**
Error code please report.

**To Reproduce**
I was only able to reproduce this 2 times in a row, but not since then.

**Expected behavior**
I opened up my game to check on my whales that were cooking, but this error popped up saying it canceled my progress.

**Screenshots**
Screenshot supplied
![Screenshot_20211025-122057](https://user-images.githubusercontent.com/93158501/138760035-f07ceacf-5d71-4dd5-9a8e-2aff8bc8f267.png)

**Browser**
Mobile app

**Console output**
N/A

**Are you using any scripts?**
N/A

**Comment by coolrox95** [comment] 2021-11-04 08:46
Duplicate of #1478

**Closed by coolrox95** 2021-11-04 08:46 UTC
Labels: Duplicate
