### ISSUE TITLE
Shop cost text stays red even though I can afford it. (Visual bug)

### ISSUE THREAD

**Issue by winterknight31** [MelvorIdle/melvoridle.github.io#1335] opened 2021-09-09 16:23 UTC
**Describe the bug**
When I go to the shop certain things stay red.  For example I purchase the green dragonhide, which it lets me, but the leather requirement stays red.  It's just visual because I am still able to buy the green dragonhide even though I have the required amount of leather.  It also happens with the weird gloop.  I have enough compost, but the cost stays red.

**Expected behavior**
When I have the required amount of materials the cost should go green instead of staying red.

**Browser**
I am on Steam, but I logged into browser on Google Chrome and the problem is still there.

**Are you using any scripts?**
I am not using any scripts.

**Comment by coolrox95** [comment] 2021-09-12 23:31
Duplicate of #1300

**Closed by coolrox95** 2021-09-12 23:31 UTC
Labels: Duplicate
