### ISSUE TITLE
[Bug]: Clue Chaser's Insignia is not being generated

### ISSUE THREAD

**Issue by profcedar** [MelvorIdle/melvoridle.github.io#2687] opened 2022-10-19 18:18 UTC
### Describe the bug

The required items are being put in the first bank slot and in the correct order, but the Clue Chaser's Insignia is not being created.

![image](https://user-images.githubusercontent.com/82060053/196772852-06c432b1-91e5-4aea-a31d-79a7cfd5599b.png)

### Reproduction Steps

1. Obtain required items.
2. Place them in correct order in bank.
3. Wait.

### Expected behaviour

Clue Chaser's Insignia should be created and added to the bank,

### Save Link

https://melvoridle.com/save/rLqNoZ2O

### Screenshots

![image](https://user-images.githubusercontent.com/82060053/196772861-0f30a8c7-96dc-4835-8604-c4e65e25cf04.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4430

### Are you using any mods?

No

**Comment by l3vines** [comment] 2022-10-19 21:11
did you try moving an item to see if it does give an item when switching one of the 6.
Or also an other option is moving all the other items after those 6 from that banktab.

**Comment by profcedar** [comment] 2022-10-19 22:05
I tried moving them around, but I did not try to leave the bank tab with just those six. Will try and provide an update.

**Comment by profcedar** [comment] 2022-10-20 01:26
Tried this also, but it did not work:

![image](https://user-images.githubusercontent.com/82060053/196834546-f4b4312d-e4f5-48db-bb48-fc80068fa9a7.png)

This bug remains open.

**Comment by TheNumberOne** [comment] 2022-10-20 06:01
I am seeing the same issue on Steam v1.1 (?4465) even after disabling all mods.

Save link: https://melvoridle.com/save/7J5KwuEJ

**Comment by TheNumberOne** [comment] 2022-10-20 16:46
Btw, I tested reversing the order and it fixed it.

**Comment by coolrox95** [comment] 2022-10-21 02:08
Duplicate of #2650

**Closed by coolrox95** 2022-10-21 02:08 UTC
Labels: bug, Duplicate
