### ISSUE TITLE
[Bug]: Herblore potion tier not updating while offline

### ISSUE THREAD

**Issue by SimplyBLGDev** [MelvorIdle/melvoridle.github.io#2040] opened 2022-01-09 13:22 UTC
### Describe the bug

If the mastery for a potion in herblore changes while offline the generated potion will not update until the game is loaded, generating the previous tier potion for a longer time than intended

### Reproduction Steps

1. Idle Herblore on any non-tier IV potion
2. Come back after the mastery for the potion has surpassed a tier change threshold

### Expected behaviour

The previous tier potion will take the entire offline production time, dismissing the tier change

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by SimplyBLGDev** [comment] 2022-01-09 13:28
I'd assume since this is the case the preservation chance (or any other mastery bonuses) may not be updating as the mastery changes offline, that might be worth taking a look at (haven't tested it though)

**Comment by ekuland** [comment] 2022-01-09 16:10
Herblore is not tickbased, it all functions as it was the instant you logged off. Not a bug.

**Comment by MelvorIdle** [comment] 2022-01-11 01:05
This is a downside of the existing system and will be fixed with the tick-based transition that is slowly rolling out in coming updates.

**Closed by MelvorIdle** 2022-01-11 01:05 UTC
Labels: bug
