### ISSUE TITLE
Performing multiple skills at once

### ISSUE THREAD

**Issue by Tokato90** [MelvorIdle/melvoridle.github.io#1018] opened 2021-06-12 17:20 UTC
I noticed before when i was trying to do some runecrafting that i was also getting wood. The runecrafting stopped after two or three and when i seemed to switch focus off the game tab. 

Reproducing Issue
I tried to reproduce it to be sure but i could try, i knew i was woodcutting originally then went over to do some runecrafting.

Expected Behaviour
Woodcuttign to stop and runecrafting to continue.

Browser
Chrome Version 91.0.4472.77

Scripts
I am not using any scripts.

**Comment by coolrox95** [comment] 2021-09-12 23:29
Duplicate of #1063

**Closed by coolrox95** 2021-09-12 23:29 UTC
Labels: Duplicate
