### ISSUE TITLE
Multiple skills simultaneous leveling.

### ISSUE THREAD

**Issue by Alexdisagit** [MelvorIdle/melvoridle.github.io#1345] opened 2021-09-12 05:02 UTC
After resuming from offline mode multiple "What you earned while offline" pop ups appeared and seemed to be glitchy.

Afterwards I was able to have all skills and combats running simultaneously until I again went offline, to reset. 
All progress earnt was still there upon re-opening.

**Comment by coolrox95** [comment] 2021-09-12 23:28
Duplicate of #1063

**Closed by coolrox95** 2021-09-12 23:28 UTC
Labels: Duplicate
