### ISSUE TITLE
[Bug]: Game not fitting to screen size correctly

### ISSUE THREAD

**Issue by reddog7879** [MelvorIdle/melvoridle.github.io#2299] opened 2022-03-05 18:46 UTC
### Describe the bug

Game is enlarging itself on load up beyond size of screen.  Restarting phone brings it back to normal until the game is closed and then reloads itself enlarged again

### Expected behaviour

Game is supposed to fit screen

### Screenshots

![Screenshot_20220305-132756_Melvor Idle](https://user-images.githubusercontent.com/93557188/156896164-ae9ad538-be7f-4290-aedb-1f0dac99f76d.jpg)

### Console output

![Screenshot_20220305-132756_Melvor Idle](https://user-images.githubusercontent.com/93557188/156896187-f15c312a-adcd-42c4-8864-024a350bd5bb.jpg)
![Screenshot_20220305-133111_Melvor Idle](https://user-images.githubusercontent.com/93557188/156896191-c7954784-dbe8-4e58-be1b-659aa633de20.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1822

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-06 00:05
Duplicate of #2290

**Closed by coolrox95** 2022-03-06 00:05 UTC
Labels: bug, Duplicate
