### ISSUE TITLE
Golbin Thief/Minotaur potentially giving 10x intended gp in adv mode

### ISSUE THREAD

**Issue by mjsterling** [MelvorIdle/melvoridle.github.io#1070] opened 2021-06-20 18:03 UTC
User reported in main discord chat @ 3.40 am 21/06/21 receiving 5k gp in one attack with 2.1k max hit

**Comment by coolrox95** [comment] 2021-08-15 07:26
Duplicate of #1064

**Closed by coolrox95** 2021-08-15 07:26 UTC
Labels: Duplicate
