### ISSUE TITLE
[Bug]: Lost Agility Levels, Can't Use Agility

### ISSUE THREAD

**Issue by rm09boug** [MelvorIdle/melvoridle.github.io#3270] opened 2023-03-24 01:52 UTC
### Describe the bug

My agility skill was quite high (in the 80s I believe), and I was spending some mastery XP on future obstacles I wanted to build.  I reloaded my game after deciding to check out the mod manager, and my agility was reset to 3.  When I attempted to train agility, a large window covered my screen and told me to report the bug.

### Reproduction Steps

1. Go to agility tab.
2. Start training agility.
3. Error window pops up.

### Expected behaviour

I expect my agility score to be what it was and to train agility as normal.

### Save Link

https://melvoridle.com/save/XZZe8NY5

### Screenshots

<img width="1434" alt="Screenshot 2023-03-23 at 9 50 57 PM" src="https://user-images.githubusercontent.com/97362639/227404035-094c3700-20f2-4a62-8724-7ee2a2cfd2b3.png">

### Console output

An error occurred while rendering:
Active Action: melvorD:Agility
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'bar')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'bar')
    at MultiProgressBar.startSegmentAnimation (https://melvoridle.com/assets/js/built/agilityMenus.js?5064:50:201)
    at MultiProgressBar.animateFromTimer (https://melvoridle.com/assets/js/built/agilityMenus.js?5064:59:6)
    at Agility.renderProgressBar (https://melvoridle.com/assets/js/built/agility.js?5064:166:158)
    at Agility.render (https://melvoridle.com/assets/js/built/agility.js?5064:136:144)
    at https://melvoridle.com/assets/js/built/game.js?5064:180:63
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://melvoridle.com/assets/js/built/namespaceRegistry.js?5064:37:44)
    at Game.render (https://melvoridle.com/assets/js/built/game.js?5064:180:39)
    at Game.loop (https://melvoridle.com/assets/js/built/game.js?5064:196:35)
Current Equipment:
Helmet: melvorF:Necromancer_Hat
Platelegs: melvorF:Necromancer_Bottoms
Boots: melvorF:Necromancer_Boots
Amulet: melvorD:Amulet_of_Fishing
Ring: melvorD:Gold_Topaz_Ring
Gloves: melvorD:Cooking_Gloves
Cape: melvorD:Fishing_Skillcape

Action Information:
Is Active: true

Active Obstacle Tier: 1
Built Obstacles (tier|obstacleID):
0:melvorF:RopeClimb
1:melvorF:BalanceBeam
2:melvorF:PipeClimb
3:melvorF:CaveClimb
4:melvorF:CliffBalance
5:melvorF:TreeHop
6:melvorF:HeatTrap
Modding Enabled. Loaded mods:
Dev

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5064

### Are you using any mods?

No

**Comment by MelvorIdle** [comment] 2023-04-04 07:34
The provided save works fine for me using no mods. Can you double check the save still does not work?

**Comment by coolrox95** [comment] 2023-08-26 17:02
Duplicate of #3111

**Closed by coolrox95** 2023-08-26 17:02 UTC
Labels: bug, question
