### ISSUE TITLE
[Bug]: Cannot read property 'qty' of undefined

### ISSUE THREAD

**Issue by DizzieDawgie** [MelvorIdle/melvoridle.github.io#2183] opened 2022-02-12 22:48 UTC
### Describe the bug

Game came to a stop with "AN ERROR OCCURRED WHILE PROCESSING TICKS". See attached screenshot and copy/pasted error text from the game.

I quit and restarted the game, loaded my latest local save (which was only a couple minutes old) and continued without incident.

I'm using the Steam Beta client on macOS 12.2.1 (21D62) (both updated within the last couple of days) 

### Reproduction Steps

If I had to guess, it might be related to my current/next magic attack using up the last of the Mind runes. 

### Expected behaviour

I expect the game to just continuously spam me with messages saying I ran out of a rune like it usually does.

### Screenshots

![Melvor Error](https://user-images.githubusercontent.com/17185182/153731198-b7ced5a2-41e2-4d7b-a332-7ffc687f3db2.png)

### Console output

Text copy/pasted from the error message:

An error occurred while processing ticks:
Active Skill: COMBAT
Error Name: TypeError
Error Message: Cannot read property 'qty' of undefined
Stack Trace:
TypeError: Cannot read property 'qty' of undefined
    at BankHelper.addQuantity (https://steam.melvoridle.com/assets/js/built/utils.js?1532:46:119)
    at https://steam.melvoridle.com/assets/js/built/utils.js?1532:50:49
    at Array.forEach (<anonymous>)
    at BankHelper.consumeItems (https://steam.melvoridle.com/assets/js/built/utils.js?1532:50:27)
    at Player.consumeRunes (https://steam.melvoridle.com/assets/js/built/player.js?1532:123:98)
    at Player.attack (https://steam.melvoridle.com/assets/js/built/player.js?1532:100:68)
    at Player.act (https://steam.melvoridle.com/assets/js/built/character.js?1532:186:69)
    at Timer.tick (https://steam.melvoridle.com/assets/js/built/combatManager.js?1532:166:89)
    at Player.tick (https://steam.melvoridle.com/assets/js/built/character.js?1532:177:49)
    at Player.tick (https://steam.melvoridle.com/assets/js/built/player.js?1532:26:14)
Current Equipment:
Helmet: Fire_Acolyte_Wizard_Hat
Platebody: Fire_Acolyte_Wizard_Robes
Platelegs: Fire_Acolyte_Wizard_Bottoms
Boots: Fire_Acolyte_Wizard_Boots
Weapon: Magic_Wand_Basic
Amulet: Gold_Topaz_Necklace
Ring: Gold_Topaz_Ring
Gloves: Leather_Vambraces
Quiver: Steel_Arrows

Skill Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: 0
Is Attacking: false
Standard Spell Selected: 3
Ancient Spell Selected -1
Aurora Selected: 0
Curse Selected: 2
Active Prayers: None
Equipped Food:
Item: Salmon, Qty: 38
Item: Herring, Qty: 102
Item: Chicken, Qty: 118
-- End Player Information --
-- Start of Enemy Information --
Enemy: Chicken
Next Action: Attack
Next Attack: 0
Is Attacking: false
Standard Spell Selected: -1
Ancient Spell Selected -1
Aurora Selected: -1
Curse Selected: -1
-- End Enemy Information --
Current Area Type: Combat
Current Area ID: 0

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1532

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-07 19:33
Duplicate of #1815

**Closed by coolrox95** 2022-03-07 19:33 UTC
Labels: bug, Duplicate
