### ISSUE TITLE
[Bug]: Mobile game crashing constantly

### ISSUE THREAD

**Issue by MisterNooblet** [MelvorIdle/melvoridle.github.io#3093] opened 2022-12-15 08:51 UTC
### Describe the bug

a quick heads up..
I have a one plus 8 pro phone loaded with ram and a good processor this is no hardware issue cause i run 10x heavier games on it.

i load up the app it takes forever to load and lags like crazy than no matter which menu i go to it would crash after like 5 seconds , which is very frustrating specially cause i paid for the game and i cant even play it.

The more annoying part is that I wanted to get it for steam cause maybe on pc it would work.. 

But I'm not going to pay again.

### Reproduction Steps

1. Open the app
2. Wait for the freezing loading stage to finish
3. click something
4. wait for the long freeze to pass/app crash
5. repeat
6. get angry

### Expected behaviour

I expected the app to work as intended 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4970

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 06:23
Duplicate of #2694.

Please note that you do not have to repurchase the game on Steam to play on desktop, and can simply visit https://www.melvoridle.com/ in a browser. You will need to have a Cloud Account and have signed in on mobile first.

**Closed by coolrox95** 2023-03-25 06:23 UTC
Labels: bug, Duplicate
