### ISSUE TITLE
[Bug]: Very laggy and buggy on mobile

### ISSUE THREAD

**Issue by WildFearless** [MelvorIdle/melvoridle.github.io#2729] opened 2022-10-21 01:13 UTC
### Describe the bug

Im playing on android with the app from google play on a Z FOLD 4, brand new and it runs on android 12L (same as 12 but tweaked for when unfolded)

It lags when folded and unfolded, freezes every like 3 seconds its unplayable

### Reproduction Steps

Buy my phone (maybe others are the same)
Launch the game and try to play.
It will always freeze and lag for no reason

### Expected behaviour

Atleast a smooth gameplay since its a brand new phone capable of playing pretty demanding game... But ill try clearing cache as some people said

I want to point out im using mods but it was happening before i installed any

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4501

### Are you using any mods?

Yes

**Comment by coolrox95** [comment] 2022-10-21 04:50
Duplicate of #2694

**Closed by coolrox95** 2022-10-21 04:50 UTC
Labels: bug, Duplicate
