### ISSUE TITLE
[Bug]: goblin raid shop bug

### ISSUE THREAD

**Issue by taso4784** [MelvorIdle/melvoridle.github.io#2438] opened 2022-05-07 22:17 UTC
### Describe the bug

Item does not appear

### Save Link

https://melvoridle.com/save/eBWRQhId

### Screenshots

![image](https://user-images.githubusercontent.com/105132106/167273482-b6d6d126-97bb-411c-a9ec-8d0dd02e5d63.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [x] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1876

### Are you using any scripts or extensions?

no

**Comment by MelvorIdle** [comment] 2022-05-12 01:01
Duplicate of #2378

**Closed by MelvorIdle** 2022-05-12 01:01 UTC
Labels: bug
