### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Bobsagggit** [MelvorIdle/melvoridle.github.io#2160] opened 2022-02-06 10:11 UTC
### Describe the bug

I had an error pop up then when I tied playing again it will not let me do combat in idle, with the screen off, with the screen minimized or the game closed out.

### Screenshots

![Screenshot_20220205-182420_Melvor Idle](https://user-images.githubusercontent.com/99119728/152676117-4294c658-9868-46e8-9c06-bd1c3acea662.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1530

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-02 21:52
Duplicate of #2150

**Closed by coolrox95** 2022-03-02 21:52 UTC
Labels: bug, Duplicate
