### ISSUE TITLE
[Bug]: "Ghost" farming skill during tutorial island

### ISSUE THREAD

**Issue by RanDumSocks** [MelvorIdle/melvoridle.github.io#3362] opened 2023-04-18 04:27 UTC
### Describe the bug

There is a "ghost" skill at the bottom of the skill list during the farming section of tutorial island. Clicking it does nothing, and seems to just be a minor bug pointing to a non-existent skill.

This is with the expansion enabled

### Reproduction Steps

1. Play tutorial island
2. Get to the farming tutorial
3. Bug time

### Expected behaviour

The tutorial will point to the passive farming skill and not create a non-existent skill.

### Screenshots

![image](https://user-images.githubusercontent.com/23219465/232670976-d2d5b294-17e7-49df-89aa-1fc698e9643d.png)

### Console output

N/A
logs are normal without errors

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

5890

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-08-26 16:29
Duplicate of #3396

**Closed by coolrox95** 2023-08-26 16:29 UTC
Labels: bug
