### ISSUE TITLE
[Bug]: OK Button for chest contents is missing classes

### ISSUE THREAD

**Issue by xanderput** [MelvorIdle/melvoridle.github.io#2075] opened 2022-01-18 15:16 UTC
### Describe the bug

When clicking "View chest contents" in bank or in dungeon overview, the ok button in the window that opens is missing some classes. Without these classes the button looks ugly. It only has the class "swal2-confirm" instead of "swal2-confirm btn btn-primary m-1".

### Reproduction Steps

1. View chest contents
2. See ugly button

### Expected behaviour

See nice button :)

### Screenshots

![image](https://user-images.githubusercontent.com/39944140/149964564-ef287e48-3aaa-459a-82ea-54c4eda414fb.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1419

### Are you using any scripts or extensions?

No

**Comment by xanderput** [comment] 2022-01-24 11:23
Same thing happens on the combat screen. When clicking Magic / Prayer / Summoning / "Browse slayer areas" / "New Task" if the respective skill is still locked on adventure mode.
You also get that same OK button while doing stuff like trying to bury bones through bank, while prayer is still locked.

These buttons: 
![image](https://user-images.githubusercontent.com/39944140/150773694-cf77ddc4-1d82-4c78-89ba-c339d8b21668.png)
![image](https://user-images.githubusercontent.com/39944140/150773613-5695fbc6-2fca-4d03-b851-df528d974a68.png)
![image](https://user-images.githubusercontent.com/39944140/150773819-4911f7e7-89dc-474b-841f-9bad367ef88c.png)
![image](https://user-images.githubusercontent.com/39944140/150774191-0c9296d6-90d4-4798-bc73-e7a5fcb7f3e5.png)


Cause this: 
![image](https://user-images.githubusercontent.com/39944140/150773657-83c3b644-6962-4cdc-a3aa-ebb59fde235f.png)

**Comment by coolrox95** [comment] 2022-03-07 19:39
Duplicate of #1883

**Closed by coolrox95** 2022-03-07 19:39 UTC
Labels: bug, Duplicate, Visual Bug
