### ISSUE TITLE
[Bug]: freezing/crashing

### ISSUE THREAD

**Issue by Grimmfalls** [MelvorIdle/melvoridle.github.io#2958] opened 2022-11-11 21:12 UTC
### Describe the bug

I'm experiencing constant lockups and crashing issues doing any and all actions I'm using a Samsung s22ultra with the most recent update. The app is also fully updated. It's almost unplayable in this state.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4695

### Are you using any mods?

No

**Comment by Tsundere115** [comment] 2022-11-16 00:49
Yep, got the exact same issue, literally can't even play just  to collect my stuff before "game has stopped responding" pops up, altho I can keep playing by just hitting "wait" every time it pops up but that's not fun

**Comment by Mot92** [comment] 2022-11-17 14:35
Good afternoon, after the last update v4908, this error reappeared. I am attaching the error code and screenshot. The error appears constantly even if  do not perform any actions in the game, regardless of the menu item. Before today's update, everything worked stably. 

XIAOMI Mi 10lite 5g. Miui 13.0.4 Android 12

[video ](https://youtu.be/ugznIah8e6U) 

Code:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.feedback/com.google.android.feedback.FeedbackActivity}: java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3761)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3935)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:9300)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2971)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2935)
	at com.google.android.feedback.FeedbackSession.getTelephonyInfo(FeedbackSession.java:307)
	at com.google.android.feedback.FeedbackSession.<init>(FeedbackSession.java:152)
	at com.google.android.feedback.FeedbackSession.<init>(FeedbackSession.java:141)
	at com.google.android.feedback.FeedbackActivity.pushSession(FeedbackActivity.java:209)
	at com.google.android.feedback.FeedbackActivity.createFeedbackSession(FeedbackActivity.java:178)
	at com.google.android.feedback.FeedbackActivity.onCreate(FeedbackActivity.java:96)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3734)
	... 12 more

![Screenshot_2022-11-17-18-13-12-465_com miui bugreport](https://user-images.githubusercontent.com/57660738/202474516-473dd9ae-873c-4f6c-9a9d-324cd2f986c0.jpg)

**Comment by coolrox95** [comment] 2023-03-25 22:37
Duplicate of #2694

**Closed by coolrox95** 2023-03-25 22:37 UTC
Labels: bug, Duplicate
