### ISSUE TITLE
[Bug]: <Game doesn't close when closing it and stays open in the background>

### ISSUE THREAD

**Issue by MKBernsons** [MelvorIdle/melvoridle.github.io#1810] opened 2021-11-26 21:36 UTC
### Describe the bug

If I close the game window it appears to be closed but on steam it still says that I am playing it and it is still very much running in the background if I open and check task manager.
I can close it trough the task manager doe.
P.S. I can't close the game by clicking stop trough steam.

### Reproduction Steps

This is what I always do when I open the game:

I open the game
Go into 1st of my 2 characters
do my stuff (the stuff that I do can vary wildly)
force save
exit 1st character and switch to the 2nd character
do my stuff on that character
force save again
Close the game with the X at top right
it remains open in the background :(

### Expected behaviour

I expect the game to close fully

### Screenshots

![Screenshot_Melvor_Bug](https://user-images.githubusercontent.com/87810247/143656450-04e5e99a-ec0d-4116-ba2c-8431efe7ad73.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1349

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment] 2021-11-29 01:15
Duplicate of #1712

**Closed by MelvorIdle** 2021-11-29 01:15 UTC
Labels: bug
