### ISSUE TITLE
[Bug]: gemstone gloves proc on new pure essence

### ISSUE THREAD

**Issue by Cruiserman19** [MelvorIdle/melvoridle.github.io#2743] opened 2022-10-21 12:54 UTC
### Describe the bug

Gemstone mining gloves are ticking down when they are not supposed to. Mining the new pure essence causes the gloves to proc
Edited out the gem nodes
### Reproduction Steps

Equip gemstone gloves
Mine pure essence 

### Expected behaviour

Not tick down gloves uses

### Screenshots

![Screenshot_20221021-074954_Melvor Idle](https://user-images.githubusercontent.com/116360583/197199869-da224d59-6d77-400e-b505-e810c519f14f.jpg)
![Screenshot_20221021-075000_Melvor Idle](https://user-images.githubusercontent.com/116360583/197199898-edd39a4f-0b59-415f-88c2-794554c39277.jpg)
![Screenshot_20221021-075006_Melvor Idle](https://user-images.githubusercontent.com/116360583/197199920-aac29037-87d0-41ce-9d37-11d208e56a42.jpg)
![Screenshot_20221021-075021_Melvor Idle](https://user-images.githubusercontent.com/116360583/197199935-fad6d048-dee4-4543-a91c-e8042a52cfe4.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4516

### Are you using any mods?

No

**Comment by Cruiserman19** [comment] 2022-10-21 12:58
Scratch the gem stone nodes not working retested and gloves don't proc

**Comment by coolrox95** [comment] 2022-10-21 15:54
Duplicate of #2720

**Closed by coolrox95** 2022-10-21 15:54 UTC
Labels: bug, Duplicate
