### ISSUE TITLE
Knight does not unlock at level 88 of thieving[Bug]: <title>

### ISSUE THREAD

**Issue by MildDiscomfort** [MelvorIdle/melvoridle.github.io#2263] opened 2022-03-01 08:43 UTC
### Describe the bug

Thieving has reached level 88 and Knight has not unlocked.

### Reproduction Steps

Get to level 88 of thieving

### Expected behaviour

Can pick pocket knight

### Screenshots

![88](https://user-images.githubusercontent.com/10940376/156134977-1d7547a3-3426-4c1b-b5da-37ce39302553.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1806

### Are you using any scripts or extensions?

No

**Comment by LotoGitH** [comment] 2022-03-01 15:13
I have the same error but since early levels in thieving:

![image](https://user-images.githubusercontent.com/19735146/156194936-36a7ef1c-2536-47db-a166-ca3bedd11e90.png)

Monsters are not unlock, by leveling up.

**Comment by coolrox95** [comment] 2022-03-01 22:12
Duplicate of #2257

**Closed by coolrox95** 2022-03-01 22:12 UTC
Labels: bug, Duplicate

**Comment by LotoGitH** [comment] 2022-03-01 22:14
I got some things that may help in this one.

MODE: Adventure character

My character name is Legolas by the way, and yess, him elf eyes are pretty damn cool

Also, when i close the game and reopen just a few minutes the new  mosters came available, but the new ones unlock in game time or offline still lock.

The thing is, if i whant to get the unlock i need to close and reopen game.

Hopefully this will help.

BTW i love the game, i want to be more useful, i am a programer, so, if i can help im please.

Have a nice day.
