### ISSUE TITLE
Axe, pickaxe and fishing rod upgrades text

### ISSUE THREAD

**Issue by PIKMYN** [MelvorIdle/melvoridle.github.io#3084] opened 2022-12-12 02:46 UTC
### What text is wrong?

<img width="362" alt="Screenshot 2022-12-12 at 02 39 42" src="https://user-images.githubusercontent.com/32957040/206949264-017ceda3-4c7b-43de-a83a-ba24fe36e7c6.png">

all upgrades are missing 5% reduction in the text. example: iron axe has 0% (doesn't display anything, looks bugged), steel has -5%, Dragon has -45%.

The reduction itself seems to not be missing though, this just seems to be an error with the text on the display in the image.

### What is the correct spelling or grammar?

add -5% to the total of all upgrades for the axe, pickaxe and fishing rod text

**Comment by coolrox95** [comment] 2023-03-25 05:26
Duplicate of #3034

**Closed by coolrox95** 2023-03-25 05:26 UTC
Labels: Duplicate, spelling/grammar
