### ISSUE TITLE
[Bug]: Game stays open in background (Steam)

### ISSUE THREAD

**Issue by SK-Crow** [MelvorIdle/melvoridle.github.io#4456] opened 2024-06-25 22:04 UTC
### Describe the bug

I've been noticing that if I idle the game for 12 hours or so, then press the X at the top right, Steam will think it's still running.  Then, when I check task manager, I see Melvor is still running.  Steam is unable to kill the process, and I must manually kill it via task manager.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery
- [X] Into the Abyss

### Which version of the game are you experiencing this bug on?

v1.3

### Game Subversion

?11516

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2024-06-28 02:13
Duplicate of #4395

**Closed by coolrox95** 2024-06-28 02:13 UTC
Labels: bug, Duplicate
