### ISSUE TITLE
Normal log sale price is 1.5gp, should be 1gp.

### ISSUE THREAD

**Issue by fordred1993** [MelvorIdle/melvoridle.github.io#674] opened 2021-01-29 17:41 UTC
To Reproduce Steps to reproduce the behavior:

Go to 'bank'
Click on 'normal logs'
Scroll down to 'sell item (any quantity)'
See error 'sale price should be 1gp, the game is trying to sell for 1.5gp'
Expected behavior A clear and concise description of what you expected to happen. 'sale price of normal log should be 1gp'
Browser - Chrome
Are you using any scripts? Melvor Idle Combat Simulator Reloaded, only.

**Comment by fordred1993** [comment] 2021-01-29 17:45
edit: sorry, the game trys to add 0.5gp to the sale of **yew and redwood**  logs, not just normal logs. There may be other but I don;t have any others other than magic logs in my bank. magic logs are not adding 0.5gp.

**Comment by imperialboy3** [comment] 2021-02-02 17:35
This is caused by 50% mastery pool in Woodcutting. It isn't a bug but can be confusing since the individual sale price only shows the whole number.

**Comment by MelvorIdle** [comment] 2021-02-17 00:48
Fixed in upcoming update.

**Closed by MelvorIdle** 2021-02-17 00:48 UTC
Labels: bug
