### ISSUE TITLE
Chicken Soup Appeared in stockpile without required ingredients

### ISSUE THREAD

**Issue by beccsplease** [MelvorIdle/melvoridle.github.io#1421] opened 2021-10-03 15:35 UTC
**Describe the bug**
The Chicken Soup appeared in my stockpile without the required ingredients or ever starting the passive cooking. I know this because in my items completion log I never acquired cream.

**To Reproduce**
Steps to reproduce the behavior: I'm not entirely sure how to recreate this bug but I'll try to describe what I did.
1. I was actively cooking cave fish, passively cooking apple pies, and was using tier 3 cooking potions as well as the cooking gloves and selected the chicken soup recipe but did not passively cook (because I lacked the ingredients).
2. I swapped tabs and had the pause actions for skills when tab is minimized or in background setting enabled.
3. I had left the tab in the background for a while (I'm unsure of how long I left it but I ended up with 708 chicken soup so working back would put me at ~82-83 minutes)

**Expected behavior**
I would expect the chicken soup not to be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/91838804/135760880-95d23146-b450-47d9-addd-ccdd2dbb924a.png)
first is proof that I got the chicken soup without cream and second is showing a friend's save who has bought the cream to show where it should be in the items list
![image](https://user-images.githubusercontent.com/91838804/135761088-e0430cda-7c4f-4d30-850f-87738eeeb0b3.png)

**Browser**
Google Chrome 94.0.4606.61

**Console output**
I had reloaded the page before copying so I'm not sure if this will be of any use.

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
save.js?1180:57 set force reload to 2
combatManager.js?1180:1 Combat Manager Built...
raidManager.js?1180:1 Golbin Raid Manager Built...
save.js?1180:14 Loading Save Game...
save.js?1180:14 Save Game Loaded...
main.js?1180:5 Game Loaded
main.js?1180:252 TypeError: Cannot read properties of undefined (reading 'cookingInterval')
    at main.js?1180:160
(anonymous) @ main.js?1180:252
(index):1 Uncaught (in promise) Error processing offline in-timeout
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
Not using any scripts

**Comment by coolrox95** [comment] 2021-10-03 19:19
Duplicate of #1393

**Closed by coolrox95** 2021-10-03 19:19 UTC
Labels: Duplicate
