### ISSUE TITLE
[Bug]: <Can Cast Poison Pod with out runes>

### ISSUE THREAD

**Issue by Mpotityo** [MelvorIdle/melvoridle.github.io#2905] opened 2022-11-03 23:28 UTC
### Describe the bug

By switching to Poison Pod and then switching to another spell before the cast timer goes off. You're able to cast the spell and poison the enemy.

### Reproduction Steps

1: Start Casting
2: Click on Poison Pod
3: before cast finishes click on a different spell

### Expected behaviour

It shouldn't be able to apply the debuffs with out the runes

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

74675

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 00:28
Duplicate of #2796

**Closed by coolrox95** 2023-03-25 00:28 UTC
Labels: bug, Duplicate
