### ISSUE TITLE
Skeleton Fish Prayer Points

### ISSUE THREAD

**Issue by Munkeywaxx** [MelvorIdle/melvoridle.github.io#1382] opened 2021-09-27 13:20 UTC
**Describe the bug**
Skeleton Fish showing 2 values for restoring prayer points.

**To Reproduce**
1. Go to Bank
2. Click on Skeleton Fish

![image](https://user-images.githubusercontent.com/3329277/134916549-1735b0fb-dd64-496b-9460-4dd33bec6db6.png)

**Browser**
Steam

**Are you using any scripts?**
No

**Comment by coolrox95** [comment] 2021-09-29 04:05
Duplicate of #1327

**Closed by coolrox95** 2021-09-29 04:05 UTC
Labels: Duplicate
