### ISSUE TITLE
Thieving Gloves Description Incorrect after Overhaul

### ISSUE THREAD

**Issue by NickestNick** [MelvorIdle/melvoridle.github.io#1415] opened 2021-10-02 00:05 UTC
**Describe the bug**
The Thieving Gloves description is still listed as it was in the previous update (prior to the massive thieving overhaul). On the Thieving page, when hovering over the thieving gloves icon next to remaining actions, it states "+10% success rate" as opposed to what I believe it should state, "+75 Thieving Stealth" following the thieving overhaul. The icon that enables one to equip the gloves from the thieving screen above the 'View Summoning Synergy Search" displays the correct information.

**To Reproduce**
1. Purchase Thieving Gloves and equip them
2. Navigate to Thieving Page
3. Hover mouse over thieving gloves icon next to 'REMAINING ACTIONS: [N]" - Screenshots posted below

**Expected behavior**
See above - On the Thieving page, when hovering over the thieving gloves icon next to remaining actions, it states "+10% success rate" as opposed to the "+75 Thieving Stealth" that it should display following the thieving overhaul.

**Screenshots**

![image](https://user-images.githubusercontent.com/91764902/135697030-3a473093-778b-4947-8f08-5560327ad404.png)

![image](https://user-images.githubusercontent.com/91764902/135697040-79668e0f-0e3b-49fe-bda8-4a412b4a85d1.png)

**Browser**
On Steam

**Are you using any scripts?**
No Scripts used.

**Comment by coolrox95** [comment] 2021-10-03 08:00
Duplicate of #1405

**Closed by coolrox95** 2021-10-03 08:00 UTC
Labels: Duplicate
