### ISSUE TITLE
Mining glove charged, but no glove?

### ISSUE THREAD

**Issue by jpdeveau** [MelvorIdle/melvoridle.github.io#1541] opened 2021-10-31 18:57 UTC
When I buy mining gloves I get the number of charges correctly, even though it says owned I never actually receive gloves to wear.

To reproduce buy a mining glove from the shop. Please note I don't currently have any.

I don't know how to put the console output here in Android.

**Comment by coolrox95** [comment] 2021-11-02 22:28
Duplicate of #1332

**Comment by coolrox95** [comment] 2021-11-11 05:09
Fixed as of Beta v1.0.

**Closed by coolrox95** 2021-11-11 05:09 UTC
Labels: bug, In Progress
