### ISSUE TITLE
Mining nodes not respawning

### ISSUE THREAD

**Issue by EvanN98** [MelvorIdle/melvoridle.github.io#881] opened 2021-03-21 22:20 UTC
**Describe the bug**
As I got further in to mining (etc. unlocking Mithril and above), the ore nodes began to take a day or two to replenish. I'm assuming this isn't an implemented game mechanic, but I could be wrong. Recently, I've ended up having 2 empty at the same time for a day or two, usually Runite and Dragonite.

**To Reproduce**
1. Go to Mining
2. Click on any ore to begin mining
3. Let node HP deplete
4. See that it will not replenish HP for prolonged amount of time

**Expected behavior**
I'm assuming it shouldn't take more than a couple of minutes for it to replenish HP?

**Browser**
ios Alpha 0.19.1

**Are you using any scripts?**
None

**Comment by coolrox95** [comment] 2021-11-02 22:35
Duplicate of #697

**Closed by coolrox95** 2021-11-02 22:35 UTC
Labels: Duplicate
