### ISSUE TITLE
Game zoomed in when loadind on app.

### ISSUE THREAD

**Issue by Cypress65** [MelvorIdle/melvoridle.github.io#2318] opened 2022-03-11 03:00 UTC
### Describe the bug

When I open the app everything is zoomed in to where its hard to play.   Cleared cache worked once to play but happens again when going back in the game.

### Screenshots

![Screenshot_20220310-215519_Melvor Idle](https://user-images.githubusercontent.com/101377126/157793667-590e5c0d-b8fe-4349-860f-3d33e3d0c623.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1843

### Are you using any scripts or extensions?

No

**Comment by Cypress65** [comment] 2022-03-11 03:08
Ok so I just  wiped the cache partition on my phone and it seemed to work  so far. So maybe it was from a update to my phone?

**Comment by coolrox95** [comment] 2022-03-11 03:54
Duplicate of #2290

**Closed by coolrox95** 2022-03-11 03:54 UTC
Labels: bug, Duplicate

**Comment by Jesus-love-you07** [comment] 2022-12-12 17:06
I don't know what you may have had/been through in your lives, but I want to tell you that it doesn't just look like it, but it goes far beyond. So, I invite you all to accept Jesus Christ in your life by believing that he died for you on the cross and confessing in your heart that he is your lord and savior, then all your burdens will disappear and you will have access to true happiness that will lead you to an eternal life. The where death/fear etc does not rest. ❤️
https://youtu.be/XIb_dCIxzr0
https://youtu.be/0k4GbvZUPuo

**Comment by Jesus-love-you07** [comment] 2022-12-12 17:06
I don't know what you may have had/been through in your lives, but I want to tell you that it doesn't just look like it, but it goes far beyond. So, I invite you all to accept Jesus Christ in your life by believing that he died for you on the cross and confessing in your heart that he is your lord and savior, then all your burdens will disappear and you will have access to true happiness that will lead you to an eternal life. The where death/fear etc does not rest. ❤️
https://youtu.be/XIb_dCIxzr0
https://youtu.be/0k4GbvZUPuo
