### ISSUE TITLE
[Bug]: Astrology Info Page Broken

### ISSUE THREAD

**Issue by Carson402** [MelvorIdle/melvoridle.github.io#3037] opened 2022-11-26 18:30 UTC
### Describe the bug

Astrology Info Page is not working.

### Reproduction Steps

1. Go to Astrology Skill Page
2. Click on skill icon (top left)
3. Info page should drop down with tips and info on the current skill, Astrology
4. nothing happens when I click the astrology button

### Expected behaviour

Info page should drop down with tips and info on the current skill, Astrology.

### Save Link

https://melvoridle.com/save/P5tQIT3h

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4928

### Are you using any mods?

No

**Comment by coolrox95** [comment] 2023-03-25 05:03
Duplicate of #2922

**Closed by coolrox95** 2023-03-25 05:03 UTC
Labels: Duplicate
