### ISSUE TITLE
Bank Tab icon is not updated when items are added/removed from empty bank tab

### ISSUE THREAD

**Issue by mazunki** [MelvorIdle/melvoridle.github.io#502] opened 2020-11-29 06:49 UTC
**Describe the bug**
Icons for bank tabs are not updated on enemy drops.

**To Reproduce**
1. Go to bank
2. Make any item go to a tab
3. Empty tab by selling all items
4. Collect said item which goes into tab
5. Tab appears as if no items are in it

**Expected behavior**
Collected item becomes tab icon

**Browser**
Steam

**Are you using any scripts?**
No

**Comment by mazunki** [comment] 2020-11-29 06:56
As a note: Moving any item afterwards between any tabs will update unregistered tab icons. Still annoying, as I use a tab for all items I want to sell, and that happens more often than me moving items around.

**Comment by coolrox95** [comment] 2021-09-04 21:00
This seems to be a general issue with the bank tab image not updating when items are added/removed from the bank.
Was able to reproduce simply by calling `addItemToBank(CONSTANTS.item.Water_Rune,1)` when the first tab of the bank was empty. Similarly equipping an item when it is the only item in a tab, will not update the tab to show as empty after.

**Comment by MelvorIdle** [comment] 2021-11-13 02:47
Fix has been applied to the game

**Closed by MelvorIdle** 2021-11-13 02:47 UTC
Labels: bug
