### ISSUE TITLE
Most recent save label is wrong

### ISSUE THREAD

**Issue by spifferoo** [MelvorIdle/melvoridle.github.io#778] opened 2021-03-07 21:03 UTC
The "old save" and "most recent save" labels on the character select screen are applied incorrectly. (see screenshots below)
This issue is the same as ticket #772 but with repro steps

1. Create 2 saves and save both to cloud
2. Switch devices and load save slot 1 from the cloud
3. Go back to character select screen
4. The "most recent save" label for save slot 2 will mimic whatever save slot 1 is, even if that is incorrect

https://i.imgur.com/nCUAi61.png - local saves
https://i.imgur.com/bpHyJ5U.png - cloud saves

I'm using both the firefox version and the android version and this bug appears on both

**Comment by coolrox95** [comment] 2021-09-05 01:14
Duplicate of #772

**Closed by coolrox95** 2021-09-05 01:14 UTC
Labels: Duplicate
