### ISSUE TITLE
When you equip/bury something from the bank the count of items in the bank isn't updated until a sort is done or until a new item is added to the bank.

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#643] opened 2021-01-16 04:01 UTC
**Describe the bug**
When you equip/bury something from the bank the count of items in the bank isn't updated until a sort is done or until a new item is added to the bank.

**To Reproduce**
1. Go to Bank
2. Click on Bones (Or arrows/bolts/gear)
3. Check the current number of items in bank
3. Bury bury all bones (Or equip all arrows/bolts/gear)
4. Check the new number of items in bank

**Expected behavior**
Number of items in the bank accurately reflects the actual number

**Browser**
Firefox

**Are you using any scripts?**
No

**Comment by mazunki** [comment] 2021-01-20 21:09
Learning that you can just press Sort to update it is actually so useful. I've been changing characters to update it until now. Really annoying when running low on bank space.

**Comment by coolrox95** [comment] 2021-09-04 21:31
Closing this as I cannot reproduce this in the current version (Alpha v0.21 (?1098).

**Closed by coolrox95** 2021-09-04 21:31 UTC
Labels: Cant Reproduce
