### ISSUE TITLE
Thieving Mastery Display

### ISSUE THREAD

**Issue by mcaterino-sudo** [MelvorIdle/melvoridle.github.io#576] opened 2020-12-24 05:30 UTC
**Describe the bug**

When opening the thieving window, the mastery for each NPC is wrongly displayed as 70. This reverts back to the actual values
once an NPC is clicked and the thieving process begins

**To Reproduce**

1. Open the thieving window lol
2. See error

**Expected behavior**

The masteries should display the actual mastery value.

**Screenshots**
![image](https://user-images.githubusercontent.com/55106123/103063240-b03e4980-457e-11eb-9e6b-f08cfca7d389.png)
![image](https://user-images.githubusercontent.com/55106123/103063259-c0562900-457e-11eb-808b-d27ca6a4ae50.png)

**Browser**

Chrome

**Console output**

DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.melvor.net/sm/13c28911820333eb6a51103a0e2096477a38941cc79afbf16b59f3d5a5f63086.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
Nope

**Comment by coolrox95** [comment] 2021-09-04 21:20
Closing this as I cannot reproduce it in Alpha v0.21 (?1118).

**Closed by coolrox95** 2021-09-04 21:20 UTC
Labels: Cant Reproduce
