### ISSUE TITLE
Offline calculation errors

### ISSUE THREAD

**Issue by Saerkyne** [MelvorIdle/melvoridle.github.io#1124] opened 2021-07-09 00:35 UTC
**Describe the bug**
There is an error when calculating offline progress in the browser version (Mozilla Firefox), that says please let the dev know of the error. Skill progress is stopped, and sometimes the skill that I was training will no longer work until I close my browser and reopen. 

I have not tested on the Steam version or the Android version. 

**To Reproduce**
1. Open Melvor  Idle in Mozilla Firefox ver. 89.0.2
2. Start a skill for offline training
3. navigate to a new tab
4. after some time, return to the game tab
5. instead of calculating offline progress, the game throws an error. 

**Expected behavior**
I expected offline progress calculation when returning to the game tab from another tab.

**Screenshots**
![Screenshot 2021-07-08 203332](https://user-images.githubusercontent.com/87156643/125006296-c8ae1700-e02b-11eb-90c4-2ffbc7992edb.png)

**Browser**
Mozilla Firefox, ver 89.0.2

**Console output**
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-129674422-1”. melvoridle.com:6:1
Loading failed for the <script> with source “https://ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js”. melvoridle.com:24:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. melvoridle.com:491:1
MICSR: playerSpecialNames is waiting for util MICSR.js:26:31
MICSR: setting up util MICSR.js:26:31
MICSR: setting up statNames MICSR.js:26:31
MICSR: AgilityCourse is waiting for modifierNames MICSR.js:26:31
MICSR: AgilityCourse is waiting for Card MICSR.js:26:31
MICSR: setting up modifierNames MICSR.js:26:31
MICSR: no unknown modifiers detected! modifierNames.js:543:25
MICSR: setting up Card MICSR.js:26:31
MICSR: setting up Menu MICSR.js:26:31
MICSR: setting up Import MICSR.js:26:31
MICSR: setting up TabCard MICSR.js:26:31
MICSR: setting up Plotter MICSR.js:26:31
MICSR: setting up Loot MICSR.js:26:31
MICSR: main is waiting for App MICSR.js:26:31
MICSR: setting up CombatData MICSR.js:26:31
MICSR: setting up Simulator MICSR.js:26:31
MICSR: App is waiting for AgilityCourse MICSR.js:26:31
MICSR: setting up playerSpecialNames MICSR.js:26:31
MICSR: setting up AgilityCourse MICSR.js:26:31
MICSR: setting up App MICSR.js:26:31
MICSR: setting up main MICSR.js:26:31
loadCharacterSelection main.js:262:594
Some cookies are misusing the recommended “SameSite“ attribute 8
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ oneui.core.min.js:6:81449
loadCharacterSelection main.js:262:594
Connected to PlayFab successfully cloud.js:76:144
set force reload to 0 save.js:71:60
Loading Save Game... save.js:13:9
Save Game Loaded... save.js:29:95
Game Loaded main.js:20:405
Array [ 0, 0 ]
main.js:118:817
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. update_v020.html:928:1
Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js”. index.html:565:1
Connected to PlayFab successfully cloud.js:76:144
Synchronising with Cloud cloud.js:8:154
MICSR: Melvor Combat Sim v1.4.2 Loaded MICSR.js:26:31
Array [ 0, 0 ]
main.js:118:817
true main.js:252:116
Array [ 0, 0 ]
main.js:118:817
setItem@https://melvoridle.com/assets/js/game/save.js?960:8:42
saveData@https://melvoridle.com/assets/js/game/save.js?960:11:384
updateOffline/offlineProgressTimer<@https://melvoridle.com/assets/js/game/main.js?960:243:619
main.js:243:883
Uncaught DOMException: The quota has been exceeded. save.js:8
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! melvoridle.com
Uncaught DOMException: The quota has been exceeded. save.js:8
Attempting to fix your save... wish me luck save.js:61:90
Uncaught DOMException: The quota has been exceeded. save.js:8
true main.js:252:116
Uncaught DOMException: The quota has been exceeded. save.js:8
Array [ 0, 0 ]
main.js:118:817
setItem@https://melvoridle.com/assets/js/game/save.js?960:8:42
saveData@https://melvoridle.com/assets/js/game/save.js?960:11:251
startFishing@https://melvoridle.com/assets/js/game/fishing2.js?960:1:2136
updateOffline/offlineProgressTimer<@https://melvoridle.com/assets/js/game/main.js?960:141:435
main.js:243:883
Synchronising with Cloud

**Are you using any scripts?**
I have the Combat Simulator installed, but was not actively using it at the time. No other scripts were in use.

**Comment by coolrox95** [comment] 2021-11-04 08:07
Duplicate of  #1562

**Closed by coolrox95** 2021-11-04 08:07 UTC
Labels: Duplicate
