### ISSUE TITLE
[Bug]: "Pile of Logss" is pluralized incorrectly

### ISSUE THREAD

**Issue by Tyriar** [MelvorIdle/melvoridle.github.io#1791] opened 2021-11-24 04:56 UTC
### Describe the bug

See screenshot:

![image](https://user-images.githubusercontent.com/2193314/143177288-512e85dd-eba3-4f91-bc96-054a01083012.png)

Same with Oress

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

1348

### Are you using any scripts or extensions?

No

**Comment by coolrox95** [comment] 2022-03-06 08:46
Duplicate of #1409

**Closed by coolrox95** 2022-03-06 08:46 UTC
Labels: Duplicate, spelling/grammar
